### ISSUE TITLE
Field State Sync Issue in Strict vs Non-Strict Mode in react-18

### ISSUE THREAD

**Issue by sudkumar** [final-form/react-final-form#1009]
First of all, thank you so much for putting so much effort in improving Forms in react or in general. 🙇‍♂️ 

### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behaviour?

Updating a field value before a component mounts, doesn't reflect the new values. More details bellow ⬇️ 

### What is the expected behaviour?

Expected to get the latest updated values in every render of a component instance

### Sandbox Link

https://codesandbox.io/embed/suspicious-snow-9xqnog?fontsize=14&hidenavigation=1&theme=dark

### What's your environment?

- React: 18.2
- React-DOM: 18.2
- Final-Form: 4.20.7
- React-Final-Form: 6.5.9

### Other information

The problem started when I deployed an application to staging for testing purpose and some initial values were left empty. Everything was working as expected during development. 

I tried to reproduce it on my machine, but didn't succeeded. 🤯 . I used react-dev-tools in production (🆘 ) and found out that some subscribers had values whereas other didn't. I thought about the diffs between dev and prod and First thing: `StrictMode`. Removed it and reproduced the issue. 🐛   

I will start by taking some code snippets from the above sandbox.

```jsx
const App = () => <Form onSubmit={() => undefined} subscription={{ submitting: true }}>
{({ handleSubmit }) => (
  <form onSubmit={handleSubmit}>
   {/* This is the behaviour in development */}
    <StrictMode>
      <fieldset>
        <legend>First Name (StrictMode)</legend>
        <Field name="firstname" component="input" /> {/* This will have the updated values */}
        <SetFieldValueIfEmpty name="firstname" />
        <Field name="firstname" component="input" /> {/* This will have the updated values */}
      </fieldset>
    </StrictMode>
   {/* This is the behaviour in production */}
   <fieldset>
     <legend>Last Name (StrictMode)</legend>
      <Field name="lastname" component="input" /> {/* This will have the updated values */}
      <SetFieldValueIfEmpty name="lastname" />
      <Field name="lastname" component="input" /> {/* This will NOT have the updated values */}
   </fieldset>
  </form>
)}
</Form>

function SetFieldValueIfEmpty({ name }) {
  const { input: { value, onChange } } = useField(name, { subscription: { value: true } })
  useEffect(() => {
   if (!value) onChange('default value')
  }, [value, onChange])
}
```

![Shot 1](https://user-images.githubusercontent.com/6812992/195013229-28c1d122-e170-41a9-a891-37fb5d17d9ac.png)

With the new behaviour in `react-18`'s StrictMode, all `useEffect` are called twice to ensure proper cleanup.  So in the first `SetFieldValueIfEmpty` component, `onChange` is called twice but not in the second `SetFieldValueIfEmpty`. This new behaviour hides the synching problem during the development but causes issues in production.

In conclusion, if we change the field values in an effect, before a field renders (subscribes to field value), the rendered field doesn't get the new values.

#### Why would someone change the field values this way ?

I am working on a SASS application for Travel Agencies where a user can create Quotes for Tour packages. The quote may include Accommodation, Transports, Activities etc. In the Activities, the user will select an activity and the application will generate a tickets configuration based on Adults and Children.

![Shot 2](https://user-images.githubusercontent.com/6812992/195017812-d4a00e4c-c6f4-481b-bc57-d058bdf6d6d1.png)

The `right-side` is a components that usages `react-final-form-array` which loops over the ticket and does the work. The parent component is the one generating a default configuration of tickets and updating the field value if not already set.

I wanted to isolate this `default configuration setup` so that the component in the right-side doesn't re-render on every change.  At first, I put the synching component before the `right-side` component. Things were working on my local but failed on production and tickets were set to empty. Then I moved the synching component after the `right-side` component and everything was working in production as well. QA team reported some other issues which were similar to this synchronising behaviour. 

### Workarounds for Now

1. Move the synchroniser (`SetFieldValueIfEmpty`) down in the tree
2. Move the logic into the rendering component itself i.e. Create a new component that set the values in `useEffect` and also render the `input` field.

**Comment by shulcsm** [comment]
I wonder if the whole thing should not be using useSyncExternalStore?

**Comment by gertdreyer** [comment]
The SetFieldValueIfEmpty violates React functional component principles and possibly the rules of hooks. 

For this kind of behaviour see [subscribe](https://final-form.org/docs/final-form/types/FormApi#subscribe).

**Comment by sudkumar** [comment]
Hi @gertdreyer. Thank you. I will checkout the subscribe API.

Can you please elaborate the violation of react functional components/hooks principles in the above example?

**Comment by gertdreyer** [comment]
A functional component have to return a [React Element](https://reactjs.org/docs/components-and-props.html#function-and-class-components) . Similarly, a class-style component has to have a render method. 

On the `useEffect`. Try playing with `console.count(fieldname)` in the useEffect to see the inefficiency. useEffect is actioned after the every render - you know before rendering that your field needs a default value. You also open yourself up to infinite render loops using setState in a useEffect if your condition is not well defined.

**Comment by sudkumar** [comment]
1. It was a typo to not add a `return null` but that won't change the strict behaviour. You will still see the results shown in the screenshot.
2. It should be safe to call `setState` or `field.change` inside` useEffect` with my conditions. The only (variable)  dependency to the Effects the value.

---

Just wanted to clarify again that the issue is between the above functionality during React's Strict and Non-Strict Modes. In StrictMode, useEffect is executed twice during the first render causing the listeners to execute twice where as in non-StrictMode, listeners fail to correctly set-up.
