### ISSUE TITLE
[request] FormSpy should receive FormApi

### ISSUE THREAD

**Issue by rosskevin** [final-form/react-final-form#101]
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?
`FormSpy` provides access to internal `FormState`, but does not expose a way to comprehend the registered fields.

### What is the expected behavior?
`FormSpy` is passed `FormApi` in addition to `FormState` so that one may call `getRegisteredFields: () => string[]`

### What's your environment?
RFF v2.1.1
React v16.2.0

### Workaround
It looks like I can get `FormApi` from the context as `reactFinalForm`, but I think it a useful addition to provide the `FormApi` to the `FormSpy` unless there is a reason to protect it.
  

BTW - so far everything has been fantastic.  Very solid library, almost no issues converting a mature codebase from react-formal over to this.

**Comment by erikras** [comment]
Fix published in [`v2.2.0`](https://github.com/final-form/react-final-form/releases/tag/v2.2.0).

**Comment by rosskevin** [comment]
Thanks @erikras - I just checked it out and noticed that `getRegisteredFields` is not provided in the `SubsetFormApi`.  Any reason for the omission?

**Comment by erikras** [comment]
Hmmm... it just didn't occur to me. The only part of `FormApi` that I really don't think belongs as a prop are the subscribing methods.

**Comment by rosskevin** [comment]
That is so far the only reason I need to access the context.  I have component that is a catch all for errors that do not match current fields (e.g. field level validation vs record level validation) and displays them above the submit.

Here's the use:

```js
class UnmappedErrors extends React.Component<UnmappedErrorsProps> {
  public static contextTypes = {
    reactFinalForm: PropTypes.object.isRequired,
  }

  public render() {
    const { children } = this.props
    return (
      <FormSpy>
        {({ errors }) => {
          const fieldNames = (this.context.reactFinalForm as FormApi).getRegisteredFields()
          log.debug('render', fieldNames, errors)

          const unmappedErrors: string[] = []
          Object.getOwnPropertyNames(errors).forEach(fieldName => {
            if (!fieldNames.includes(fieldName)) {
              const fullMessage = `${fieldName} ${errors[fieldName]}`
              unmappedErrors.push(fullMessage)
              log.debug(fieldName, ': ', fullMessage)
            }
          })
          return children({ errors: unmappedErrors })
        }}
      </FormSpy>
    )
  }
}
```
