### ISSUE TITLE
Error in codesandbox example

### ISSUE THREAD

**Issue by daniellavi** [final-form/react-final-form#1012]
Hi,

I've found an error in the following codesandbox example:
https://codesandbox.io/s/react-final-form-how-to-get-ref-ekc6m?file=/index.js

In line 38 the 'render' property should be used instead of 'component' because we pass props. Otherwise it won't work.

Thanks,
Daniel

![Screen Shot 2022-10-26 at 14 56 37](https://user-images.githubusercontent.com/42873683/198020195-1e377128-93f6-4560-9b30-0f3c326fee6d.png)

**Comment by gertdreyer** [comment]
Hi Daniel, 
The props do get passed down to the the child component when using component prop. Do you perhaps have a CodeSandbox that demonstrates the error?

Cheers,
Gert
