### ISSUE TITLE
does subscription work correctly?

### ISSUE THREAD

**Issue by akichim21** [final-form/react-final-form#102]
### Are you submitting a **bug report** or a **feature request**?
bug?

### What is the current behavior?
https://codesandbox.io/s/32r824vxy1

does subscription work correctly?
subscription={{ submitting: true, pristine: true }}
not disabled submit button

### What is the expected behavior?
disabled submit button

### Other information
state of ReactFinalForm component is incorrect value when I use subscription props.

when
```
<Form
  subscription={{ submitting: true }} 
/>
```

state of ReactFinalForm component
state === {
  submitting: false
}

why?

**Comment by erikras** [comment]
That sandbox seems to be working properly. The submit button _is_ disabled when submitting. "when submitting" == during the lifetime of the promise returned by `onSubmit`.
