### ISSUE TITLE
Rewrite To Typescript

### ISSUE THREAD

**Issue by Firfi** [final-form/react-final-form#1028]
(the title is an intended pun)

Thank you for a great library!

Looking for libraries and comparing them, I often look at Github's "languages" and I give less attention to libraries still written in JS. 

<img width="338" alt="Screenshot 2023-04-27 at 8 54 12 PM" src="https://user-images.githubusercontent.com/947595/234883892-418cf8e7-303e-40c2-b882-430caa736d88.png">

I believe many people do the same but that could be a fallacy as well.

You use .js file extension for your Typescript code and Github wrongly picks it as JS. 

I believe it would make a good service to your project "SEO" if you use .ts file extensions

**Comment by BATCOH** [comment]
Actually, the usage of the .js extension is reasonable - it's not typescript.
AFAIK the library was written at a time when ts wasn't as popular as it is now.
And it mainly uses [flow](https://flow.org/) for types.

There are some similarities between flow and typescript, but they are different. And to switch to typescript you really need to rewrite the code, changing the extension will not be enough.

**Comment by Firfi** [comment]
Oh, my bad - thank you for this clarification! I failed to recognize Flow as haven't worked with it at all. I shall close this issue as it now could be considered a shitpost lol.
