### ISSUE TITLE
How to correctly set the name of the Field for the object with numeric keys?

### ISSUE THREAD

**Issue by em-ka** [final-form/react-final-form#103]
Hi @erikras again!

### Are you submitting a **bug report** or a **feature request**?

Probably a bug report.

### What is the current behavior?

I'm not able to set the correct radio button field name for the following structure:
```
answers: {'0': '1', '1': '2'}
```

### What is the expected behavior?

I think the correct way should be something like:
```
<Field
   name="answers['0']"
   component="input"
   type="radio"
   value="0"
/>
```
But I've unsuccessfully tried `answers[0]`, `answers.0` too. With the first one, initialValues of the Form are set correctly, but any change of the field will rise an error: Cannot set a numeric property on an object (see the sandbox link)

### Sandbox Link

[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n9qqp1pxx4)

### What's your environment?

RFF 2.1.1., FF 3.0.0

Thank you!

**Comment by erikras** [comment]
Hmmm... The way the Final Form `setIn` engine works, whether or not a key is a number is how it knows whether or not the structure is an array or an object. Keep in mind that it might need to set `answers[0].name` in an empty `{}` initial form values, which would result in `{ answers: [ { name: 'value' } ] }`. Keeping track of whether `[]` or `.` syntax was used adds a LOT of complexity.

So I'm afraid the answer is that Final Form doesn't support numeric keys on objects. ☹️ You'll have to transform your structure from `{ '0': '1', '1': '2' }` to something like `{ 'k0': '1', 'k1': '2' }` before initializing and reverse it on submit.

**Comment by erikras** [comment]
[Added a FAQ](https://github.com/final-form/react-final-form/blob/master/docs/faq.md#why-cant-i-have-numeric-keys-in-an-object).

**Comment by em-ka** [comment]
Fair enough, thank you Erik!
