### ISSUE TITLE
Remove versions from generated displayName

### ISSUE THREAD

**Issue by tquetano-r7** [final-form/react-final-form#106]
### Are you submitting a **bug report** or a **feature request**?

Bug report ... although I sincerely hope this is not "a feature, not a bug"

### What is the current behavior?

The `displayName` provided  for the components include the version number for both `final-form` and `react-final-form`, e.g. `ReactFinalForm(3.0.0)(2.1.0)`. This is basically viewable everywhere with DevTools.

### What is the expected behavior?

That the version number is not included. The problem is that this causes snapshots to fail for no reason, and is a nuisance for developers because a simple patch / minor update produces failed tests. What benefit does this provide?

### What's your environment?

React Final Form version => 2.1.1
Final Form version => 3.0.0

**Comment by erikras** [comment]
I admit that this decision was not given too much thought. The main intention was to provide debugging information to support the library when people did not provide the versions in their complaints.

The snapshot testing reason never occurred to me. Thanks! 👍

It seems like passing the versions in as props would:
- not break snapshot testing
- still be visible in React devtools

**Comment by erikras** [comment]
Fixed in [`v3.0.0`](https://github.com/final-form/react-final-form/releases/tag/v3.0.0).
