### ISSUE TITLE
Combine two Fields values

### ISSUE THREAD

**Issue by Cignite** [final-form/react-final-form#107]
Hi,
Thanks for amazing library. I started using in one of my project. Let's say I have Datepicker component name StartDate and timepicker name StartTime. Datepicker initialValue will be e.g: `2018-01-10T12:15:00`
but in UI it will only show` DD.MM.YYYY` and Timepicker will take Datepicker `initialvalue` and show in `HH:mm` format.  

User can change date and time. How can I combine Datepicker and timepicker values into one on inputs onChange?

**Comment by erikras** [comment]
You've got a couple of options:
1. Create a custom date-and-time component that manages its own state and only ever receives a javascript `Date` (containing both date and time) via the `value` prop and gives a combined `Date` object to `onChange`.
2. Maybe something with calculated fields. Check out the [Calculated Fields Example](https://codesandbox.io/s/oq52p6v96y).

**Comment by Cignite** [comment]
Thanks @erikras it was really helpful 👍

**Comment by 311chaos** [comment]
This issue can prob be closed now.
