### ISSUE TITLE
Avoid TS regressions (final-form and react-final-form defs are not in sync)

### ISSUE THREAD

**Issue by brikou** [final-form/react-final-form#108]
### Are you submitting a **bug report** or a **feature request**?

Both :)

### What is the current behavior?

In fact the typescript definition file is not tested and I tkink it leads easily to regressions.

Since last release of both final-form and react-final-form, I get this...

![image](https://user-images.githubusercontent.com/383212/34866873-5c8010d6-f77e-11e7-9c63-45e93802def7.png)

### Other information

On definitively repository, ts definitions files are tested against an example called test.ts, covering every use cases (only syntax), I think it is the way to solve it.

I know that you don't write TS yourself but it could be really nice.

**Comment by erikras** [comment]
I'd be happy to accept a PR adding some sort of TS regression tests into the build validation step.

**Comment by rosskevin** [comment]
I'm taking this @brikou.  I'm going to add tests to `react-final-form` just like you did in final-form.

**Comment by erikras** [comment]
Published fix in [`v3.0.4`](https://github.com/final-form/react-final-form/releases/tag/v3.0.4).
