### ISSUE TITLE
Regression in simple example, checkbox cannot be unchecked anymore

### ISSUE THREAD

**Issue by brikou** [final-form/react-final-form#109]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

Employed checkbox cannot be unchecked anymore

![image](https://user-images.githubusercontent.com/383212/34870142-87f55e1e-f789-11e7-8bac-ce33ebb0f8de.png)

### What is the expected behavior?

to work :)

### Sandbox Link

simple example, https://codesandbox.io/s/ww40y2m595

**Comment by erikras** [comment]
Hahaha!!! Oops... 🤦‍♂️

**Comment by erikras** [comment]
Fixed in [`v3.0.1`](https://github.com/final-form/react-final-form/releases/tag/v3.0.1).

Thanks for the heads-up.

**Comment by brikou** [comment]
Thank you very much, you are very reactive and makes this library a pleasure to use.
