### ISSUE TITLE
How could I create custom submit handler ?

### ISSUE THREAD

**Issue by IvanKuzyshyn** [final-form/react-final-form#114]
I have form and two submit buttons: first for saving draft and second for validation and saving as form result. How could I create custom handler, have you any ideas. 
Thank you a lot.

**Comment by alex-shatalov** [comment]
Have the same form logic. And also have a question. Is it possible to submit not only from "button type submit"?

**Comment by erikras** [comment]
Well, one option is to set a value on your form when you click the button. Like this:

[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/18v6pmql1q)

**Comment by ThiefMaster** [comment]
thx! didn't realize i can set arbitrary values like this. btw, you probably meant "red" in the first button's change() call

**Comment by IvanKuzyshyn** [comment]
@erikras thanks a lot!

**Comment by Itachi-Uchiha78** [comment]
Yes but when the buttons are handled externally?

How can be retrieved "form" object? Which is not the same I get from getElementById("myFormId").

thanks!

**Comment by maciejmyslinski** [comment]
@Itachi-Uchiha78 I'm sorry, 'handled externally'?

**Comment by IrvinDD** [comment]
Hello, 

form.change works well but when i set form.pauseValidation(), the form ignores the validation rules (which is correct) 

but the entire form is disabled and form.change doesn't work
