### ISSUE TITLE
Checked value is not provided when using custom `component` prop

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/react-final-form#117]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
When `radio` input is created with `component` prop, `checked` value is not provided.

[![Edit 🏁 React Final Form radio 🐛](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m41mz8q038)

### What is the expected behavior?
`input` prop should contain `checked` value.

### What's your environment?

package | version
---------|---------
React Final Form | 3.0.2
Final Form | 4.0.0

**Comment by erikras** [comment]
Hmm... This was by design. Providing a `checked` prop is only to map to the HTML spec. Is there some reason why your `Radio` component can't figure out whether or not it's checked?

**Comment by maciejmyslinski** [comment]
It could but I rely on `react-final-form` as my library for handling such things. Is there any reason why `react-final-form` couldn't do it for me if it knows that a certain field is of type `radio` anyways?

**Comment by erikras** [comment]
Nope. I have no good response to that. The `if` I added isn't solving any problems. You convinced me. 👍

**Comment by erikras** [comment]
Fix published in [`v3.0.3`](https://github.com/final-form/react-final-form/releases/tag/v3.0.3).
