### ISSUE TITLE
Parse is not called on number input

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/react-final-form#120]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
[![Edit 🏁 Parse on number input](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kk6y3ol287)

When we use a normal `<input type="text" />`, parse function works as expected. But when we use `<input type="number" />`, though, the parse function is never called 😢 
This bug could occur for other input types too, I didn't test for that, though.

### What is the expected behavior?
Parse function should be called for inputs of type `number`.
### What's your environment?
package | version
---------|---------
React Final Form | 3.0.2
Final Form | 4.0.0

### Other information
I'd ❤️ to contribute but I'm really confused this time and don't know where to start.

**Comment by maciejmyslinski** [comment]
After doing some research I came to a conclusion that using `onInput` instead of `onChange` is not the right solution, since in react specifically `onChange` behaves like `onInput` already ([source](https://github.com/facebook/react/issues/3964))

I guess there is not a good solution for that one except not using an input of type number. Instead, use an input of type text and force numbers only with a parse function.

If you agree I think we can close this issue 🙂

**Comment by erikras** [comment]
That is pretty weird, yes. I agree with your conclusion.
