### ISSUE TITLE
3.0.2 typescript error TS2322 on subscriptions

### ISSUE THREAD

**Issue by rosskevin** [final-form/react-final-form#125]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
I introduced changes in https://github.com/final-form/final-form/pull/61 that produce typescript errors.

### What is the expected behavior?
One example:

```
error TS2322: Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'IntrinsicAttributes & FormSpyProps & { children?: ReactNode; }'.
  Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'FormSpyProps'.
    Types of property 'subscription' are incompatible.
      Type '{ errors: true; values: true; }' is not assignable to type 'FormSubscription'.
        Property 'active' is missing in type '{ errors: true; values: true; }'.
```

### What's your environment?
 final-form        ^4.0.1 
 react-final-form  ^3.0.2 

### Other information
I created the problem, I'll PR the fix ASAP.  Working on it now.  I will probably PR tests here as well (Closes #108)

**Comment by erikras** [comment]
Published fix in [`v3.0.4`](https://github.com/final-form/react-final-form/releases/tag/v3.0.4).
