### ISSUE TITLE
If the async field-level validation takes too long you can submit the form

### ISSUE THREAD

**Issue by bogdansoare** [final-form/react-final-form#131]
In the demo below the async validation takes 10 seconds, time in which the user can submit the form. Is there any way to prevent this from happening ?

![final-form-async](https://user-images.githubusercontent.com/2750170/35297200-f41c29a0-0086-11e8-9171-4f7df6692ca7.gif)

**Comment by VladShcherbin** [comment]
@bogdansoare you can probably set button as disabled while form's [validating](https://github.com/final-form/final-form#validating-boolean) prop is `true`.

**Comment by bogdansoare** [comment]
@VladShcherbin good idea, thank you.
