### ISSUE TITLE
Add touch fields state to Form State

### ISSUE THREAD

**Issue by klis87** [final-form/react-final-form#132]
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?
I need an access to `touched` state of all fields in Form `render` and in `FormSpy`.

I created a following helper:
```js
const isInvalid = (error, touched, submitError, dirtySinceLastSubmit) => (
  !!((touched && error) || (submitError && !dirtySinceLastSubmit))
);
```
So I know when to display a form message. That is working great in `Field` component, but I have a requirement to display a counter of all currently displayed error messages, I can get errors and values of every field in `FormSpy`, but I cannot for `touched`, `submitError` and `dirtySinceLastSubmit`. I care more about `touched` here, as I don't have any server side errors in related form, but `submitError` and `dirtySinceLastSubmit` could be added in a similar fashion.

### What is the expected behavior?
`FormSpy` should provide more field related state, like `touched`, `submitError` and `dirtySinceLastSubmit`.

### What's your environment?
React Final Form: 3.0.2,
Final Form version: 4.0.4,
OS/browser affected: Linux manjaro 4.9.73-1-MANJARO
Node version: 9.3

**Comment by erikras** [comment]
Published fix in [`final-form@4.1.0`](https://github.com/final-form/final-form/releases/tag/v4.1.0).
