### ISSUE TITLE
[bug] FieldArray with string (scalar and not object) removes it from list if value is ""

### ISSUE THREAD

**Issue by brikou** [final-form/react-final-form#133]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

Just try to empty a field...

https://codesandbox.io/s/0y8rrx808l

### What is the expected behavior?

Keep an empty field

### What's your environment?

https://codesandbox.io/s/0y8rrx808l

### Other information

thanks

**Comment by erikras** [comment]
Yikes. That's not good.

**Comment by erikras** [comment]
Published in [`final-form@4.1.0`](https://github.com/final-form/final-form/releases/tag/v4.1.0).

**Comment by brikou** [comment]
thanks a lot @erikras
