### ISSUE TITLE
[BUG] Firefox: checkbox validation not triggered with validateOnBlur 

### ISSUE THREAD

**Issue by jedrzejiwanicki** [final-form/react-final-form#134]
### What is the current behavior?

Passing validateOnBlur prop to Form results in not validating the checkbox input in Firefox browser, as onBlur is not triggered in that browser.

### What is the expected behavior?

Checkbox input should be validated.

### Sandbox Link

Here is the issue presented. I placed two checkboxes, one with bug behavior, second with my workaround. To encounter the issue, please run it in Firefox. 

https://codesandbox.io/s/yyw1r626z

### What's your environment?

React Final Form: 3.0.5
Final Form: 4.0.1
Browser: Firefox 57.0.4

**Comment by maciejmyslinski** [comment]
When the first thing I did was checking the first checkbox, it worked.
However, when the first thing I did anything else (like click a button or check the second one) the bug occurred.

From what I can see it has something to do with `onBlur` event not firing on FF when one would expect.

I or @jedrzejiwanicki could propose a solution if you @erikras agree.

**Comment by maciejmyslinski** [comment]
@erikras ping

**Comment by maciejmyslinski** [comment]
@erikras any update?

**Comment by vefimov** [comment]
Same for me

**Comment by dkulakov** [comment]
Having the same issue

**Comment by tylim88** [comment]
issue still persist

**Comment by hypeofpipe** [comment]
Issue still exists :/

**Comment by hypeofpipe** [comment]
@jedrzejiwanicki did you manage to fix the issue? 🤔

**Comment by jedrzejiwanicki** [comment]
@hypeofpipe Haven't submitted a PR unfortunately, my example has a workaround, have you tried it?

**Comment by hypeofpipe** [comment]
Yes, thank you, didn't notice it 🎉 ❤️
