### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by niros-welldone** [final-form/react-final-form#137]
Hi, i use RN v0.51 and react-final-form v3.1
In iOS everything work perfect but in Android i got that error while trying to render `<Field />`:

TypeError: undefined is not a function (evaluating 'path[typeof Symbol === 'function' ? Symbol.iterator : '@@iterator']()')

**Comment by erikras** [comment]
Maybe try a shim? https://github.com/final-form/final-form/issues/52#issuecomment-354087347

**Comment by niros-welldone** [comment]
Thanks, it's works!
