### ISSUE TITLE
[BUG] Cannot change form state using onSubmit when initialValues prop exists

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#138]
Sorry if this has asked before, I could not find an example doing the same.

So I would want to populate data from Data into ```final-form``` state and I can do this with ```initialValues``` field.  I basically read from DB, then reformat data into the format which my form would like and then provide to ```initialValues```

Also onSubmit I want to re-populate the final-form state with whatever DB replies so final-form state is in sync with DB.  And  also submit button should be disabled as no changes.

I current see 3 issues

- If there are validation errors on ```initialValues```, final-form basically gets undefined as ```initialValues``` , so form is empty.
- When I do submit, ```final-form``` still things data is not in sync and allows me to click submit .
- is there a recommended way where I can provide input and output functions to final form ,so I directly provide my DB value to ```final-form``` as input and onSubmit the output is from my function is to DB, so ```final-form``` state and DB state always is in sync. 

@erikras Thanks for great work !!

**Comment by p-grzelczak** [comment]
What I currently do is this pretty much this (that's example with redux and saga, but you can go with regular promise based request the same way):

```
// Function triggered when form calls onSubmit()
handleSubmit = (values, formApi) => {

  const request = () => new Promise((resolve, reject) => {
    onUpdateData(values, resolve, reject); 
  });

  try {
    await request(returnedValues);
    formApi.initialize(returnedValues);
  } catch (e) {
    console.log(derp);
  }
}
```

I'm pretty sure this solves points 1 and 2, don't know about no. 3 since I don't quite understand what's the issue there :)

**Comment by kavink** [comment]
@p-grzelczak Thanks!!! The point 3 was basically asking if there was any best way to keep database and final-form state in sync always.. But your answer works for me .. for now...

**Comment by kavink** [comment]
@p-grzelczak Does not seem to work 😢

**Comment by kavink** [comment]
@erikras @p-grzelczak Yes just confirmed, it seems like a bug, i.e. when you initialize, it just changes the state for ```pristine``` to ```true``` and changes ```state``` to the value passed it, but does not change the ```initialValues``` prop to the value passed to ```formApi.initialize```,  And looks like final-form gives priority to props instead of state. i.e. if prop is set to X, you change state to Y, and if you initialize form by Y, X will still win.

**Comment by kavink** [comment]
Closing it because of great example by @erikras posted in README,  https://codesandbox.io/s/xr0mvl1904  , means the right way to do above is just get ```initialValues``` from state and use that to populate the form, so whenever state changes form's ```initialValues``` changes.

**Comment by erikras** [comment]
@kavink This issue prompted me to write that example. I had just forgotten to come close it. Thanks!
