### ISSUE TITLE
Autosave form, set submitErrors.

### ISSUE THREAD

**Issue by scsirdx** [final-form/react-final-form#139]
### Are you submitting a **bug report** or a **feature request**?

feature request

### What is the current behavior?

In this example https://codesandbox.io/s/7k742qpo36 it's possible to autoSubmit a form using submit function that i passed to FromSpy, but there is no way to set field(s) submitErrors (that came from server).

### What is the expected behavior?

It would be nice to have from api function that will accept something like:
```javascript
{ fieldName: ['Error message'] }
```
and set form/field errors.

### What's your environment?

final-form 4.2.0
react-final-form 3.1.0

### Other information

Right now custom `data` attributes can be used with mutator, but it can be complicated when form is used in "mixed" mode, when user can submit the whole form or edit/change one field and submit on click/blur.

**Comment by romanlex** [comment]
Can confirm this behavior
Can't set errors from AutoSave submit function((

**Comment by scsirdx** [comment]
Sorry, i totally forgot that i opened this issue 🤦‍♂️ 
@romanlex There is actually a way to get error from submit, here is a codesandbox: https://codesandbox.io/s/34vw8zn7om

Important lines in Autosave.js:
```
const error = await this.promise;
if (error) setFieldData(blurredField, { error });
```
and in index.js:
```
{meta.data.error && meta.touched && (<span>{meta.data.error}</span>)}
```

So, you can return something from submit (string in this case) and save it in `data`.

And if you have additional sync validation, you can use
```
{(meta.error || meta.data.error) && meta.touched && (<span>{(meta.error || meta.data.error)}</span>)}
```

**Comment by romanlex** [comment]
@scsirdx but if you use autosave with hybrid record validation when you need send to AutoSave component `handleSubmit` function, not `onSubmit` :(
I'm create this issues for this case https://github.com/final-form/react-final-form/issues/373

**Comment by scsirdx** [comment]
@romanlex Maybe i didn't understood what you want to achieve. But here https://codesandbox.io/s/34vw8zn7om (updated) you can see an example of hybrid validation. If there is less than 5 chars then only client side validation will occur, otherwise backend/async.

**Comment by romanlex** [comment]
@scsirdx in your case you don't use validate prop of Form, you use validate prop of Field(
I can use only validate props of Form, not Field level validation

**Comment by scsirdx** [comment]
@romanlex Form validation works the same way: https://codesandbox.io/s/34vw8zn7om

**Comment by romanlex** [comment]
@scsirdx ok, thx
but now Form state in this case has `valid` key is true :( 
when you call setFieldData you change state for Field, not Form

**Comment by scsirdx** [comment]
@romanlex Yes, it's a hacky solution :) You can set state in a form component with `{ fieldname: bool, ... }` , reduce it to `formValid` and rely on it and form valid/invalid subscription.

**Comment by romanlex** [comment]
@scsirdx  can you show solution for this?)
