### ISSUE TITLE
[Feature] Formik like Typescript interfaces

### ISSUE THREAD

**Issue by thupi** [final-form/react-final-form#140]
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?
Most of the typings are very loose and not very strickt about which fields is present in the form. The initialValues props expects type of object. Values in in the validate prop is type of object.

### What is the expected behavior?
If typings like the ones in formik was present react-final-form would be a bit more type safe and appeal a bit more to applications written in typescript. Take a look at [https://github.com/jaredpalmer/formik#using-formik-with-typescript](https://github.com/jaredpalmer/formik#using-formik-with-typescript).

### Other information
Otherwise react-final-form checks a awful lot of boxes when it comes to handling forms. Very impressive :-) !

**Comment by erikras** [comment]
Have you seen [`react-define-form`](https://github.com/ForbesLindesay/define-form/tree/master/packages/react-define-form)? That might be just what you're looking for.

**Comment by thupi** [comment]
@erikras That's great :D ! Exactly what i needed :-) !

I will give this a try :-)

The package do not seam to have gained a lot of traction yet but might be useful to add to the docs of react-final-form :-) This would make react-final-form way more useful to Typescript users :-) !
