### ISSUE TITLE
Flow type definitions aren't working

### ISSUE THREAD

**Issue by saadq** [final-form/react-final-form#142]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Flow type definitions aren't working

### What is the expected behavior?
Flow type definitions should work

### What's your environment?

**Node**: v9.5.0
**Flow**: v0.64.0
**React**: v16.2.0
**Final-Form**: v4.2.0
**React-Final-Form**: v3.1.0

### Steps to reproduce
1. `npm install flow-bin final-form react-final-form`
2. Write this code:

```js
/**
 * @flow
 */

import { version } from 'react-final-form'

const v: number = version // This should throw error, but doesn't

console.log(v)
```

3. Run `flow` in terminal or editor

As you can see, it doesn't cause any issues:

![screen shot 2018-02-06 at 5 01 10 pm](https://user-images.githubusercontent.com/5678694/35889844-2a041e8a-0b6b-11e8-9457-36a3cb3623af.png)

### Possible solution

I think this may have to do with the fact that in the `dist`, the `main` file is `react-final-form.cjs.js`. I think this may mean that the `.flow` file that gets generated may need to be called `react-final-form.cjs.js.flow`. When I renamed `index.js.flow` to `react-final-form.cjs.js`, flow seems to work:

![screen shot 2018-02-06 at 5 01 00 pm](https://user-images.githubusercontent.com/5678694/35889884-50220da2-0b6b-11e8-876a-1a93c90284e9.png)

---

**NOTE**: The types still seem to be problematic however. When I use the [simple example](https://codesandbox.io/s/ww40y2m595) (only thing I changed was `<Styles>` to `<div>`), there seem to be all sorts of Flow errors. I'm not sure if this has to do with the type definitions being incorrect or not.

Example Code: [Gist](https://gist.github.com/anonymous/f434a5ba2b9b73200dd3f4cfd9a145b5)
Terminal Output: [Gist](https://gist.github.com/anonymous/7e3e523fa6166525f56b4364ac1cd854)

**Comment by zalishchuk** [comment]
@erikras I also can't get flow typings to work.

```js
import type { FieldRenderProps /* any */ } from 'react-final-form';
```

Only thing worked for me is to specify typings path:
```js
import type { FieldRenderProps /* FieldRenderProps */ } from 'react-final-form/dist/types.js.flow';
```

**Comment by erikras** [comment]
I've been investigating this. @saadq's analysis was exactly correct.

The other stuff seems to be caused by the latest version of Flow. Still investigating...

**Comment by erikras** [comment]
Should be fixed in [`final-form@4.3.0`](https://github.com/final-form/final-form/releases/tag/v4.3.0) and [`react-final-form@3.1.3`](https://github.com/final-form/react-final-form/releases/tag/v3.1.3).

**Comment by consegrado** [comment]
@erikras there is no export of type `FieldRenderProps`

**Comment by StevenLangbroek** [comment]
Having the same issue as @consegrado. Any idea @erikras? If i look at the definitions I definitely see it there, but flow (I tried 0.63 and 0.68) both seem to think it's not there.

**Comment by erikras** [comment]
@StevenLangbroek Check out [`v3.1.5`](https://github.com/final-form/react-final-form/releases/tag/v3.1.5). It publishes all those other types.

**Comment by StevenLangbroek** [comment]
Like a charm :) amazing work as per usual!
