### ISSUE TITLE
Plans for an accompanying library to extend state-management with Redux?

### ISSUE THREAD

**Issue by leggomuhgreggo** [final-form/react-final-form#155]
**Feature Inquiry**
I know one of the goals with this library is to avoid a heavy package size, in favor of modularity, a choice about which I salute you. With respect to that modular ethos, I was wondering if there was any intentions of make an accompanying library to aid in a boilerplated Redux integration, along the same lines of the redux-form predecessor.

It's true forms are often cited as being a part of the UX for which Redux has diminishing returns ("every keystroke?!" etc) and I respect that point of view; but, as someone who errs towards redux state purity, I was curious if there was any *action* in that direction.

Many thanks for your continued OSS contributions! Especially appreciating this library 🥇

**Comment by erikras** [comment]
Seems like it would be pretty easy to write a reducer and use [`FormSpy`](https://github.com/final-form/react-final-form#formspy--reactcomponenttypeformspyprops) to `dispatch` the form state to be saved in Redux on every change. I guess the primary benefit would be to have access to it from outside the form.

But to answer your plans, no, there are no plans to do so.

**Comment by leggomuhgreggo** [comment]
Cool, thanks for the response

**Comment by erikras** [comment]
Here's a sandbox:

[![Edit 🏁 React Final Form - Redux Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4xq2qpzw79)

**Comment by leggomuhgreggo** [comment]
Holy cow! Man @erikras you knock my dang socks off. 

This is awesome. Thanks!

**Comment by erikras** [comment]
To minimize the barrage of dispatched actions, I'd recommend using the `subscription` prop on `FormSpy` to only put the part of form state that you care about into Redux, not _all_ of it as in the example.

**Comment by leggomuhgreggo** [comment]
Makes sense -- looking forward to playing with it! Thanks again, man!

**Comment by oliviertassinari** [comment]
> Seems like it would be pretty easy to write a reducer and use FormSpy to dispatch the form state to be saved in Redux on every change. I guess the primary benefit would be to have access to it from outside the form.

@erikras This sounds great. I will do that for debug purposes in development (redux devtools)!
🤔 It could also be useful in production to send the form state when an error occurs to services like Sentry.io.
