### ISSUE TITLE
Uncaught TypeError: Cannot read property 'subscription' of undefined when using FormSpy

### ISSUE THREAD

**Issue by johanneslumpe** [final-form/react-final-form#159]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

When rendering a `Form` with a `FormSpy`, it becomes impossible to remove the spy from the react hierarchy based on form state, without triggering errors during subscription handling.

In the sandbox example, submitting the form will trigger the form to re-render and only return a string, unmounting the `FormSpy`. This will then lead to an error being thrown.

A workaround is to keep rendering the `FormSpy` regardless of whether the form has been successfully submitted.

### What is the expected behavior?

It should be possible to remove the `FormSpy` from the tree without having it conflict with subscription handling.

### Sandbox Link

https://codesandbox.io/s/0o6o6mp3ov

### What's your environment?

final-form 4.2.0
react-final-form 3.1.0

**Comment by vasilich6107** [comment]
Is there any news regarding this bug?

**Comment by maciejmyslinski** [comment]
I'm trying to reproduce it.

**Comment by maciejmyslinski** [comment]
reproduced, let me debug it.

**Comment by erikras** [comment]
Updating the FF and RFF deps in that code sandbox fixes the problem. 🤷‍♂️

**Comment by onlyann** [comment]
For what it's worth, it is also happening with final-form 4.11.1 and react-final-form 4.0.2 when conditionally removing a `FormSpy` from the tree.
Is there a known workaround beside keep the `FormSpy` always rendered?
I will take a deeper look when I get the time.

**Comment by erikras** [comment]
Published fix in [`final-form@4.13.0`](https://github.com/final-form/final-form/releases/tag/v4.13.0).
