### ISSUE TITLE
validateFields={[]} runs validation when other fields change

### ISSUE THREAD

**Issue by juanpasolano** [final-form/react-final-form#170]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
A `Field` with `validateFields={[]}` is validating the field even when others are changed.

### What is the expected behavior?
According to [docs](https://github.com/final-form/final-form#validatefields-string) a Field with `validateFields={[]}` should only run the validation when it changes and not the rest of the fields

### Sandbox Link
https://codesandbox.io/s/wyq72qxly5
You can see the console that console.count("usernameValidaiton") is called when typing on age or last name

### What's your environment?
 "react-final-form": "3.1.0",
 node v9.3.0

**Comment by erikras** [comment]
Hmm... this is an easy point of confusion (I was just confused looking back at it). The `validateFields` prop controls what validation will run when _that field_ (`username` in your example) changes, it does not control behavior of when _other_ fields change. That's what the memoization is for in the example.

There is currently no way to mark a field-level validation function as "only run when this field changes". By default, they all have to run in case they depend on other field values.

**Comment by juanpasolano** [comment]
Thanks.
I noticed the memoized function but was expecting a different behavior.
I'll close this since the solution is outside of final-form and is not really a bug.
