### ISSUE TITLE
Warning: setState(...): Cannot update during an existing state transition

### ISSUE THREAD

**Issue by kaskazurek** [final-form/react-final-form#174]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

When I try to render `Field` component, the following warning is shown in the console:
```
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
```
It is caused by setState in the constructor.

```
constructor(props: Props) {
  ...
  this.notify(state)
  ...
}
```
```
notify = (state: FormState) => this.setState({ state })
```
 (the same code in `ReactFinalForm.js`, `FormSpy.js`, `Field.js`)

### What is the expected behavior?

No warnings.

### What's your environment?

react-final-form: 3.1.0
final-form: 4.2.0
react: 15.6.1
react-dom: 15.6.1

**Comment by erikras** [comment]
This is not happening in the examples. You might need to share some code and/or try to demonstrate it in a sandbox.

**Comment by kaskazurek** [comment]
Example: [https://codesandbox.io/s/1oxn80yr8l](https://codesandbox.io/s/1oxn80yr8l)

**Comment by powah** [comment]
Yes, this is happening with the versions given (not latest ones). Could this be react related?

**Comment by kaskazurek** [comment]
To be honest, I do not know why this only happens with React v15. However, the documentation says:  

>  Avoid introducing any side-effects or subscriptions in the constructor. For those use cases, use componentDidMount() instead.

> The constructor is the right place to initialize state. To do so, just assign an object to this.state; don’t try to call setState() from the constructor.

And what I see in the code is:
```
constructor(props: Props, context: ReactContext) {
    …
    this.subscribe(props, (state: FieldState) => {
      ...
        this.notify(state)
      …
     }
...
}
```
```
 notify = (state: FieldState) => this.setState({ state })
```

**Comment by sww314** [comment]
I see the same issue in React 15.6.

**Comment by erikras** [comment]
I'm pretty sure this was fixed in [`v3.1.4`](https://github.com/final-form/react-final-form/releases/tag/v3.1.4). Can someone confirm?

**Comment by sww314** [comment]
Yes! That fixed it for me. Thank you, sir!

**Comment by erikras** [comment]
Great! Closing.
