### ISSUE TITLE
Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.

### ISSUE THREAD

**Issue by consegrado** [final-form/react-final-form#176]
### Are you submitting a **bug report** or a **feature request**?

Bug report. 
I have a problem on the SSR

```
Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.
Please check the code for the ReactFinalForm(4.2.0)(undefined) component.
```

### What's your environment?

FinalForm v4.2.1
ReactFinalForm v3.1.2
React v16.2.0
node v8.9.4

**Comment by thomhos** [comment]
Same here. It works, but just throws a warning :(

**Comment by edqd** [comment]
Same here

**Comment by erikras** [comment]
I am unable to reproduce this with those exact versions of the library using Next, my SSR framework of choice.

Is your SSR setup rendering the page more than once on the same request, possibly a second time with async loaded data? I know that I used to have an SSR setup where I rendered my page, and that act of rendering informed my data module what data needed to be loaded, and then after it was loaded, it rendered the document again with the data.

**Comment by thomhos** [comment]
In my case I'm not using nextjs. My flow looks like this;

1. Apollo's `getDataFromTree`
2.`renderToString`
3. Pass the resulting string into glamor's `renderStatic` 
4. Pass the data, markup to an HTML component and render that to string

If I remove apollo (step 1), the renderStatic (step 3) and second render to string (step 4) the warning still persists.

I'm not sure where to start digging for this, any pointers where this might be occurring?

**Comment by erikras** [comment]
The original post implied that it was the fault of the `Form` component. @thomhos, does your warning also say `Please check the code for the ReactFinalForm...`?

**Comment by erikras** [comment]
Weird... Do you see the warning in the browser console as well as the server log?

My best way to generate that warning is to call `this.setState()` in a component's constructor, which appears on both.

**Comment by thomhos** [comment]
it only logs server-side, I have no logs whatsoever in the browser console.

I've checked the props for the Field component, but even with just `<Field name="foo" />` it generates that warning.

Funny thing is though, it only triggers that warning once (on the first request to the server). Subsequent refreshes in the browser do not trigger the warning.

**Comment by erikras** [comment]
> Funny thing is though, it only triggers that warning once (on the first request to the server). Subsequent refreshes in the browser do not trigger the warning.

That is _really_ bizarre. 🤯

**Comment by thomhos** [comment]
Yeah I'm going over the source of the field component and form component to check where state changes occur, and if there's anything kept in memory which could be held there between renders. But so far haven't found anything.

**Comment by erikras** [comment]
They both use a mechanism that initiates the first registration (with the final-form instance), the callback for which is synchronous, in the constructor that uses `this.state =` on the first call, and then `this.setState()` on subsequent calls.

**Comment by thomhos** [comment]
What does the subscribe part do at Field.js:46? this.notify can trigger a state change, but as far as I can see you wouldn't be able to get there? Considering initialState is only just initialized before calling this.subscribe

**Comment by erikras** [comment]
Thanks for your sleuthing here. You've given me an idea of what might be the problem.

**Comment by erikras** [comment]
🎉 I've got a breaking test! 🎉

**Comment by thomhos** [comment]
whoop! let me know if i can help in solving this issue :)

**Comment by thomhos** [comment]
excellent! Looking forward to testing it on my side. Thanks for the quick work on it 🙇

**Comment by erikras** [comment]
Published fix in [`v3.1.4`](https://github.com/final-form/react-final-form/releases/tag/v3.1.4).

**Comment by thomhos** [comment]
Can confirm, works great now.

**Comment by lourain** [comment]
I think you need a state container to manage the data.like redux,mobx.
