### ISSUE TITLE
Lack of "invalid" FormRenderProp in documentation

### ISSUE THREAD

**Issue by Lukasz-Semik** [final-form/react-final-form#178]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Lack of "invalid" FormRenderProp in documentation (README.md)

### What is the expected behavior?

"invalid" prop should be exposed with other props in documentation

**Comment by erikras** [comment]
https://github.com/final-form/react-final-form/pull/180#issuecomment-369985249
