### ISSUE TITLE
Reset (or change the value of) a field at field-level

### ISSUE THREAD

**Issue by Zephir77167** [final-form/react-final-form#179]
### Are you submitting a **bug report** or a **feature request**?

feature request (it exists at the form-level, but is not practical for some use cases)

### What is the current behavior?

Currently, I don't think there is any solution to reset a field (e.g. an input with a clear button). I tried:

```
clearField = (e) => {
  e.preventDefault();
  this.inputRef.value = '';
};
```

but the previous value came back on blur.

### What is the expected behavior?

Maybe a `reset` or `change` (a la redux-form) prop passed to Field?

### Sandbox Link

https://codesandbox.io/s/6vm34649nn

### What's your environment?

RFF version: 3.1.2
FF version: 4.2.1
OS: MacOS High Sierra v10.13.3
Node version: 8.9.3

### Other information

Thanks for the work put into RFF!

**Comment by Zephir77167** [comment]
Also, it seems like the `<Field />` component has access to some useful things in `context`: [![Screenshot from Gyazo](https://gyazo.com/f70d11988e2e9080a515b156fe795e49/raw)](https://gyazo.com/f70d11988e2e9080a515b156fe795e49). Maybe they could be passed to child component?

**Comment by leuction** [comment]
@Zephir77167 Hi, I have the same issue here. Have you found a way to get access to the context in the child component? Thanks.

**Comment by Zephir77167** [comment]
Hey, I haven't had much time to look it up yet. I will get back to you as soon as I will have!

**Comment by Zephir77167** [comment]
Hello, I just opened https://github.com/final-form/react-final-form/pull/209

**Comment by erikras** [comment]
Closing for reasons explained here. https://github.com/final-form/react-final-form/pull/209#issuecomment-377490998
