### ISSUE TITLE
Typescript FieldRenderProps has no property "checked" 

### ISSUE THREAD

**Issue by DenisNeustroev** [final-form/react-final-form#182]
### What is the current behavior?

ts fails with `{ input: { name, checked, value, onChange } }`

https://github.com/final-form/react-final-form/blob/master/src/index.d.ts#L16

### What is the expected behavior?

correct typescript typings

### Versions

react-final-form: 3.1.2
final-form: 4.2.1

**Comment by cthompson527** [comment]
This issue can be closed due to #207.
