### ISSUE TITLE
codeSandbox: Title for Example Input Form is incorrect (copy-paste "typo")

### ISSUE THREAD

**Issue by SherylHohman** [final-form/react-final-form#184]
👋 Thank You for writing 🏁 React Final Form! and including great documentation 👋 

### Are you submitting a **bug report** or a **feature request**?
**bug report**
(minor typo - result of copy-paste)

### What is the current behavior?
Click Link "" in ReadMe -> Examples -> "Synchronous Field-Level Validation"
https://codesandbox.io/s/2k054qp40
Example input form is Titled "Synchronous Record-Level Validation"

(Record-Level Validation example is a different codeSandbox/link)

### What is the expected behavior?
Example input form should be Titled: "Synchronous Field-Level Validation"

(change:  
    `<h2>Synchronous Record-Level Validation</h2>`
to:  
   ` <h2>Synchronous Field-Level Validation</h2>`
)

### Sandbox Link
N/A

### What's your environment?
N/A (web link)

### Other information
N/A

**Comment by erikras** [comment]
Thanks! Fixed.
