### ISSUE TITLE
Allow formatOnBlur

### ISSUE THREAD

**Issue by MichaelBuen** [final-form/react-final-form#187]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

Formatting is immediate when user is doing an input. When the user is trying to edit a number with formatting, e.g., 1.5 percent is presented/formatted as 1.5 to user (value is stored as 0.015), the problem is when the user tries to backspace the number 1 (when the cursor is at the position before the dot in 1.5) and replace it with 3, the input becomes .5  (parsed and stored as 0.005), but then the formatting kicks in immediately, the .5 user input is replaced with 0.5, and the cursor goes to the end of the number. Then the user has to press left key two times, and then press 3. This gives a bad user experience since the user can't edit the text in the most natural way possible.

Another problem is when the user wanted to type `2.5`,  as soon as `2.` is typed, the value is formatted as `2`, this won't give user a chance to type `2.5` in the most natural way. The only way for `2.5` can be typed is by typing `25` first and then pressing the left key and then typing the `.` character.

### What is the expected behavior?

Give an option that formatting happens only when the input loses focus.

Demo for the expected behavior. Backspace the number `1` in the `Interest Rate per Annum` of `1.5`, and then press `3`. http://jsfiddle.net/0zw630d4/4/

### Sandbox Link

Demo: https://codesandbox.io/s/nk1828jz70

### What's your environment?

Sandbox

**Comment by MichaelBuen** [comment]
A not so neat work-around, store both the view value and model value: https://codesandbox.io/s/x4wl4r1kz

It would be best to just store a single value (model). Perhaps format could be made to be called only when the `change` action is not caused by user input; if the `change` action is caused by user input, don't call `format`.

**Comment by erikras** [comment]
Sounds like you want a `formatOnBlur`?

**Comment by Togrias** [comment]
Wouldn't a HOC pattern be better for this use case? Store the rawValue on the HOC's state and depending on whether your form wants formattedValue or rawValue, pass the applicable value to input.onChange. Then supply the formattedValue to the wrapped component.

**Comment by MichaelBuen** [comment]
Is that HOC pattern the React middleware? I've yet to learn how to create my own middleware in React.

Here's the desired output: https://codesandbox.io/s/yp1j7pynqz

If that can be tackled neatly in middleware, I'll explore it.

**Comment by jbinto** [comment]
I think `formatOnBlur` would help a ton. The codesandboxes @MichaelBuen posted illustrate the problem and desired solution perfectly: I want to make display-facing changes to my inputs, but only on blur. I don't want my input changing while I'm editing it.

**Comment by erikras** [comment]
Published `formatOnBlur` prop in [`v3.6.0`](https://github.com/final-form/react-final-form/releases/tag/v3.6.0).
[![Edit 🏁 React Final Form - Format On Blur Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3rp260ly51)
