### ISSUE TITLE
Provide example on using batch() and/or change()

### ISSUE THREAD

**Issue by powah** [final-form/react-final-form#189]
### Are you submitting a **bug report** or a **feature request**?

feature request

### Other information

It would be great to have a working example or more thorough documentation on how to use these methods. i.e. currently I'm trying to achieve the following: if checkbox A is clicked checkbox B should be unchecked and disabled. How to achieve such functionality without triggering `Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). ...`? Tried to use `<FormSpy>` for this but got aforementioned warning. Even if it would work that feels a bit as an anti-pattern. What would be your recommended way of doing such things as interrelated inputs?

**Comment by erikras** [comment]
This is a great example idea. My interest is piqued. 😄

**Comment by powah** [comment]
Thanks, can't wait to see what you will come up with! Keep us updated :)

**Comment by erikras** [comment]
Here's my answer, in the form of a Medium article. 😄

## [Declarative Form Rules](https://medium.com/@erikras/declarative-form-rules-c5949ea97366)

**Comment by powah** [comment]
Thank you! That's just awesome :)

**Comment by erikras** [comment]
@powah Love your avatar. 😄
