### ISSUE TITLE
Update validation message after initial render

### ISSUE THREAD

**Issue by tquetano-r7** [final-form/react-final-form#19]
### Are you submitting a **bug report** or a **feature request**?

I interpret it as a bug, because it is not the expected behavior, so bug report!

### What is the current behavior?

The validation message that is used on the `validate` method is instantiated once and that is the static message used for the rest of the renders. With static text this is fine, but when using internationalization libraries like i18next that can have bundles dynamically loaded, this can cause issues because the non-internationalized string key is shown instead of the internationalized value.

```javascript
const isFoo = (value) => {
  return value === 'foo';
};

const getErrorMessage = (t, i18nKey) => {
  return (isValid) => {
    return isValid ? undefined : t(i18nKey);
  };
};

// in component
validate={compose(getErrorMessage(t, 'some.key'), isFoo)}
```

The `i18next` thing is just one example, but any sort of dynamically-built message will not be dynamically built!

### What is the expected behavior?

That when items are invalid the current message is used.

### What's your environment?

Final Form version => 1.0.0
OS => Manjaro Linux
Node version => 8.9.1

**Comment by erikras** [comment]
I'm not following... Can you make a sandbox?

**Comment by tquetano-r7** [comment]
Hmm attempting to reproduce this without i18next is actually proving difficult, because it appears to work as expected (messages are dynamically added) ... this may be something specific to i18next. I'll close for now and if I can come up with a simple example to reproduce I'll come back.
