### ISSUE TITLE
DropDownList not working properly in Mozilla firefox 59.0.1

### ISSUE THREAD

**Issue by elangodhilipan** [final-form/react-final-form#194]
In my web site i'm having the dropdownList fileds. It showing the dropDown Button alone. not showing the input box. it's working fine in chrome. can you help to fix this issue

![image](https://user-images.githubusercontent.com/12911533/37656468-202c7668-2c6e-11e8-9722-8b7fc7cb33d7.png)

**Comment by erikras** [comment]
You'd need to share your React form code.

**Comment by elangodhilipan** [comment]
@erikras myself used the following code

<DropdownField
	data={subSkillsList || []}
	valueField="id"
	textField="name"
	label="SPECIALIZED SKILL"
	name="specializedSkill"
	className="due_duration pull-right"
	placeholder="Specialized Skill"
	isRequired
/>

**Comment by elangodhilipan** [comment]
<code>

> <DropdownField

	data={subSkillsList || []}
	valueField="id"
	textField="name"
	label="SPECIALIZED SKILL"
	name="specializedSkill"
	className="due_duration pull-right"
	placeholder="Specialized Skill"
	isRequired

> />"

</code>

**Comment by hassanzadeh** [comment]
Hey, is it really not compatible with firefox? I was thinking to use this.

**Comment by elangodhilipan** [comment]
Yes. it's showing the button alone. the input box getting hiden.

**Comment by erikras** [comment]
It sounds like your problem is not at all related to this library. Ask on StackOverflow.
