### ISSUE TITLE
How to connect to redux

### ISSUE THREAD

**Issue by hassanzadeh** [final-form/react-final-form#195]
Hello moderators,
I have a question regarding your final-form lib.
In the docs you mention: "If you need to mutate your data via dispatching Redux actions, you should probably use Redux Form."

Does that mean I cannot use the data that I get from redux states in the forms? If yes, is it not an big limitation?
For example, my forms will get data from graphql (apollo) and based on the data I want to update my forms, how can I do that if I can't use redux?

THanks

**Comment by erikras** [comment]
The form data is set/initialized by passing in the `initialValues` prop. There's no reason why you could not `connect()` to get some Redux data and pass it into your React Final Form component as `initialValues`. Does that make sense?

**Comment by mnbbrown** [comment]
@erikras that works for values but what about things like errors? From the docs there doesn't seem to be a way to set errors outside of `onSubmit` or `validate`. 

or am I mistaken?

**Comment by mnbbrown** [comment]
Great library btw - I much prefer the API and philosophy over redux-form.

**Comment by erikras** [comment]
You want to set submit errors?

**Comment by rogerwalt** [comment]
Very similar issue: Assume we need to change values of some fields (fetch some additional data that could also be provided manually) using a rest service (e.g. using redux-saga). The values are updated in Redux; but that will not change the field values in the final-form fields. Is this correct?

**Comment by erikras** [comment]
> The values are updated in Redux; but that will not change the field values in the final-form fields. Is this correct?

To update the values in the final-form fields, you will need to update the value of the `initialValues` prop to the form. That could be done via Redux's `connect()`, it seems.

**Comment by jfreixa** [comment]
I have a similar problem with the redux and redux-saga. When I am submitting the form I dispatch an action and then I receive the errors via props (connect). It will be great if the Form has a prop of the submit errors. I don't want to make workaround passing callback into redux to make possible to put the errors inside the form.

**Comment by rogerwalt** [comment]
@jfreixa :+1: either something like you described; or there should be another clean (= no hack involved) solution to have a similar effect.

Side note: I looked into [redux-form](https://redux-form.com/), but it does not integrate very easily with [material-ui-next](https://material-ui-next.com/) (yet). There is a library to address this problem ([redux-form-material-ui](https://github.com/erikras/redux-form-material-ui/tree/5.0)), but it lags behind (material-ui version `v1.0.0-beta.16`, while current is `v1.0.0-beta.38`, and also it include no types). So it is no option for me to use `redux-form` at the moment.

**Comment by erikras** [comment]
I'm working on a way to get errors into RFF via a dispatched Redux action. Might not appear until next week sometime, though, due to the 🐰 holiday.

**Comment by ms88privat** [comment]
@erikras 
> To update the values in the final-form fields, you will need to update the value of the initialValues prop to the form. That could be done via Redux's connect(), it seems.

I didn't test it yet, but what happens to other, unrelated dirty fields then? Will they be overwritten with the "new" initialValues?

**Comment by erikras** [comment]
Here you go: [React Redux Promise Listener](https://medium.com/@erikras/getting-a-promise-from-redux-actions-d92787894368) converts actions into a `Promise` for libraries like this one.

**Comment by Jesus-Gonzalez** [comment]
Using `initialValues` is not really a solution.

The form will be reinitialized, fields will be not touched anymore and the form state will be pristine.

I've tried using `keepDirtyOnReinitialize` but it only works in the case of calling `FormApi.initialize` manually.

Do you know of any solutions for this?

Couldn't a form mutator, merge a certain redux form state with the final-form state? I'm about to go this way, or even coding a solution to keep dirty state when initial values are changed.

Let me know what you think.

Jesús

**Comment by erikras** [comment]
@Jesus-Gonzalez It certainly seems like you could wire up some sort of mutator/`connect()` solution, yes. But if you really need such tight coupling with Redux, I'd recommend looking at Redux-Form.

**Comment by Jesus-Gonzalez** [comment]
@aldis it should be a separate issue.

I'd use the FormSpy component to copy the values into the redux state as well, so I can restore it as initial values.

**Comment by aldis-ameriks** [comment]
I realized there's a shallow compare with the initialValues, so in my case, the initialValues always remains the same. But because It's a composite input field, the value is actually an object containing two nested values. `initialValues = {startEndDate: {startDate: xxx, endDate: xxx}}`.

 I'm creating a new reference during each re-render by rebuilding the `initialValues`. By ensuring that the reference remains the same between re-renders, i can avoid the form reinitialization whenever the props change.
