### ISSUE TITLE
Strange field level validation when form level validate function is missing

### ISSUE THREAD

**Issue by em-ka** [final-form/react-final-form#196]
Hi @erikras !

### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

Referring to the [old example](https://github.com/final-form/react-final-form/issues/64#issuecomment-352199012) of the conditional fields, I'm experiencing some strange behaviour when updating to the last version of the RFF. I've prepared two examples:

1. [With old packages](https://codesandbox.io/s/p9y8ln79rm)
2. [With updated packages](https://codesandbox.io/s/lyn8394kjz)

The first change comparing both of them is, that with updated packages the form is not in invalid state on the initial load (invalid flag is false) upon first interaction with the form.
The main issue is with unchecking the Employed? checkbox. The 
errors object is containing the job.description error even if the job value is deleted. I had a luck to resolve it with the form level validate function returning the empty object, but I think this one is not desired:

3.  [With updated packages and form level validate function](https://codesandbox.io/s/qzw4w960v4)

### What's your environment?

FF 4.3.1, RFF 3.14

Thank you.

**Comment by erikras** [comment]
Since the form has to render once to create the field components (which register themselves and their validation functions with the form), the _very first_ form render _cannot_ know that `invalid===true`, but there was a bug that was missing the update. So as soon as the fields register themselves, the form will rerender with `invalid===true`.

**Comment by em-ka** [comment]
@erikras Thank you, Erik. As I understand, this one will resolve the invalid flag issue but not the one with the errors object not being updated on the field deletion, is it?

**Comment by erikras** [comment]
Published fix in [`v3.1.5`](https://github.com/final-form/react-final-form/releases/tag/v3.1.5).

> As I understand, this one will resolve the invalid flag issue but not the one with the errors object not being updated on the field deletion, is it?

You might need a decorator for that. What I do in that situation is run the `delete` at submit time and just not worry about the extra structure while the form is being edited.
