### ISSUE TITLE
I wonder focus of FormRenderProps does not work?

### ISSUE THREAD

**Issue by longhuynh95** [final-form/react-final-form#199]
https://github.com/final-form/react-final-form#focus-name-string--void

**Comment by erikras** [comment]
It does not imperatively focus the field. [For that you need the DOM reference](https://medium.com/@erikras/focus-on-errors-e569264d33a). That `focus()` function _marks the field as active_ in the form state.

**Comment by longhuynh95** [comment]
Why it's not `active`? Focus should be means focus. Focus with a name of field is very useful for users. The ref configuration is very complex. For example I have more than 10 fields. Just focus name is enough. You should support this.

**Comment by erikras** [comment]
It can't be supported. There is no way to focus on a field without the ref of the DOM element.

It's called `focus`, because `change`, `blur`, and `focus` are the names of [the DOM events](https://developer.mozilla.org/en-US/docs/Web/Events).

**Comment by redbmk** [comment]
Please correct me if I'm way off base. It seems like a lot of examples do something like the following:

```
<Field name="asdf" render={({ input }) => <input {...input />`/>
```

Couldn't `input` from `FieldRenderProps` contain a `ref` function that would set the ref for the input? Then the `focus` function could actually call `inputRef.focus()`.

**Comment by Krknv** [comment]
Why to not use **unique names** of fields? Cause this is not react way?)

```
export const focusByName = fieldName => {
  const elem = document.querySelector(`[name='${ fieldName}']`);
  return elem && elem.focus();
};
```
