### ISSUE TITLE
Validation of invalid numbers

### ISSUE THREAD

**Issue by doasync** [final-form/react-final-form#210]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
I can't validate an input like "_ee+-..,,_" in the number field. `validate` function doesn't trigger.

### What is the expected behavior?
I expect that if I enter an invalid number like '_1..02_' there is a way to display a validation error somehow.

### Sandbox Link
https://codesandbox.io/s/82nyr7ojq2

### What's your environment?

Chrome 65.0.3325.162
Node v8.9.4
"final-form": "^4.3.1"
"react-final-form": "^3.1.4"

**Comment by erikras** [comment]
Numbers are always tricky. What you're seeing is what either React or the DOM is providing. i.e. "an invalid number is treated as `undefined`". You'll be better off using `type="text"` and doing the parse validation yourself.

**Comment by doasync** [comment]
Thanks for the clarification
