### ISSUE TITLE
Nested name fields documentation and expected bahavior

### ISSUE THREAD

**Issue by crobinson42** [final-form/react-final-form#214]
### Are you submitting a **bug report** or a **feature request**?
Documentation concern for expected behavior.

### What is the current behavior?
Nested name with dot notation casts array when using integer values.

### What is the expected behavior?
Nested name with dot notation to use object key => value structure for values.

### Sandbox Link
```
<Field
  component="input"
  type="checkbox"
  name="days.1"
/>

// form values
{
  "days": [
    null,
    true
  ]
}
```

```
<Field
  component="input"
  type="checkbox"
  name="days.one"
/>

// form values
{
  "days": {
    "one": true
  }
}
```

### Other information
I cannot find any documentation on nested values (this was discussed in several topics back from redux-form). Is the above expected behavior or might there be some configuration to offer for declarative consumption/use. 

I am happy to make a PR and contribute to documentation this with a little direction and approval.

**Comment by erikras** [comment]
Thanks for this. I've been meaning to get around to it.
