### ISSUE TITLE
Allow onSubmit function to be updated after Form has mounted

### ISSUE THREAD

**Issue by dunika** [final-form/react-final-form#218]
**feature request**

I am trying to generate a new `onSubmit` function when the props change 

I am implementing the `deadDrop` strategy you suggested [here](https://medium.com/@erikras/redux-dead-drop-1b9573705bec) (thanks for that btw !)

I am using the `mergeProps` function inside my `connect` from `react-redux` to map the new `onSubmit` function every time `deadDrop` is updated

(Also since I'm using `redux-saga`  I've to pass the resolve/reject through the actions payload)

```
({ deadDrop: { values: deadDropValues } } = {}, actions, props) => ({
      ...props,
      ...actions,
      deadDrop,
      onSubmit: values => new Promise((resolve, reject) => {
        actions.dispatch(onSubmitAction({ { ...values, ...deadDropValues }, resolve, reject })); // needed for redux saga
      }),
```

I have been trying to figure out whats been going wrong for a while now droping countless `console.logs` and unless I am mistaken or have completely missed something it would seem that once the `onSubmit` is set it is not updated on successive re-renders

Looking at the code inside `/src/ReactFinalForm.js` it seems that the config passes `onSubmit` to  the form on creation in the constructor  but  it doesn't look like `onSubmit` is ever reinitialised

**Comment by erikras** [comment]
This has been implemented in #183, but not yet published to NPM. 👍

**Comment by dunika** [comment]
You the maaaan

**Comment by erikras** [comment]
Well, credit for that PR is all @ForbesLindesay's. I'll get it published this week.

While we're sharing Medium posts... 😆 I think [this thing I built last week](https://medium.com/@erikras/getting-a-promise-from-redux-actions-d92787894368) might be even more awesome than Redux Dead Drop for submitting with Redux Saga.

**Comment by dunika** [comment]
Cool will check it out thanks
