### ISSUE TITLE
Postinstall `opencollective` script will never run

### ISSUE THREAD

**Issue by zacanger** [final-form/react-final-form#220]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

RFF has a postinstall script that runs `opencollective`, which is a devDep, so it'll only ever be run when someone is working on RFF itself.

### What is the expected behavior?

Probably a message on install

### What's your environment?

Applies to any environment that doesn't have `opencollective` installed globally.

### Other information

I did see some discussion in #172 about running `opencollective`. One possibility might be to do [what nodemon does](https://github.com/remy/nodemon/blob/v1.17.3/package.json#L42).

**Comment by timarney** [comment]
Running into this when running 

npm install --only=production

```
> react-final-form@3.4.2 postinstall /var/lib/jenkins/workspace/pipelines/Serverless/ .... /admin/node_modules/react-final-form
> opencollective postinstall || exit 0

sh: 1: opencollective: not found
```

**Comment by zacanger** [comment]
@erikras if you'd like, I can put in a PR to fix this. Looks like `styled-components` also uses a [hand-written script](https://github.com/styled-components/styled-components/blob/v3.3.0/scripts/postinstall.js) rather than the `opencollective` package.
