### ISSUE TITLE
Expose FormApi

### ISSUE THREAD

**Issue by powah** [final-form/react-final-form#221]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

Currently FormApi is accessible only in onSubmit, debug function (which is not executed in prod environment) and via decorators (am I'm missing something?).

My use case: in my app we have a form spread throughout several tabs and I need to highlight edited/invalid tabs. In order to do that I need to know field states, so FormApi.getFieldState().

Maybe we could just allow debug function to run on production environment and let the debug function decide whether it should be run in production?

**Comment by erikras** [comment]
Published fix in [`v3.3.0`](https://github.com/final-form/react-final-form/releases/tag/v3.3.0).
