### ISSUE TITLE
Uncaught rror cannot read property log of undefined  at Object.eval

### ISSUE THREAD

**Issue by BakirRabiaSalma** [final-form/react-final-form#226]
I use this code
`import React, { Component } from 'react';

const log = global.SQLECTRON_CONFIG.log;

export default class LogStatus extends Component {
  render() {
    if (!log.console && !log.file) {
      return null;
    }

    return (
      <a className="ui red label">
        <i className="terminal icon" />
        Log
        {<div className="detail">{log.level}</div>}
      </a>
    );
  }
}
`
when i run the project i get this error,

**Comment by erikras** [comment]
👎  This looks completely unrelated to this library.
