### ISSUE TITLE
[Help] Change field's value directly

### ISSUE THREAD

**Issue by pvlv** [final-form/react-final-form#231]
How change field's value directly?

**Comment by erikras** [comment]
`form.change('fieldName', newValue)`

If that is insufficient, you need to provide more code/context.

**Comment by jasan-s** [comment]
@erikras where is the ` form` coming from ?

**Comment by erikras** [comment]
It's in the [`FormRenderProps`](https://github.com/final-form/react-final-form#form-formapi).

**Comment by jasan-s** [comment]
thanks. I was getting undefined. had to update the version of `react-final-form`. now works :)

**Comment by erikras** [comment]
Yep. It changed in [`v3.3.0`](https://github.com/final-form/react-final-form/releases/tag/v3.3.0).
