### ISSUE TITLE
on submit, values object should be only the changed values

### ISSUE THREAD

**Issue by pantchox** [final-form/react-final-form#235]
### Are you submitting a **bug report** or a **feature request**?

feature request
### What is the current behavior?

Even with initial values are set it returns them all

### What is the expected behavior?

to return values that has only changed (a diff between values and initialValues)

### Other information
Basically have the ability to load a form with initialValues and only set the resulted values with the changed ones - it is good for "PATCH" requests to an API rather then sending the WHOLE data.

Thanks!

**Comment by Gnito** [comment]
This would break the expected behaviour (HTML / `<form>`) and assumes that all the APIs work in certain way.

**Comment by erikras** [comment]
Easy enough to use something like [`object-diff`](https://www.npmjs.com/package/object-diff) to accomplish this.

**Comment by pantchox** [comment]
@Gnito  how exactly? i don't understand your comment.

@erikras thanks for the suggestion, how would you implment it?
if i have a component i created that uses react-final-form, i pass to the submit the action which is being called with the new form data.
i should also call that action with the initialValues as well?
what i am asking is there a place to do the diff inside the form, like a way to manipulate the "Values" being returned from react-final-form before calling the onSubmit action.

thanks.

**Comment by pantchox** [comment]
[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/woowk98xq5)

I have forked your simple example and try to add the logic you suggested. i hope you think its ok and i am not missing something.

Thanks.
