### ISSUE TITLE
Add example (handling form submission errors with promise-listener)

### ISSUE THREAD

**Issue by artemirq** [final-form/react-final-form#238]
### Are you submitting a **bug report** or a **feature request**?

**feature request**

It would be useful to see an example with handling form submission errors with promise-listener

**Comment by artemirq** [comment]
Really I use redux-saga and this hack for catch errors

```
const LoginForm = ({ promiseListener }) => (
    <MakeAsyncFunction
        listener={promiseListener}
        start='LOGIN_REQUEST'
        resolve='LOGIN_COMPLETE'
        reject='LOGIN_FAILED'
    >
        {(onSubmit) => (
            <Form
                onSubmit={
                    (payload) => (
                        onSubmit(payload).catch(
                            ({ error }) => ({ [FORM_ERROR]: error })
                        )
                    )
                }
                ...
```

**Comment by artemirq** [comment]
@erikras Yes, I took this example as a basis. But it has little meaning, because there is not used action `REGISTER_FAILURE`, in any case, the registration will be success

**Comment by erikras** [comment]
I'm confused. Pardon my ignorance as I have never built anything serious with redux-saga... Do you need more than three actions (request, success, failure) for your form submission?

**Comment by artemirq** [comment]
@erikras No-no :)) I think, maybe need complement [this example](https://github.com/final-form/react-final-form#async-redux-submission) in order to show error handling like in [this example](https://codesandbox.io/s/9y9om95lyp). I too recently started using `redux-saga` and did not realize how to handle errors using `react-promise-listener` (even looking at the example)

As I said [earlier](https://github.com/final-form/react-final-form/issues/238#issuecomment-383689354), while I catch errors so. There may be a shorter version, not overriding the onSubmit function?

Thanks

**Comment by erikras** [comment]
Aha! You have found an important gap in the docs here. I've updated the example to disallow the first name `John` via submit validation. ⚠️ *Take note of the comment on `asyncSubmissionMiddleware.js:25`!*

Hope that helps. 👍
[![Edit 🏁 React Final Form - Async Redux Submission](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x71mx66z8w)

**Comment by artemirq** [comment]
@erikras I didn't really want to write it, but it looks like a crutch. Not particularly compatible with `redux-saga`, because if your request process failed and not processed, - we need dispatch *failed* action. And yeah, i read *note* on 25 line. I do not deny this decision, but just then we lost all sense to use `redux-saga`, because we send only *success* actions

Let's take a better look at my code

**saga.js**
```
import {
    loginRequest,
    loginComplete,
    loginFailed
} from './reducers/user';


function* login({ payload: { login, password } }) {
    try {
        const {
            data: {
                token
            }
        } = yield call(auth.login, { email: login, password });

        yield put(
            loginComplete({
                login,
                token
            })
        );
    } catch (err) {
        yield put(
            loginFailed({
                error: extractHttpError(err)
            })
        );
    }
}

export default function* () {
    yield takeLatest(loginRequest, login);
};
```

**reducers/user.js**
```
import { createActions, handleActions } from 'redux-actions';

export const defaultState = {
    isAuthorized: false,
    login: null,
    token: null
};

export const {
    loginRequest,
    loginComplete,
    loginFailed
} = createActions(
    'LOGIN_REQUEST',
    'LOGIN_COMPLETE',
    'LOGIN_FAILED'
);

export default handleActions({
    [loginComplete]: (state, { payload: { login, token } }) => ({
        ...state,
        isAuthorized: true,
        login,
        token
    })
}, defaultState);
```

`loginRequest` action always have to send `{ login, password }` because user reducer save authorized user **and only**
`loginFailed` action always have to send errors. Next here, which could intercept, mean **react-promise-listener**, which works with *final-form* and give him information, which errors happened

On fact me until suits my decision with:
```
<Form
     onSubmit={
           (payload) => (
               onSubmit(payload).catch(
                   ({ error }) => ({ [FORM_ERROR]: error })
                 )
            )
       }
      ...
```

The only thing that could make it easier is if final-form could handle rejects as error feeders

I was trying to say all what I think, can be this will help someone
If you have any other ideas, spit it out. I want us to find a better solution. I will be glad to talk more :)

Thank you for trying to help. I appreciate your incredible contribution, your projects and your helping people <3

**Comment by erikras** [comment]
You make good points. My reasoning behind making submit errors come back on resolved promises was to save rejected promises for HTTP communications errors, not validation errors.

However, due to the functional awesomeness nature of javascript this is pretty easily remedied with a higher order function.

```jsx
// Takes rejected errors and returns them in a resolved promies
const resolveErrors = asyncFn => (...args) =>
  asyncFn(...args).then(success => success, error => Promise.resolve(error))

...

<MakeAsyncFunction
  listener={promiseListener}
  start={REGISTER}
  resolve={REGISTER_SUCCESS}
  reject={REGISTER_FAILURE}
>
  {onSubmit => (
    <Form onSubmit={resolveErrors(onSubmit)}>...fields here...</Form>
//                  ^^^^^^^^^^^^^^^^^^^^^^^
  )}
</MakeAsyncFunction>
```

**Comment by MartinCerny-awin** [comment]
Is there an option to reset the form after successful resolution? I am not able to access `formAPI` when I am using `react-redux-promise-listener`.
