### ISSUE TITLE
Using `change` to replace a FieldArray entry doesn't work

### ISSUE THREAD

**Issue by renodesu** [final-form/react-final-form#240]
### Are you submitting a **bug report** or a **feature request**?

Bug report.
(Behaviour doesn't match expectation, unsure if by design)

### What is the current behavior?

When working with FieldArray, this works (prop changes, form updates, field value is `foo`)
```
change(`${name}.lastName`, 'foo')
```
This does not work.
```
change(name, { lastName: 'foo', /* other props */ })
```

### What is the expected behavior?

This SHOULD work:
```
change(name, { lastName: 'foo', /* other props */ })
```

Expectation: Said FieldArray entry should be replaced entirely with given object, thus changing `lastName` (and any other props that might be a `Field`).
Result: Entry doesn't change at all. No merge, replace or anything takes place. No errors.

### Sandbox Link
FieldArray example modified to demo the effect (2 buttons next to Customer-entry)
https://codesandbox.io/s/rp1xm6z4n

### What's your environment?

Node 9, RFF 3.3.1, FF 4.5.2, Chrome 66.
Issue is demoable in codesandbox.

### Other information

None.

**Comment by wespickett** [comment]
It's because you don't define a a field with `name`, you only set `${name}.firstName`, and `${name}.lastName`

```
<Field
    name={`${name}.firstName`}
```

```
<Field
    name={`${name}.lastName`}
```

You would need a field:

```
<Field
    name={`${name}`}
```

to do what doesn't currently work

**Comment by renotoaster** [comment]
Right, makes sense in a way. I assumed `something[0]` were treated as arrays in that way as well. Is there a way to replace a field entry completely? Other than insertToIndex+removeprevious with `form.batch`.

**Comment by gertdreyer** [comment]
Working in recent versions
