### ISSUE TITLE
Changing initialValues without changing form state

### ISSUE THREAD

**Issue by dcosson** [final-form/react-final-form#246]
Hi, first off thanks for all the work maintaining this library. For a still relatively young library it has a ton of functionality and still manages to be pretty intuitive.

### What is the current behavior?

I've noticed that when the form renders when initialValues has changed, it updates the form state for all fields to match those new values. This behavior is clearly useful in the case that an external process changed the data and we want to synchronize the form to reflect that. But the alternative behavior I could imagine wanting in some cases is that the form values stay the same but are now dirty because they differ from initialValues. This would be particularly useful if there are any fields that were dirty when initialValues changed and we don't want to discard those local changes.

Is there an easy way to get this behavior?

I may just be missing something but I'm struggling to find the right combination of final-form features to do this. I can prevent initialValues from changing at all if my remote state changes, but then the form's dirty state won't be up to date. Or, in the render method after initialValues updates I can call onChange to put back the dirty values I had previously, but I think this would cause a brief flicker from an inconsistent render.

### Use Case

At a higher level, the reason I want to do this is to build an auto-save form where I can keep updating the form while it's saving, and once a save completes update initialValues with the remote state so the form's dirty state will reflect whether there are any additional changes. I had a look at some examples, including the auto-save examples, and the Load, Save, Reinitialize example which is very similar but gets around this problem by disabling the form during save. 

### What's your environment?

React Final Form 3.4.0, Final Form 4.5.2, React 15.6.1

**Comment by dcosson** [comment]
FWIW, I was able to accomplish this manually.

The trick was to create a mutator that does a single `changeValue` call to update the final-form state, and then in render assign the bound version of it as a property on my component so I have access to it from the other lifecycle methods in my component. 

Then the first time my component tries to render when initialValues have changed due to the server returning its current state:

1. in `componentWillReceiveProps` I assign a reference to the getFormState().values
2. in `componentDidUpdate`, which is now after the current form state has updated to revert to the new initialValues, I diff all my fields against the previous form state values. If there are any differences, I use my bound mutator from above to change the final-form state to match the changed form value.

It actually works surprisingly well, I can keep editing the form while its saving, and then if there are any changes when a save comes back it shows up as dirty again and gets auto-saved in the next debounced save cycle. And I haven't so far seen any glitches from the fact that I'm sometimes doing two renders by updating final-form state in componentDidUpdate.

But I'm still interested to hear back from maintainers if there is a better way to do this that wouldn't require a double-render, or if adding a better way into final-form makes sense. I don't think this is *that* much of a fringe usecase.

**Comment by erikras** [comment]
Redux Form has [`keepDirtyOnReinitialize`](https://redux-form.com/7.3.0/docs/api/reduxform.md/#-code-keepdirtyonreinitialize-boolean-code-optional-) which accomplishes this. It's interesting how all of the edge cases that Redux Form experienced and adapted to in its growth are happening again with React Final Form.

Great work on using a mutator for a workaround! Impressive. 👍 

I will look into what it would take to add a `keepDirtyOnReinitialize` config option to Final Form...

**Comment by erikras** [comment]
Published fix in `final-form@4.7.3` and `react-final-form@3.5.0`. You can now specify a `keepDirtyOnReinitialize` prop to the `Form` to toggle this behavior.

**Comment by dcosson** [comment]
Sweet, thanks! I'll have to play around with the new flag.

**Comment by zarabotaet** [comment]
keepDirtyOnReinitialize seems doesnt work with FieldArray

**Comment by doxomo** [comment]
@erikras keepDirtyOnReinitialize seems doesnt work with FieldArray

**Comment by doxomo** [comment]
quick solution for FieldArray
...
keepDirtyOnReinitialize
initialValuesEqual={() => true}
...
