### ISSUE TITLE
Validation of the presence of one of the two fields

### ISSUE THREAD

**Issue by perevezencev** [final-form/react-final-form#253]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

If you need to validate the presence of one of the two fields, sometimes you need to return an error such as `"One of the fields username or email is required"`. Now it can be done only in the `onSubmit` function with `{ [FORM_ERROR]: 'my error message' }`

### What is the expected behavior?

This situation can be handled in the validate function in the Form component.

```
<Form
  onSubmit={onSubmit}
  validate={values => {
    const errors = {};
    if (!values.username && !values.email) {
      errors[FORM_ERROR] = "One of the fields username or email is required";
    }
    return errors;
  }}
...
```

### Sandbox Link

https://codesandbox.io/s/2xn5yz48lp

**Comment by perevezencev** [comment]
It is also possible to add the `required` field to the `meta` object, so that it is possible to track which field should be marked with an asterisk in ui

**Comment by powah** [comment]
Validation functions accept 2 params: value and **allValues**. You can do something like this:
`const atLeastOneFieldRequired = (value, allValues) => !value && !allValues.myOtherField ? 'At least one field is required : undefined;`

**Comment by perevezencev** [comment]
Of course, but the validation still apply to the field and not to the whole form or part of it

**Comment by erikras** [comment]
If you're going to do it in sync validation, like in your sandbox, you need to look at the `error` value given to the form render function. With that and `submitFailed`, you can determine how to show the error. Like so:

[![Edit 🏁 React Final Form - Submission Errors Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rl1y194p6n)
