### ISSUE TITLE
Setting FORM_ERROR on form.submit() is not being reset in form.reset()

### ISSUE THREAD

**Issue by AlbertDennis** [final-form/react-final-form#258]
### Are you submitting a **bug report** or a **feature request**?
I believe this is a bug, as I can't find anyway to reset this value through public methods
The fix shall be in Final-Form NOT React-Final-Form.

### What is the current behavior?
1)  Render method with ref to Form object as this.theForm
     &lt;Form onSubmit={this.addContact} 
                ref={(F) => this.theForm = F}   ...

2) When submit button clicked and there is an error display this in field FORM_ERROR  
    addContact = contact => {
        ...
	return {[FORM_ERROR]: "Please enter an email address and or phone number"};
}
3) Form fails validation and displays message great!
     &lt;Form ...
    {submitError && &lt;div&gt; >{submitError}&lt;/div&gt;}
     &lt;/Form&gt;

Now for the problem
4)   I have a button that should clear the form content back to initial state
      (I have a reference to form  (see step 1 above)

      this.theForm.form.reset();

5) Everything is reset except for the submitError message.

See possible solution below in Other information

1) Take your existing demo from https://codesandbox.io/s/9y9om95lyp
2) Enter user name 'erikras' and password of 'final'
3) Click 'Log In'
4) You should now see text in red between Password text box and buttons 'Login Failed'
5) Now click Reset button. The text ('Login Failed')  is NOT cleared, everything else is perfect.

### What is the expected behavior?
The expected behavior should be formState.submitError should be reset to undefined to remove the submit error message.  
Please see possible solution below.

### What's your environment?

"react": "^16.3.1",
"redux": "^3.7.2",
"final-form": "^4.6.1",
"react-final-form": "^3.4.2",

### Other information
Here is a fix that I did get to work, but I am not sure that how you wish to do it.

1) File final-form.es.js
2) sumit function line 967 sets a dynamic field   formState.submitError = errors[FORM_ERROR] (Great no problem)

Now for the fix 
3) File final-form.es.js   (Same file)
4) Add the following to method reset line 872

BEFORE FIX:
 reset: function reset() {
      var initialValues = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : state.formState.initialValues;

      state.formState.submitFailed = false;
      state.formState.submitSucceeded = false;
      delete state.formState.submitErrors;
      delete state.formState.lastSubmittedValues;
      api.initialize(initialValues || {});
    },

AFTER FIX:
 reset: function reset() {
      var initialValues = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : state.formState.initialValues;

      state.formState.submitFailed = false;
      state.formState.submitSucceeded = false;
      delete state.formState.submitError;               //<<<<<<<FIX!!!
      delete state.formState.submitErrors;
      delete state.formState.lastSubmittedValues;
      api.initialize(initialValues || {});
    },

**Comment by rosskevin** [comment]
I am also seeing the need to clear a FORM_ERROR for a signin dialog.  I could execute a form api call from a custom `onChange` handler added to the field which resets the `FORM_ERROR`, but I'm open to ideas.  Currently my FormSpy based submit button is permanently disabled by this case:

**When** I fill in incorrect signin information
**And** I click submit
**Then** I should see a `FORM_ERROR`
**And** the submit button should be disabled 
**When** I alter the signin information
**Then** the `FORM_ERROR` should disappear
**And** the submit button should be enabled

It seems that no combination of render props gives me what I need, but I think if I could clear the `FORM_ERROR` I probably would have the values expected.  Here's a snip of my submit button, much like the example:

```js
const Submit = (props: SubmitProps) => {
  const { disabled, children, ...rest } = props

  return (
    <FormSpy
      subscription={{
        errors: true,
        hasSubmitErrors: true,
        hasValidationErrors: true,
        invalid: true,
        pristine: true,
        submitting: true,
      }}
    >
      {form => {
        // disable when marked as such or errors
        log.debug('render', props, form)
        const { invalid, pristine, submitting } = form
        return (
          <Button
            type="submit"
            {...rest}
            disabled={disabled || invalid || pristine || submitting}
          >
            {children}
          </Button>
        )
      }}
    </FormSpy>
  )
}
```

**Comment by rosskevin** [comment]
Working as expected?  Meaning that the case and details I provided are to be ignored?  Or that it is working as I expected?  

What API can I use to reset the form error for this case:

**When** I fill in incorrect signin information
**And** I click submit
**Then** I should see a `FORM_ERROR`
**And** the submit button should be disabled 
**When** I alter the signin information
**Then** the `FORM_ERROR` should disappear
**And** the submit button should be enabled

**Comment by gertdreyer** [comment]
The behaviour for which the issue was opened was solved... 

The extra behaviour you wanted extra is also reasonably easy to add to achieve.
Most probably you do not want to clear the FORM_ERROR from the state but rather just know some fields were touched after that error.
See below.
https://codesandbox.io/s/react-final-form-submission-errors-example-forked-x8ct7f?file=/index.js

**Comment by rosskevin** [comment]
Thanks @gertdreyer.  For those that bump into this, you can achieve what I desired by watching some combination of `hasValidationErrors` and `modifiedSinceLastSubmit` to suit your case.

**Comment by rosskevin** [comment]
For future searchers, I found the best combination for submit button disablement to be a modified version of the example:

```jsx
              disabled={
                pristine ||
                hasValidationErrors ||
                submitting ||
                (submitFailed && !modifiedSinceLastSubmit)
              }
```
https://codesandbox.io/s/react-final-form-submit-button-disablement-dd2dyt?file=/index.js:2474-2670
