### ISSUE TITLE
Avoid using componentWillReceiveProps, componentWillUpdate lifecycle methods

### ISSUE THREAD

**Issue by powah** [final-form/react-final-form#267]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

Currently **ReactFinalForm** uses both _componentWillReceiveProps_ and _componentWillUpdate_ and **FormSpy** and **Field** use _componentWillReceiveProps_ which generates warnings like: 

> Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.
More info here: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

### What's your environment?
React: 16.4.0 
FF: 4.7.3
RFF: 3.5.1

**Comment by erikras** [comment]
Yes, this has been on my mind. It's not clear to me if there is a way to accomplish what is currently being accomplished without using the `UNSAFE_` prefixes, but migration to using the `UNSAFE_` is definitely a priority.
