### ISSUE TITLE
hasSubmitErrors is always true after submitting the form If I directly pass action dispatch to onSubmit

### ISSUE THREAD

**Issue by changLiuUNSW** [final-form/react-final-form#271]
```hasSubmitErrors``` is always ```true``` after I submit the form If I directly pass action dispatch to onSubmit

Here is an online example:
https://codesandbox.io/s/353vprw06

It has annoyed me for a long time and cannot figure out why it happen. Really hope someone can help me to solve this issue.

Thanks

**Comment by erikras** [comment]
This is because `onSubmit` should not resolve to anything on success. Anything "resolved" is treated as a submit error. Here they are printed out:

[![Edit my-app](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mjxnqz3mv9)

**Comment by changLiuUNSW** [comment]
@erikras 
Thanks for your quick response.
May I ask you what is the best way to handle my case ? Because I think pass dispatcher to ```onSubmit``` is  very normal.

**Comment by erikras** [comment]
If you don't care to ever return submission errors, then this would do it:
```jsx
 <SearchForm onSubmit={values => { search(values) }}/>
```
...otherwise, you'll need to figure out how to distinguish between errors and success. If you're rejecting your promise on errors, it could be:
```jsx
<SearchForm
  onSubmit={values =>
    new Promise((resolve, reject) => {
      search(values).then(
        () => resolve(),
        errors => resolve(errors)
      )
    })
  }
/>
```
