### ISSUE TITLE
Support for Nested Forms?

### ISSUE THREAD

**Issue by Togrias** [final-form/react-final-form#276]
Is it supported to have nested forms? For instance, a form where a field itself is a form.

I intend to make certain fields editable via a "popup" portal, where the popup itself is managed by a form. When you "submit" the nested form, the field updates.

However, it seems that the new FormState api is leaking into nested forms.

**Comment by erikras** [comment]
Sounds fairly similar to the [Wizard Form](https://codesandbox.io/s/km2n35kq3v) example. Note how an outer container is managing each submit of the values in the "sub forms".

**Comment by Togrias** [comment]
My intended use case is more complicated than that...

It's supposed to be a form, where one of the fields is a sortable table. When you click one of the rows, a new form pops out, allowing you to edit the row. Not to mention one of the fields on that row is itself a table, which is editable the same way...

I guess it's unsupported, but I used to get it to work. Not sure what caused it to break. I think it's to do with context (the inner forms accidentally receiving the context of the outer form)

**Comment by gvautour** [comment]
I am trying to do the exact same thing.

> I intend to make certain fields editable via a "popup" portal, where the popup itself is managed by a form. When you "submit" the nested form, the field updates.

The issue I'm getting into is that the onSubmitCustom (inner form) triggers for both the onSubmit for the inner form and the onSubmit for the outer form.

As a workaround, if I had a way to capture the form id, I could return false on the outer form's onSubmit when the onSubmitCustom (inner form) is triggered. But I have yet to figure out how to do that.

**Comment by erikras** [comment]
Published fix in [`v3.6.3`](https://github.com/final-form/react-final-form/releases/tag/v3.6.3).

**Comment by gvautour** [comment]
See this working [example](https://codesandbox.io/s/p7p6lx24xq)
