### ISSUE TITLE
Form with validate, initalValues and decorators fails to render

### ISSUE THREAD

**Issue by ak1394** [final-form/react-final-form#278]
### What is the current behavior?

Form with initial value, validator and decorator (which uses  final-form-calculate to update one of the fields of form based on the value of the other) fails to render if the value for the other field is present in the initial values.

On render, exception "Cannot read property 'validateFields' of undefined" is thrown.

### What is the expected behavior?

Form should render, fields should reflect initial values and calculated value.

### Sandbox Link

https://codesandbox.io/s/y7qxyml459

### What's your environment?

"react-final-form": "^3.4.0",
"final-form-calculate": "^1.1.0",
"final-form": "^4.6.1"

**Comment by erikras** [comment]
Published fix in [`final-form@4.8.3`](https://github.com/final-form/final-form/releases/tag/v4.8.3).

**Comment by ak1394** [comment]
Thanks a lot for a quick resolution!!!
