### ISSUE TITLE
Material-UI 1.2: Select with Final-Form

### ISSUE THREAD

**Issue by LucienBouletRoblin** [final-form/react-final-form#285]
I tried to use Final-Form with the Select component from Material-UI 1.2.3 but couldn't make it work.

Could you share an example of such form? Thank a lot!

**Comment by BigBuckBunny** [comment]
Hi,
these work for me

import { Select } from 'final-form-material-ui';


                              <Field
                                name="locale"
                                component={Select}
                                placeholder={formatMessage(messages.select_locale)}
                              >
                                {this.props.languageItems.map((locale) => (
                                  <MenuItem key={locale._id} value={locale.locale}>{locale.name}</MenuItem>
                                ))}
                              </Field>

<Field
                                    name="categories"
                                    component={Select}
                                    multiple
                                    format={value => Array.isArray(value) ? value : []} // eslint-disable-line
                                    MenuProps={{
                                      PaperProps: {
                                        style: {
                                          maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
                                          width: 200,
                                        },
                                      },
                                    }}
                                  >
                                    {this.props.categoryItems.map((category) => (
                                      <MenuItem key={category._id} value={category._id}>{category.title}</MenuItem>
                                    ))}
                                  </Field>

Pierre

**Comment by LucienBouletRoblin** [comment]
Thanks! I couldn't have a look earlier but below is an example inspired from [final-form-material-ui](https://github.com/Deadly0/final-form-material-ui#readme):

```
import React from "react";
import Select from "@material-ui/core/Select";
import FormControl from "@material-ui/core/FormControl";
import InputLabel from "@material-ui/core/InputLabel";
import FormHelperText from "@material-ui/core/FormHelperText";

const SelectInput = ({
  input: { name, value, onChange, ...restInput },
  meta,
  label,
  formControlProps,
  ...rest
}) => {
  return (
    <FormControl
      {...formControlProps}
      error={showError}
      style={{
        minWidth: "100%"
      }}
    >
      <InputLabel htmlFor={name}>{label}</InputLabel>
      <Select
        {...rest}
        name={name}
        onChange={onChange}
        inputProps={restInput}
        value={value}
      />
      {meta.error && (
        <FormHelperText>{meta.error}</FormHelperText>
      )}
    </FormControl>
  );
};

export default SelectInput;
```
