### ISSUE TITLE
Add previous value to parse callback arguments

### ISSUE THREAD

**Issue by cedricmessiant** [final-form/react-final-form#286]
# Feature request

## What is the current behavior?

`parse` function only takes `value` and `name` ( https://github.com/final-form/react-final-form#parse-value-any-name-string--any--null )

## What is the expected behavior?

It would be nice if it could also provides the previous value for this field.

## Why ?

Here is a sandbox to illustrate my problem and why I need this feature: https://codesandbox.io/s/pyorr6qmm
I need to edit my text field in multiple languages. To do this, I use an object that contains values for all languages in conjunction with `parse` and `format`
As you can see, I have been able to get the value from `values` but when the field is deep in a complex form, it is not a very elegant solution.

Maybe it is not the right approach and I should do it differently, I'm open to suggestions.

### What's your environment?

🏁 React Final Form version: 3.6.2
🏁 Final Form version: 4.8.2

**Comment by erikras** [comment]
Another (possibly more elegant?) option would be to have a custom input component that was clever enough to edit objects. Behold:
```jsx
const LocaleInput = ({
  input: { value, onChange, ...otherListeners },
  locale
}) => (
  <input
    {...otherListeners}
    value={value[locale] || "" /* "" is to ensure it's controlled */}
    onChange={event => onChange({ ...value, [locale]: event.target.value })}
  />
);
```
[![Edit q70ko71414](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q70ko71414)

**Comment by cedricmessiant** [comment]
Thanks, it'll do the job!
(also thanks for this awesome library! ;-) )
