### ISSUE TITLE
reset state react-final-form with redux and redux-persist

### ISSUE THREAD

**Issue by juvasquezg** [final-form/react-final-form#290]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

I am using **react-final-form** with **redux** and **redux-persist**. The data loads well, the first time in the state of redux and they are shown in the form, when I try to change a value of another field, the state in redux is reset and remains blank. The state of the form in **final-form** is reset, maybe in FormSpy I think.

View the image https://ibb.co/ebvguo 

1. select a value (Ambulancia 1)
2. page reload-refresh
3. change other field

### What is the expected behavior?

Do not reset the current state, add a new change value

### Sandbox Link

https://codesandbox.io/s/zk0q71ppx4

View the image https://ibb.co/ebvguo 

### What's your environment?

```
    "react-final-form": "^3.4.0",
    "final-form": "^4.8.3",
```

**node version:** v8.1.4

**Comment by juvasquezg** [comment]
Hi,

Some help? 

Thank you

**Comment by erikras** [comment]
Your problem is that you're overriding the value in your inputs. That's RFF's job to handle. It seems to work better when I add this to your `<Form>` line:
```jsx
initialValues={form}
```
That sets the _initial_ values from Redux, but lets RFF control the form values as you enter them. Make sense?

**Comment by juvasquezg** [comment]
Hi,

Thank you so much, work fine!

You can close the issue
