### ISSUE TITLE
Material ui v1 Integration

### ISSUE THREAD

**Issue by ChrisWiles** [final-form/react-final-form#294]
I can't get the Material UI Textfield to behave as it should.  The field does not seem to focus properly and is not getting the material UI focused classname applied to it.

Example
https://codesandbox.io/s/2p48zw575p

**Comment by erikras** [comment]
Weird. Switching `inputProps` to `InputProps` in the `TextField` component fixed it. The difference is [subtle](https://material-ui.com/api/text-field/#props).
