### ISSUE TITLE
Question: how to do a rest call in side the form updating other fields. [has gif]

### ISSUE THREAD

**Issue by vospascal** [final-form/react-final-form#298]
Hello @erikras,
First off great library!, 

How would i do the following been struggling with this for sometime now
basicly because i cant form.batch update from in side a Field calling a input.onChange on a lower level gives me problems with controlled/uncontrolled inputs because its not the proper way. 
Any tips?

Gif that illustrates how it should work. https://image.ibb.co/iCPnzy/Untitled.gif

Workflow....
Fill out zipcode and house number.
when these are filled out and have no errors a Rest call gets the street and city and fills it out.

So it listens to the changes in the 2 fields zipcode and house number to prefill the other 2 fields.

**Comment by vospascal** [comment]
![untitled](https://user-images.githubusercontent.com/6942179/42289433-ca1c66fc-7fbf-11e8-8f72-60389a151324.gif)

**Comment by crobinson42** [comment]
@vospascal I would recommend using `<FormSpy>` and the `onChange` prop to trigger your async call.

**Comment by vospascal** [comment]
@crobinson42 bit late... solution i used withReactFinalForm which is the form api.
its a hoc around your class like so : export default withReactFinalForm(YourClass)
then needs 

YourClass.propTypes = {
  reactFinalForm: PropTypes.object.isRequired,
};

in the component i used 

  changFieldsCallback = (name, value) => {
    const { reactFinalForm } = this.props;
    reactFinalForm.batch(() => {
      reactFinalForm.change(name, value);
    });
  };
