### ISSUE TITLE
What is the best way to subscribe to n fields in order to dispatch specific handlers?

### ISSUE THREAD

**Issue by fernandofleury** [final-form/react-final-form#299]
Hey, thanks for providing this amazing library. It has definitively my life easier!

I've been struggling to find a proper way to subscribe to N fields then dispatch a handler based on it.

Recently I've wrote a small component to help me achieve this, and I wanted some feedback on it to be sure I'm on the right track:

```js
import React, { Component } from 'react';
import { PropTypes } from 'prop-types';
import { FormSpy } from 'react-final-form';
import { curry, reduce, filter, noop } from 'lodash/fp';

const toKeys = (fn, arr) =>
  reduce(
    (acc, field) => {
      acc[field] = fn(field);

      return acc;
    },
    {},
    arr
  );

const getChangedFields = (prev, next, arr) =>
  filter(field => {
    if (!prev[field] && !next[field]) {
      return false;
    }

    if (prev[field] !== next[field]) {
      return true;
    }

    return false;
  }, arr);

const getChanges = curry((values, errors, field) => ({
  value: values[field],
  valid: !errors[field]
}));

class FieldSpy extends Component {
  static propTypes = {
    fields: PropTypes.arrayOf(PropTypes.string).isRequired,
    onChange: PropTypes.func.isRequired
  };
  
  // create an object with keys/falsy values to match against later
  previousValues = toKeys(noop, this.props.fields);

  handleChange = ({ values, errors }) => {
    const { fields, onChange } = this.props;

    const changedFields = getChangedFields(this.previousValues, values, fields);

    if (changedFields.length) {
      onChange(toKeys(getChanges(values, errors), changedFields));
    
      this.previousValues = { ...this.previousValues, ...values };
    }
  };

  render() {
    return (
      <FormSpy
        onChange={this.handleChange}
        subscription={{ values: true, errors: true }}
      />
    );
  }
}

export default FieldSpy;
```

and then usage becomes: `<FieldSpy fields={['name', 'age']} onChange={console.log} />`

This can be easily extended into a renderProp for conditional render if needed. but I feel like the regular field subscription is just fine for these cases.

Should I be trying to achieve this differently? Or is it ok like this?

Thanks!

**Comment by pRdm** [comment]
Been looking around for a similar solution and it seems like many people are asking the same thing (e.g. #297). 

This [example decorator](https://github.com/final-form/final-form-calculate) subscribes to changes and performs updates on other fields, but I'm sure you can write a custom decorator to perform some custom logic instead.

**Comment by fernandofleury** [comment]
I'll close since this wasn't addressed
