### ISSUE TITLE
Material-UI demo

### ISSUE THREAD

**Issue by oliviertassinari** [final-form/react-final-form#302]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

The codesandbox doesn't load: https://codesandbox.io/s/2z5y03y81r

### What is the expected behavior?

The codesandbox loads: https://codesandbox.io/s/kmn0x7pn97

**Comment by oliviertassinari** [comment]
I have some other issue with the demo, for instance, the link to http://material-ui-next.com/ is outdated. Or the alignment could be improved with a Grid or the Button could be changed. Let me know how you want to move forward. I have time available to improve the demo. Thank you!

**Comment by oliviertassinari** [comment]
We should be able to rename the demo title from `Material-UI 1.0` to `Material-UI`.

**Comment by erikras** [comment]
Fixed. Thanks!

**Comment by oliviertassinari** [comment]
@erikras This was fast :).

**Comment by GuskiS** [comment]
Themes are not working in that example as well :disappointed:

**Comment by erikras** [comment]
@GuskiS Would you like to show me how to fix that?

**Comment by GuskiS** [comment]
I wish, but haven't figured it out yet.

**Comment by GuskiS** [comment]
@erikras Found the issue, `inputProps` => `InputProps`
