### ISSUE TITLE
How to create a dynamic form

### ISSUE THREAD

**Issue by bhupesh-sf** [final-form/react-final-form#306]
I need to create a dynamic form kind of a query builder. Please see the attached screenshot for the exact requirement.
![dynamic form to be created](https://user-images.githubusercontent.com/6471510/42996448-388a307e-8c31-11e8-8b19-46bbb34bd39b.png)

**Comment by maciejmyslinski** [comment]
Thanks for giving react final form a try @bhupesh-sf!

What exactly about the form you build is challenging for you?

**Comment by erikras** [comment]
Looks a bit like the [Field Arrays Example](https://github.com/final-form/react-final-form#field-arrays).

**Comment by bhupesh-sf** [comment]
That time I switched to something else. Will surely take a look on this for next assignment. Thanks for your support.
