### ISSUE TITLE
Warnings in strict mode

### ISSUE THREAD

**Issue by justingrant** [final-form/react-final-form#319]
I just wrapped my react.js app in a <[`StrictMode`](https://reactjs.org/docs/strict-mode.html)> component, and react-final-form yielded the following warnings, two of which are complaining about react-final-form. 

> Warning: Unsafe lifecycle methods were found within a strict-mode tree:
>     in App
> 
> componentWillMount: Please update the following components to use componentDidMount instead: Autocomplete, **ReactFinalForm**
> 
> componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Autocomplete, Transition, t
> 
> componentWillUpdate: Please update the following components to use componentDidUpdate instead: **ReactFinalForm**
> 
> Learn more about this warning here:
> https://fb.me/react-strict-mode-warnings
> 

I assume that this will repro in any app that's using react-final-form wrapped in a `<StrictMode>` component, but if not let me know and I'll build a simplified repro case.

**Comment by ghengeveld** [comment]
![schermafbeelding 2018-10-30 om 14 19 40](https://user-images.githubusercontent.com/321738/47720738-e3127e80-dc4e-11e8-9de0-fb0fb7bfac87.png)

Just a heads up ☝️

**Comment by stramel** [comment]
Any progress on this?

**Comment by erikras** [comment]
This should be fixed in `v5`. Reopen if not.
