### ISSUE TITLE
Migration guide for redux-form to react-final-form

### ISSUE THREAD

**Issue by Whoaa512** [final-form/react-final-form#325]
Long time user of redux-form, and looking to migrate an existing production app. I was wondering if there are any existing resources for migrating. 

Mainly I'm looking for a list of things that don't map easily, or a set of code examples that compare the two.

Thank you for the amazing work @erikras!

**Comment by Whoaa512** [comment]
FYI for people who find this later, I found @erikras's [presentation at React Alicante](https://www.youtube.com/watch?v=WoSzy-4mviQ) to be very helpful in seeing how to migrate

**Comment by petermikitsh** [comment]
Watched the video. 40 minutes well spent. It looks like many of the ideas carry over, and that the bundle size is kept in check by making the endless feature requests that come into making something like a form library as plugins (which is awesome). For example, if you're like me and have array-type data in your forms, then you can use the `react-final-form-arrays` plugin. If not, you don't have it by default, and therefore have a smaller bundle.

I haven't migrated yet, but I'm left with the impression that it's going to be relatively straightforward. You still have a `<Field>` component, and importing that one component is probably >75%+ of my `redux-form` inputs. Also looking forwarding to axing lodash from bundle.

**Comment by erikras** [comment]
Here's a couple of paragraphs about how to migrate [on StackOverflow](https://stackoverflow.com/a/56868996/103690). People who have made the leap all say it's pretty easy.

**Comment by AndyOGo** [comment]
The migration guide is easy to follow for simple forms.
Though if one made exhaustive use of `redux-form` [Action Creators](https://redux-form.com/8.2.2/docs/api/actioncreators.md/) and [Selectors](https://redux-form.com/8.2.2/docs/api/selectors.md/) it does not help much in this regard of complex forms.
