### ISSUE TITLE
Field has name prop in meta props

### ISSUE THREAD

**Issue by VladShcherbin** [final-form/react-final-form#34]
### Are you submitting a **bug report** or a **feature request**?

Probably a bug

### What is the current behavior?

Field has `name` prop both in `input` and `meta` props.

### What is the expected behavior?

From the docs, `meta` should not have duplicate `name` prop, it exists only in `input` props.

### Sandbox Link

https://codesandbox.io/s/5z7z467o4l

Open the console and you'll see it.

**Comment by erikras** [comment]
I noticed this the other day but was on another task and forgot about it. Thanks for bringing it up!

**Comment by erikras** [comment]
Published in [`v1.2.0`](https://github.com/final-form/react-final-form/releases/tag/v1.2.0).
