### ISSUE TITLE
Update field value according to another field

### ISSUE THREAD

**Issue by jferrettiboke** [final-form/react-final-form#348]
Hi,

I am having an issue with chained selects. Is there any way to change values of other fields according to another field's value?

I created a [sandbox](https://codesandbox.io/s/v1qoq1xn65) so that it is easy to look at. If you select a currency from first select, let's say "usd", the country select doesn't select any option. As you can see in the state of the form, "country" value is still "IE" (the previous value).

I would like to select the first country available for a given currency. So, I thought removing `<option />` it would work but it doesn't. Any idea how to solve this without wrapping the form and send data to its parent component? Is there any way to solve this just using RFF?

Thanks.

**Comment by davidroeca** [comment]
@jferrettiboke I've been struggling with this one recently too, and here's the approach that I'm currently taking:

```javascript
// `function` required since there is recursion involved
function DependentField({
  parentFields,
  ...remainingProps
}) {
  if (!parentFields?.length) {
    return <Field {...remainingProps} />
  }
  const [nextParent, ...remainingParents] = parentFields
  return (
    <Field
      name={nextParent}
      subscription={{value: true}}
      render={({input: {value}}) => {
        const renderProps = {
          ...remainingProps,
          [nextParent]: value,
        }
        return (
          <DependentField parentFields={remainingParents} {...renderProps} />
        )
      }}
    />
  )
}
```

If any listed parent field changes, then a the new prop is passed to the child. It can be used like so:

```javascript
const MyDependentField = () => (
  <DependentField
    parentFields=['parentField1', 'parentField2']
    name='myDependentField'
  >
    {({ input, meta, parentField1, parentField2}) => (
      {/* render whatever you want here */}
    )}
  </DependentField>
)
```

I wish there were a nicer way of doing this out of the box or via an extension, but the `DependentField` approach here has worked for me nicely.

A few related issues:
https://github.com/final-form/react-final-form/issues/297
https://github.com/final-form/react-final-form/issues/273

**Comment by phoulgaux** [comment]
We use a `FormSpy` component to do for example something like this:

```jsx
<Field name="first">
  { /* ... */ }
</Field>
<FormSpy
  subscription={{ /* ... */ }}
  render={({ form }) => (
    <Field name="second">
      { /* you can do something like this here: */ }
      {({ input }) => (
        <Input {...input} enabled={form.getFieldState('first').valid} />
      )}
    </Field>
  )}
/>
```

In short: with `FormSpy` you get the `FormApi` object to interact with the form, for example use `getFieldState` method.

**Comment by davidroeca** [comment]
My challenge with `FormSpy` is the `subscription` prop. In the above case, you’d need to subscribe to `{{ values: true }}` at the very least for this component to render appropriately.

When subscribed to `values`, the FormSpy component will trigger a rerender if *any* field’s value has changed, regardless of whether or not I even use that field’s value to render my dependent component.

**Comment by phoulgaux** [comment]
Yeah, everything depends on the scale, but for small to medium forms it’s easily sufficient.

**Comment by davidroeca** [comment]
Agreed, as long as render doesn’t trigger unnecessary side effects, it should be fine for smaller forms (e.g. a dropdown that depends on another field and a server response should cache the server responses appropriately).

It just seems counter to the design of this library to subscribe to more fields than necessary.

**Comment by erikras** [comment]
> As you can see in the state of the form, "country" value is still "IE" (the previous value).

Seems like this could be handled with a [Declarative Form Rule](https://medium.com/@erikras/declarative-form-rules-c5949ea97366), no?

**Comment by jferrettiboke** [comment]
Hey guys, thanks for all answers but I am not sure if this is what I need. I want to set a field value according to another field value. How can I solve my needs?

**Comment by jferrettiboke** [comment]
Thanks @erikras. This seems to be the solution.

**Comment by davidroeca** [comment]
:man_facepalming: can't believe I didn't see that before. thanks @erikras

**Comment by jferrettiboke** [comment]
In case someone is interested how I solved my needs, check this [sandbox](https://codesandbox.io/s/k91x6v1113) out.

**Comment by crobinson42** [comment]
```
/*
    For use inside a react-final-form context - change a field based on another field.
    
    Example: Change everytime the other field changes
    
      <WhenFieldChanges
          field='department'
          set='subDepartment'
          to={-1}
        />
        
    Example: Only change if `shouldChangeHandler` condition is true
        
      <WhenFieldChanges
        field='department'
        set='subDepartment'
        shouldChangeHandler=(department => { 
          if (department === -1) return true
          else return false
        }}
        to={-1}
      />
 */
import React from 'react'
import PropTypes from 'prop-types'
import { Field, useFormState } from 'react-final-form'
import { OnChange } from 'react-final-form-listeners'

const WhenFieldChanges = ({ shouldChangeHandler, field, set, to }) => {
  const { values } = useFormState()

  return (
    <Field name={set} subscription={{}}>
      {(
        // No subscription. We only use Field to get to the change function
        { input: { onChange } },
      ) => (
        <OnChange name={field}>
          {() => {
            if (shouldChangeHandler && shouldChangeHandler(values[field]))
              onChange(to)
            else onChange(to)
          }}
        </OnChange>
      )}
    </Field>
  )
}

WhenFieldChanges.propTypes = {
  field: PropTypes.string.isRequired,
  set: PropTypes.string.isRequired,
  shouldChangeHandler: PropTypes.func,
  to: PropTypes.any.isRequired,
}
WhenFieldChanges.defaultProps = {}

export default WhenFieldChanges
```

**Comment by engineforce** [comment]
I think this can be solved using useField hook easily.

**Comment by dbertella** [comment]
hey @engineforce since this is a hot topic and I don't think the previous solution is very neat, can you share a solution using the hook?

**Comment by engineforce** [comment]
@dbertella, turn out the solution posted by [jferrettiboke](#issuecomment-429037041) is more declarative than mine and quite clean. You can find my solution using [FormApi.change](https://final-form.org/docs/final-form/types/FormApi#change) (not hook, my mistake) at [my sandbox](https://codesandbox.io/s/nice-moser-f5n1u).

**Comment by dbertella** [comment]
I actually found out myself how to do this using hooks and it looks very easy, maybe less polish but very neat, this is an example:
```
const FormComponent = ({handleSubmit}) => {
 const input1Field = useField('input1')
 const input2Field = useField('input1')
return  (
<form onSubmit={handleSubmit}>
  <input
    {...input1Field.input}
    onChange={(e: ChangeEvent<HTMLInputElement>) => {
        input2Field.input.onChange(e.target.value)
    }}
  />
  <input {...input21Field.input} />
</form>
)
}
```
Super easy actually and it works quite well!
what do you think about it?
(I didn't test this particular code but it should work more or less, I can make a sandbox perhaps

**Comment by sgarcialaguna** [comment]
I like crobinson42's solution quite a bit, but it does have two bugs:

1) onChange will always fire, even if shouldChangeHandler returns false.
2) values[field] assumes values is a flat object. 

I went with a patched version that also uses form.change:

```
import React from "react";
import PropTypes from "prop-types";
import { useForm, useFormState } from "react-final-form";
import { OnChange } from "react-final-form-listeners";
import get from "lodash/get";

const WhenFieldChanges = ({ shouldChangeHandler, field, set, to }) => {
  const { values } = useFormState();
  const form = useForm();

  return (
    <OnChange name={field}>
      {() => {
        if (shouldChangeHandler)
          shouldChangeHandler(get(values, field)) &&
            form.change(set, to);
        else form.change(set, to);
      }}
    </OnChange>
  );
};

WhenFieldChanges.propTypes = {
  field: PropTypes.string.isRequired,
  set: PropTypes.string.isRequired,
  shouldChangeHandler: PropTypes.func,
  to: PropTypes.any.isRequired
};
WhenFieldChanges.defaultProps = {};

export default WhenFieldChanges;
```

**Comment by jedwards1211** [comment]
@erikras I'm migrating an old codebase from `redux-form` and I was using a custom hook to get the value of a specific field and conditionally render some elements based on that.  Basically similar to the old `formValues` HoC but less tedious.  Using a declarative form rule wouldn't cut it in my case.  And using values from `FormRenderProps` isn't ideal because you can't subscribe to just one field value in `<Form>`.

I tried doing `const {input: {value}} = useField(name)` but that doesn't seem to work and probably will cause problems since it calls `registerField` without any validation etc. unlike the main `<Field>` for that name.

A lot of people would find a `useFieldValue` hook a welcome addition, I assure you

**Comment by windsome** [comment]
> > As you can see in the state of the form, "country" value is still "IE" (the previous value).
> 
> Seems like this could be handled with a [Declarative Form Rule](https://medium.com/@erikras/declarative-form-rules-c5949ea97366), no?

it solves the simple case. but not good for complex case.
if props A changed, after a calculate with B or/and C, change X, Y, Z. how to handle this?
