### ISSUE TITLE
[Question] What is the way to check label style when a checkbox is checked

### ISSUE THREAD

**Issue by qs** [final-form/react-final-form#349]
Hi,

Is there any easy way to check label style when a checkbox is checked?

For example, in this case https://codesandbox.io/s/ww40y2m595 the checkboxes are not marked as checked, so I can't use `input[type="checkbox"]:checked + label`. My current thought is to check `FormSpy` for the whole form but I wonder if there is an easier way that I can use locally with my label component.

**Comment by maciejmyslinski** [comment]
@qs checkboxes **are** marked as checked, it's just a DOM API. I can see you have a different problem, though. You use a selector that points to a label just *after* the checkbox while in the example you provided it's *before* the checkbox. That's why your CSS selector doesn't work.

**Comment by qs** [comment]
Thanks a lot for the hint! It works with `label > input[type="checkbox"]:checked`.
