### ISSUE TITLE
Example for 'Third Party Components' does not use Material ui Button  and does not work when using Button

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#35]
**Bug report**

### What is the current behavior?

Upgraded Material ui to 1.0 Beta and sing material UI button element, Does not call the function onClick.

How do I make final form with 3rd party component like Material UI ?

### What is the expected behavior?
on Button click it should show the form json

### Sandbox Link

https://codesandbox.io/s/wn5v2q3lj7

### What's your environment?

Material ui 1.0 beta

**Comment by kavink** [comment]
figured it out, and to just make ```onClick={handleSubmit}``` instead of ```onSubmit``` at form level

**Comment by kavink** [comment]
@erikras Just wanted to confirm, is this the right way to fix the issue  ?

**Comment by erikras** [comment]
That's fine. 👍
