### ISSUE TITLE
How to pass additional data to Field, usable in FormSpy and decorators

### ISSUE THREAD

**Issue by bertho-zero** [final-form/react-final-form#355]
### Are you submitting a **bug report** or a **feature request**?

Feature request, I'd like to use some props that I pass to a Field.

```jsx
<Field
  key={rule.key}
  name={rule.key}
  type="checkbox"
  entityName={entityName} // <--
  identifier={identifier} // <--
  render={( { input, meta } ) => (
    //
  )}
/>
```
or
```jsx
<Field
  key={rule.key}
  name={rule.key}
  type="checkbox"
  data={{ entityName, identifier }} // <--
  render={( { input, meta } ) => (
    //
  )}
/>
```

### What is the current behavior?

These props are ignored.

### What is the expected behavior?

It would be convenient to be able to add data to a field.

### What's your environment?

```
$ npx envinfo --system --binaries
npx : 1 installé(s) en 0.845s

  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 194.54 MB / 11.61 GB
    Container: Yes
    Shell: 5.1.1 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.12.0-20181002.1121 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm

$ yarn list --pattern final-form
yarn list v1.12.0-20181002.1121
├─ final-form-calculate@1.2.1
├─ final-form-set-field-data@1.0.1
├─ final-form@4.10.0
└─ react-final-form@3.6.7
```

**Comment by erikras** [comment]
Whatever additional props you pass to `Field` are spit out in the `FieldRenderProps`. See:

![react final form - simple example - codesandbox 2018-10-17 20-29-42](https://user-images.githubusercontent.com/4396759/47108240-76a97f80-d24b-11e8-8862-73d166e7b3c8.jpg)

This is very useful for passing additional config values to custom inputs, like date pickers.

[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nwm1mlm0n0)

**Comment by bertho-zero** [comment]
I can have them in the render but they are not in the `FormState` and therefore not accessible in a `FormSpy`?

We can use the mutator `setFieldData` but how to initialize a `Field` with data?

**Comment by erikras** [comment]
Sorry, you started this talking about "passing props to `Field`". Now I see that you are referring to actually setting the `meta.data` values **_such that they are available via `FormSpy`_**.

I swear, maintaining a form library provides insight such an amazing array of _strange_ requirements. This is so bizarre that you've inspired me to figure out how to implement this, sort of as a challenge. 

...20 minutes later...

This is as close as I can come, given that both `Form` and `FormSpy` don't really know about `meta.data` as a thing, i.e. you cannot "subscribe" to changes to it. This sets the values on the very first render of the field, but the `Form` and `FormSpy` don't know to rerender with the new data values.

[![Edit 🏁  React Final Form - Warnings](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vqz7wvjqvy)

Close enough?

**Comment by bertho-zero** [comment]
It's almost that, but the component is still not initialized with `meta.data` at the first render.

**Comment by erikras** [comment]
Yeah, I think this is a misuse of what the `meta.data` was designed for. `meta.data` is for putting arbitrary stuff in a field-only context. I think you might need to pull these values out higher in your component structure, either in `this.state` of your form component or somewhere else.

**Comment by bertho-zero** [comment]
That's what I do but it looks like a workaround.
You can attach data to a field but not from the registration of this field.

The other part of this issue concerns the decorators, we do not have access to the FormState since the decorators and we can not calculate the values according to the data.

**Comment by bertho-zero** [comment]
The data I would like to stick to my Field and be able to find everywhere is the state indeterminate of my checkboxes.

**Comment by bertho-zero** [comment]
For use `form` in a decorator:
```js
const childCheckboxDecorator = () => form => createDecorator({})(form)
```
instead of:
```js
const childCheckboxDecorator = () => createDecorator({})
```

**Comment by bertho-zero** [comment]
@erikras I have another quick question, when I use a mutator in a calculator and I use getFieldState later in the same function I do not see the change made just before? (setFieldData in my case)

Can you explain to me quickly why or send me a link? I have not found anything.
