### ISSUE TITLE
Fix material ui example

### ISSUE THREAD

**Issue by popugang** [final-form/react-final-form#363]
in example https://codesandbox.io/s/4042v50094 when i add placeholder for Textfield
```
<Field
 name="firstName"
 component={TextField}
 placeholder="first name"
 type="text"
 label="First Name"
 />
```
i see 
![image](https://user-images.githubusercontent.com/19804652/47554701-93f8e080-d912-11e8-8d25-0ae6c86e327d.png)

How to fix it ?

**Comment by popugang** [comment]
Textfield need to change inputProps to InputProps

**Comment by popugang** [comment]
@maccuaa 
see this example 
https://codesandbox.io/s/735n418n1x

**Comment by maccuaa** [comment]
@popugang ah I see now.  Every time I looked at that CodeSandbox example I never realized that the MUI components were being wrapped in a custom component.  Thanks :+1:
