### ISSUE TITLE
Backend error doesn't disappear

### ISSUE THREAD

**Issue by linashredinger** [final-form/react-final-form#38]
Hi!

### Are you submitting a **bug report** or a **feature request**?

possibly bug

### What is the current behavior?

Please use sandbox.
steps to reproduce:

1. type anything in field
2. click send => you get min length error(frontend validation) or "try" message(backend)
2a. type more then 6 letters to complete validation, send again to recieve backend message
3. erase letters until you get frontend validation message
4. type again to complete frontend validation => backend message still here

### What is the expected behavior?

i think its better to hide backend message when user start editing field

### Sandbox Link

https://codesandbox.io/s/xo33o77j7q

**Comment by erikras** [comment]
Thanks. Great reporting. Discussion about this happening on https://github.com/final-form/final-form/issues/4.
