### ISSUE TITLE
[Thoughts] focus first error

### ISSUE THREAD

**Issue by linashredinger** [final-form/react-final-form#39]
Hi again.
Maybe you have any thoughts how to make scrolling to first error message using your validation library?

**Comment by erikras** [comment]
Well, the `FormRenderProps` given to your form render function _does_ have all the form errors. Actually scrolling them into view is up to you, I'm afraid.

**Comment by linashredinger** [comment]
Yes, I already found that methods, but what event is better to stick to? Where is the best way to scroll? 
`componentWillReceiveProps` will give to much side effects, `onSumbit` won't be called when frontend validation fails, form validate function have different purposes than accessing DOM and scrolling.
maybe some hidden component events or calls?

**Comment by circlingthesun** [comment]
```js
<FormSpy
  subscription={{ submitFailed: true }}
   onChange={(v) => {
    scrollIntoView(document.querySelector('.is-invalid-input'));
  }}
/>
```

**Comment by circlingthesun** [comment]
@linashredinger have you figured out how to do this?

**Comment by linashredinger** [comment]
erikras sent me possible solution:
```
<FormSpy
  subscription={{ submitFailed: true }}
   onChange={(v) => {
    scrollIntoView(document.querySelector('.is-invalid-input'));
  }}
/>
```

**Comment by circlingthesun** [comment]
@linashredinger @erikras that works great on the initial submit, however, if the user submits again, 'submitFailed' remains false and the formspy isn't called again. Any suggestions there?

**Comment by circlingthesun** [comment]
@linashredinger: https://github.com/final-form/final-form-focus. Thanks @erikras!

**Comment by justkost** [comment]
```
<FormSpy
  subscription={{ submitFailed: true }}
  onChange={() => {
    const el = document.querySelector('.error')
    if (el) {
        el.scrollIntoView({ behavior: 'smooth' })
    }
  }}
/>
```
