### ISSUE TITLE
State of form array field is not setting to dirty 

### ISSUE THREAD

**Issue by cloneali** [final-form/react-final-form#390]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
I am using field array and on handle submit I am looking for dirty fields. To do that I am using Form.api method getFieldState(). Problem is when I try to find if an array field is dirty or not, it always sends 'false' (even you added a new value to the array). I forked the field-array example to show this behaviour.
[![Edit 🏁 React Final Form - Field Arrays](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rj7v6o9xo)

Steps to reproduce:
1. Add a customer in the list and press submit.
2. Alert box show state of the "customer" field. Check the dirty property is false.

### What is the expected behavior?
The field state of an array should get updated accordingly. 
### What's your environment?

React Final Form version: 4.0.2
Final Form version: 4.11.0, 
OS/browser: RHEL, Chrome

### Other information
@erikras, thanks for making this awesome library.

**Comment by rflmyk** [comment]
So, I'm not sure that is a bug, its happen because **customer** is a array field, but if you get `form.getState()` so you can see what fields are dirties like bellow:

```
{
  "dirty": true,
  "dirtySinceLastSubmit": false,
  "errors": {},
  "hasSubmitErrors": false,
  "hasValidationErrors": false,
  "invalid": false,
  "pristine": false,
  "submitting": true,
  "submitFailed": false,
  "submitSucceeded": false,
  "valid": true,
  "validating": false,
  "values": {
    "customers": [
      {
        "firstName": "Foo",
        "lastName": "Bah"
      },
      null,
      {
        "firstName": "bah",
        "lastName": "Foo"
      }
    ]
  },
  "dirtyFields": {
    "customers[0].firstName": true,
    "customers[0].lastName": true,
    "customers[2].firstName": true,
    "customers[2].lastName": true
  },
  "touched": {
    "company": false,
    "customers": false,
    "customers[0].firstName": true,
    "customers[0].lastName": true,
    "customers[1].firstName": false,
    "customers[1].lastName": false,
    "customers[2].firstName": true,
    "customers[2].lastName": true
  },
  "visited": {
    "company": false,
    "customers": false,
    "customers[0].firstName": true,
    "customers[0].lastName": true,
    "customers[1].firstName": false,
    "customers[1].lastName": false,
    "customers[2].firstName": true,
    "customers[2].lastName": true
  }
}
```

**Comment by cloneali** [comment]
@rflmyk, I think array field is also a field and have states so the array field should give its right state when needed. By saying that I think we can use isEqual prop. See, https://github.com/final-form/react-final-form-arrays#isequal-allpreviousvalues-arrayany-allnewvalues-arrayany--boolean

I am closing this issue.
