### ISSUE TITLE
Can not set parse or format to null with Flow

### ISSUE THREAD

**Issue by 11bit** [final-form/react-final-form#400]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

Flow gives an error for form fields with parse or format set to `null`
`Cannot create Field element because:
 • null [1] is incompatible with function type [2] in property parse.`

### What is the expected behavior?

No errors

### What's your environment?

"react-final-form": "4.0.2",
"final-form": "4.11.0",
"flow-bin": "0.84",

### Other information

Probably the fix is to slightly change type defs (it works in my project, but it has only one form so I am not sure about possible? side effects) 
```
  format?: ((value: any, name: string) => any) | null,
  parse?: ((value: any, name: string) => any) | null,
```

**Comment by erikras** [comment]
Published fix in [`v6.0.0`](https://github.com/final-form/react-final-form/releases/tag/v6.0.0).
