### ISSUE TITLE
Form validation in old browsers

### ISSUE THREAD

**Issue by omidnikrah** [final-form/react-final-form#417]
Hi, I'm using `react-final-form` with `core-js` polyfill but in old browsers (like IE) validation not working!!
You can test the following codesandbox. Form validation not working in old browsers.
Is there any solution?
https://codesandbox.io/s/9y9om95lyp

**Comment by crobinson42** [comment]
I'm also dealing with this in react-native which i'm using `core-js` also - @erikras any ideas?

**Comment by crobinson42** [comment]
Nevermind - I spoke too soon.
