### ISSUE TITLE
Conditional Form From a SELECT menu

### ISSUE THREAD

**Issue by christianlopez1965** [final-form/react-final-form#422]

**Comment by christianlopez1965** [comment]
Hi. I'm trying to set up a condition where another field is filled depending on the answer selected from a drop down menu. E.g., I select the value "Website Problems" in the field "issues", it then populates the field "recipient" with the value "ITS@email.com" as a hidden field.

I'll need both values to complete a triggered send. TIA

**Comment by rflmyk** [comment]
Hi! Try put your code on sandbox to us help you https://codesandbox.io/s/new

**Comment by christianlopez1965** [comment]
I'm going to close this request. I was trying to manual do this function in Salesforce but realized the system isn't really set up to accommodate. I found the function in JotForm. Thanks.
