### ISSUE TITLE
`useField()` hook

### ISSUE THREAD

**Issue by jamesknelson** [final-form/react-final-form#432]
### Feature Request

It'd be nice to have a `useField()` hook for the existing react-final-form. This would give basically the same performance as `<Field>`, but with data returned from the hook instead of passed to the render prop.

```js
useField(props: FieldProps): FieldRenderProps
```

The idea would be to get the form store via context, then subscribe to it within a `useEffect()`, and update a `useState()` each time it changes. Basically, implementation would look exactly like the hooks version of `<Field>`.

This would allow for fields to be created without the render prop, which would be nice when creating styled field components. For example:

```jsx
function Field(props)
  let { input, meta } = useField(props)
  return (
    <StyldeField>
      <StyledLabel>Bio</StyledLabel>
      <StyledTextarea {...input} />
      {meta.touched && meta.error && <StyledError>{meta.error}</StyledError>}
    </StyledField>
  )
)
```

And the corresponding `<Field>` based example from the README:

```jsx

function StyledField(props) {
  return (
    <Field
      {...props}
      render={({ input, meta }) => (
        <StyledFieldWrapper>
          <StyledLabel>Bio</StyledLabel>
          <StyledTextarea {...input} />
          {meta.touched && meta.error && <StyledError>{meta.error}</StyledError>}
        </StyledFieldWrapper>
      )}
    />
  )
}
```

**Comment by Kaltsoon** [comment]
Is this somehow different to [react-final-form-hooks](https://github.com/final-form/react-final-form-hooks)?

**Comment by Noitidart** [comment]
Thanks for sharing that @Kaltsoon I had no idea final form had hooks support yet! Super cool!

**Comment by erikras** [comment]
Thanks for this issue, @jamesknelson. It's very helpful to have other people attack a problem you've attempted to solve and to evaluate the differences.

So yes, RFFH is the package that uses hooks to use FF. What Render Props™ give you that hooks cannot – and never will be able to ([somewhat validated](https://twitter.com/sophiebits/status/1055701995355430912)) – is the ability to let your components (e.g. `Field`) control when they rerender. With hooks, if you are using `useField()`, your entire form _must_ rerender on every keypress, so the whole "optimization through subscriptions" architecture of FF is thrown to the wind. The good news is, however, that 96% of forms don't need that level of optimizations, so hooks are great.

The most amazing thing about the hooks announcement with relation to Final Form is the validation of keeping form state in a separate container, outside of React. Within hours of the hooks announcement, [I was able to whip up a version of RFF with almost no effort](https://twitter.com/erikras/status/1055840024271511553).

**Comment by wtgtybhertgeghgtwtg** [comment]
> With hooks, if you are using useField(), your entire form must rerender on every keypress

I played around with a version of `useField` using the current context setup of `react-final-form` and haven't found that to be the case.  It isn't very polished, but is there something I'm missing?

**Comment by jamesknelson** [comment]
I’m also curious why useField would need to re-render in every update. Shouldn’t it be possible to selectively render fields by checking whether they should be rendered from within the notification handler, as opposed to within shouldCmponentUpdate?

The idea here wouldn’t be to create a completely hook-based version - just to add a single hook to the existing version, which accesses final form via context, like @wtgtybhertgeghgtwtg has done.
