### ISSUE TITLE
Add support to value lifecycle

### ISSUE THREAD

**Issue by gsantiago** [final-form/react-final-form#45]
The [value lifecycle](https://redux-form.com/7.2.0/docs/valuelifecycle.md/) is one of the best features from redux-form. Will react-final-form support something like that?

**Comment by erikras** [comment]
Hmm... I was hoping to not need to implement that, instead laying the burden of formatting and parsing on the code that initializes and submits the form. Can you make an argument for why you think you need it?

**Comment by dispix** [comment]
I agree with @gsantiago, the value lifecycle was a really simple and nice way to separate the data from the display. I think that there are quite a lot of cases where the value stored in the form state and the value passed to the "dumb" component need to be handled differently.

**Comment by erikras** [comment]
Published fix in [`v2.1.0`](https://github.com/final-form/react-final-form/releases/tag/v2.1.0).
