### ISSUE TITLE
Not passing name gives object value

### ISSUE THREAD

**Issue by nabati** [final-form/react-final-form#450]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

If you pass `undefined` to the `Field` `name` prop, you get an object as a value instead of a string. Would be good if it threw an error or a warning instead.

https://codesandbox.io/s/l7xr7qrk2l?fontsize=14

**Comment by erikras** [comment]
Published fix in [`v6.5.0`](https://github.com/final-form/react-final-form/releases/tag/v6.5.0).
