### ISSUE TITLE
Reset a form programmatically

### ISSUE THREAD

**Issue by dbertella** [final-form/react-final-form#46]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### Other information

I might missing something, but what is the correct approach to reset a form after successful submission? Without having a reset button of course.
I couldn't see anything about this in the documentation.
I can inject new empty `initialValues` from props maybe, but it doesn't seem very clean.

**Comment by davidhenley** [comment]
@erikras I'm trying to reset the form after resolving promise and this is not working:

Code:
```
import React from 'react';
import { Form as RFForm, Field } from 'react-final-form';
import { validate } from './options';
import * as Form from '../helpers';
import { typeOptions } from './options';
import { Form as SUIForm } from 'semantic-ui-react';

const onSubmit = values => {
  return new Promise(resolve => {
    setTimeout(resolve, 3000);
  });
};

const CreditDebitForm = props => (
  <RFForm
    onSubmit={onSubmit}
    validate={validate}
    render={({ handleSubmit, values, reset, pristine, invalid, submitting, submitFailed, submitSucceeded }) => (
      <Form.Wrapper onSubmit={event => {
        handleSubmit(event).then(reset);
      }} submitting={submitting}>
        <Form.Header text="Credit / Debit Form" />

        <Form.Section top text="Manager Info">
          <Field name="manager" label="Manager" component={Form.Manager} />
        </Form.Section>

        <Form.Section text="Customer Info">
          <Field name="type" label="Request Type" options={typeOptions} component={Form.Select} />
          <Form.Group>
            <Field name="customer" label="Customer Name" component={Form.Customer} />
            <Field name="invoice" label="Invoice #" type="number" component={Form.Input} />
          </Form.Group>
        </Form.Section>

        <Form.Section text="Product Info">
          <Form.Group>
            <Field name="product" label="Product Name" component={Form.Product} />
            <Field name="cases" label="Cases" type="number" component={Form.Input} />
            <Field name="bottles" label="Bottles" type="number" component={Form.Input} />
          </Form.Group>
        </Form.Section>

        <Form.Section text="Amount Info">
          <Form.Group>
            <Field name="billed" label="Case Discount Billed" type="number" step="0.01" component={Form.Input} />
            <Field name="correct" label="Correct Case Discount" type="number" step="0.01" component={Form.Input} />
            <SUIForm.Input label="Amount Owed/Due" value={((values.correct || 0) - (values.billed || 0)).toFixed(2)} />
          </Form.Group>

          <Field name="notes" label="Notes" placeholder="Provide any additional info here" component={Form.TextArea} />
        </Form.Section>

        <Form.Message submitSucceeded={submitSucceeded} submitFailed={submitFailed} />

        <Form.Submit disabled={pristine || invalid || submitting} />
      </Form.Wrapper>
    )}
  />
)
```
export default CreditDebitForm;

**Comment by erikras** [comment]
See https://github.com/final-form/react-final-form/issues/21#issuecomment-349024729 and https://github.com/final-form/react-final-form/issues/21#issuecomment-350285566.

**Comment by davidhenley** [comment]
I checked those out. This is not closed. I am on the latest version.

**Comment by erikras** [comment]
Hmm... You do see it working in the sandbox, right? I wonder what is different about your setup? Your code looks just fine.

**Comment by davidhenley** [comment]
@erikras OK. When you submitted the change you said to upgrade to 1.1.0. I did that, once I upgraded to 1.3.0 for f-f and 1.2.0 for r-f-f it started working. Sorry, that was frustrating. We are all good now with the same code. Thanks for your hard work!!

**Comment by erikras** [comment]
> I can inject new empty initialValues from props maybe, but it doesn't seem very clean.

@dbertella You can also call `initialize()` instead of `reset()` in the same way.

**Comment by dbertella** [comment]
Great sorry I didn't see that, I probably looked into the wrong issues instead, I have just a problem, I'm using redux saga and the form submission is just a synchronous action, so I don't think it will work unfortunately

**Comment by erikras** [comment]
@dbertella Let me restate your request to make sure I understand. You want:
```jsx
props.reinitialized === false // form might have been initialized, but has never been RE-initialized
props.reinitialized === true // form has had `reset()` or `initialized()` called on it at least once
```
?

**Comment by dbertella** [comment]
My problem is that I need to reset the form from outside the render prop, something that I could do with an action creator in redux form for example.
My onSubmit unfortunately is synchronous since I'm using saga so i can't use the method you mentioned.

What I'm doing as a work around is: according to a custom flag I'm setting the initialValues causing the form to re-render to the empty state but it works just the first time.

**Comment by erikras** [comment]
@dbertella Everything about this [How to submit from outside?](https://github.com/final-form/react-final-form/blob/master/docs/faq.md#how-can-i-trigger-a-submit-from-outside-my-form) FAQ I just wrote could equally apply to `reset()`.

**Comment by dbertella** [comment]
Sweet I like the the dead drop concept but I'm not sure about how to
implement the reset, I need to try it :-). Anyway the closure or a hidden
reset button triggered can help I think! Thank you very much for all the
effort!

On Dec 13, 2017 21:11, "Erik Rasmussen" <notifications@github.com> wrote:

@dbertella <https://github.com/dbertella> Everything about this How to
submit from outside?
<https://github.com/final-form/react-final-form/blob/master/docs/faq.md#how-can-i-trigger-a-submit-from-outside-my-form>
FAQ I just wrote could equally apply to reset().

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/final-form/react-final-form/issues/46#issuecomment-351526245>,
or mute the thread

**Comment by dbertella** [comment]
Clojure did the job, I tried the event first but it didn't work with reset, I guess it's not handled via a custom event, I was thinking at something like this `document.getElementById('myForm').dispatchEvent(new Event('reset'))`

Anyway here is my code, it feels a little hacky but it does the job!
```
let resetForm

...
  componentWillReceiveProps(nextProps: Props) {
    if (!this.props.success && nextProps.success) {
      resetForm()
    }
  }

...
render={({ handleSubmit, reset, values }) => {
            resetForm = reset
            return (
                <form onSubmit={handleSubmit}>
                ....
                </form>
            )
        }
```

**Comment by hitunes** [comment]
import { Form } from 'react-final-form';
 <Form  component={yourFormComponent} />
const yourFormComponent = props => {
  const {
    form,
    pristine,
    submitting,
    handleSubmit 
} = props;
  return (
    <form
      onSubmit={event => {
        handleSubmit(event).then(form.reset);
      }}
    >
{children}
</form>
this works for me.

**Comment by hitunes** [comment]
`import { Form } from 'react-final-form';

const yourFormComponent = props => { const { form, pristine, submitting, handleSubmit } = props; return ( { handleSubmit(event).then(form.reset); }} > {children} this works for me.`

**Comment by khaoptimist97** [comment]
Can we use the reset function outside the Form? For the sake of calling it in particular condition.

**Comment by khaoptimist97** [comment]
@dbertella Thank you so much

**Comment by rendomnet** [comment]
Anyone react hooks way?

**Comment by JackHowa** [comment]
Have a similar question as @rendomnet. I'm using recompose. Any advice?
