### ISSUE TITLE
Submission errors on nested fields

### ISSUE THREAD

**Issue by doneumark** [final-form/react-final-form#466]
Hi, I noticed that submission errors are not passed to nested fields (meaning, that if the field is nested: "someField.someNestedField"), the META doesn't get any errors.
Is there any way to pass those errors to those nested fields?

**Comment by erikras** [comment]
The errors should be the same "shape" as the values.

```js
function validate(values) {
  const errors = { someField: {} }
  if(values.someField && values.someField.someNestedField < 5) {
    errors.someField.someNestedField = 'Should be at least five'
  }
  return errors
}
```
