### ISSUE TITLE
Field type prop not injected to input

### ISSUE THREAD

**Issue by doguh** [final-form/react-final-form#471]
Hi,

first time using this lib, seems really nice but I encountered an issue after 5 minutes of testing with the latest build (5.0.0 and 5.0.1 on npm)

### Are you submitting a **bug report** or a **feature request**?

a bug

### What is the current behavior?

the `type` prop of the `Field` component is not injected into the `input` 

it seems to only work with `radio` and `checkbox` types but not with `password`

`<Field type="password" />`  results in `<input />`

### What is the expected behavior?

`<Field type="password" />` should result in `<input type="password" />`

### Sandbox Link

Try to change any `type="text"` into `type="password"` in this example
https://codesandbox.io/s/6y4ny3xjr

### What's your environment?

Windows 10, react-final-form 5.0.1, node 10.14

### Other information

For your information, it works perfectly with react-final-form 4.1.0

**Comment by erikras** [comment]
Aha! I forgot about the other types. 🤦‍♂️

**Comment by erikras** [comment]
Published fix in [`v5.0.2`](https://github.com/final-form/react-final-form/releases/tag/v5.0.2).
