### ISSUE TITLE
Add getValue to the public API

### ISSUE THREAD

**Issue by ThiefMaster** [final-form/react-final-form#473]
This would be convenient for custom adapter components if they want to provide an `onChange(value)` prop that gets called when the value of the field changes.

With that I could do something like this:

```js
const handleChange = arg => {
    // arg is usually an event, but for custom
    // fields it might also be the value itself
    input.onChange(arg);
    if (props.onChange) {
        props.onChange(getValue(arg));
    }
};
```

and then pass `onChange={handleChange}` to the component that's representing my actual form field (regardless of whether it's an `<input>` or something custom which calls `onChange` with a value instead of an event)

**Comment by ThiefMaster** [comment]
Actually, an `onValueChange` prop on the `Field` that receives the value after having been processed by the `parse` function would probably be even better; but from what I can see this doesn't exist so far. I can of course define another Field, subscribe to its value, and abuse its render prop for this, but then it runs on every re-render and not just when the value actually changes.

**Comment by erikras** [comment]
That's sort of the functionality provided by [`<OnChange/>`](https://github.com/final-form/react-final-form-listeners#usage). Is that sufficient for your needs?

**Comment by ThiefMaster** [comment]
Yes, that looks like a good option!
