### ISSUE TITLE
Using format prop on fields shows a warning in the console

### ISSUE THREAD

**Issue by jwld** [final-form/react-final-form#475]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

When using `format` on a field, the console logs a warning.

### What is the expected behavior?

No warnings.

### Sandbox Link

Typing in the username field causes the warning:
https://codesandbox.io/s/10rzowm323

### What's your environment?

browser = chrome
final-form = 4.12.0
OS = Mojave 10.14.4
react-final-form = 4.1.0

**Comment by Andarist** [comment]
In this case your format has to return "initial" value if you dont provide it in initialValues. See https://codesandbox.io/s/react-final-form-parse-and-format-0l1oj

**Comment by jwld** [comment]
Thanks! That sandbox I linked to is from the main README - might be good to get that sandbox updated so that it's not throwing that error.

**Comment by erikras** [comment]
Sandbox updated. Thanks to both of you!
