### ISSUE TITLE
useFormState has painful typescript return type

### ISSUE THREAD

**Issue by stramel** [final-form/react-final-form#476]
### What is the current behavior?
To be able to destructure props out of `useFormState` I must cast it `as FormState` since the existing can be `void | FormState`.

### What is the expected behavior?
I should not have to cast it as FormState.
`const { submitError, submitFailed, submitting } = useFormState()` should work.

### What's your environment?

`react-final-form` v5.0.2

**Comment by Andarist** [comment]
I've prepared a fix for this in #482

**Comment by erikras** [comment]
Published fix in [`v5.1.1`](https://github.com/final-form/react-final-form/releases/tag/v5.1.1).
