### ISSUE TITLE
`Submitting` not getting reset after submit

### ISSUE THREAD

**Issue by michaltk** [final-form/react-final-form#487]
### What is the current behavior?
When  subscribed to `submitting` state, `submitting` never gets updated back to `false` even after submitting.
This seems to work fine in v4 and only is an issue in v5. 

### What is the expected behavior?
After submit, `submitting` state should be `false` again.

### Sandbox Link
[See Demo](https://codesandbox.io/s/react-final-form-simple-example-7slu8)

### What's your environment?
React Final Form - 5.1.0
Final Form - 4.13.0

**Comment by erikras** [comment]
Published fix in [`v6.0.0`](https://github.com/final-form/react-final-form/releases/tag/v6.0.0).
