### ISSUE TITLE
Why am I using yarn to install react-final-form The latest version is 5.0.1?

### ISSUE THREAD

**Issue by Gzbox** [final-form/react-final-form#489]
Why am I using yarn  to install react-final-form The latest version is 5.0.1?

**Comment by erikras** [comment]
Not sure what the question is. In theory, you can use either `yarn` or `npm` with no problem.

**Comment by Gzbox** [comment]
> 不确定问题是什么。从理论上讲，你可以使用`yarn`或`npm`没有问题。

![image](https://user-images.githubusercontent.com/21010051/58229475-6bc84780-7d64-11e9-819b-bdff79185416.png)

Thank you for your answer
I don't know what the situation is, I don't know how to find the reason! ! !
