### ISSUE TITLE
withReactFinalForm is missing in latest build

### ISSUE THREAD

**Issue by TrejGun** [final-form/react-final-form#490]
this function exists in 4.1.0 but not in 5.1.0
it is used by react-final-form-arrays

**Comment by TrejGun** [comment]
was removed in https://github.com/final-form/react-final-form/commit/ffd2003a3e0ec521d3e764623b780bb9e4b77aa9

**Comment by erikras** [comment]
It was listed as a [breaking change](https://github.com/final-form/react-final-form/releases/tag/v5.0.0). There's a simple fix there, too.

**Comment by TrejGun** [comment]
do you suggest to fork react-final-form-arrays and fix it? or do you have better plan?
