### ISSUE TITLE
Form doesn't rerender when going back from dirty state to pristine state

### ISSUE THREAD

**Issue by smashercosmo** [final-form/react-final-form#492]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
Form doesn't rerender when going back from dirty state to pristine state

### What is the expected behavior?
Form should rerender when going back from dirty state to pristine state

### Sandbox Link
https://codesandbox.io/s/r9e0k

1. Change value from 'bla' to some other value
2. You'll see 'Is pristine: false'
3. Change value back to 'bla'
4. You'll see that 'Is pristine' is still false
5. Click 'get state' button
6. In the form state in console you'll see that pristine is true

### Other information
Works fine in react-final-form@4.1.0

**Comment by jsrhodes15** [comment]
FWIW - We are seeing this also. Workaround at the moment is to wrap the thing that needs to know `pristine || dirty` in a FormSpy. I know this isn't ideal, but it does work.

**Comment by erikras** [comment]
Published fix in [`v6.0.0`](https://github.com/final-form/react-final-form/releases/tag/v6.0.0).

**Comment by smashercosmo** [comment]
Thank you
