### ISSUE TITLE
[Feature request] Support for TypeScript

### ISSUE THREAD

**Issue by mark-raymond** [final-form/react-final-form#50]
It would be great to be able to use final-form and react-final-form from TypeScript fully typed. Hopefully this would be fairly easy, as you already have Flow types. I'm not aware of any automated conversion, though.

**Comment by erikras** [comment]
There must be someone who's type system bilingual that could do this pretty easily...? I wouldn't know how to test that it's working... 😢

**Comment by mark-raymond** [comment]
Well, I'm not familiar with Flow, but I've had a go at translating the typings for `final-form` here: https://github.com/final-form/final-form/pull/30. `react-final-form` is trickier as TypeScript doesn't have a literal translation of Flow's `*` in typings, I haven't worked out what that should be yet.

**Comment by erikras** [comment]
Published fix in [`v1.2.1`](https://github.com/final-form/react-final-form/releases/tag/v1.2.1).

**Comment by mark-raymond** [comment]
So, I've just actually tried to use the TypeScript typings I wrote, and discovered two issues:

- I forgot to add a `"typings"` entry to package.json. Easily solved.
- The typings for `react-final-form` reference something called `Api` in `final-form`, but that doesn't exist in `final-form`, only something called `FormApi`. This is present in the Flow typings too. I'm not sure what to do about this - are the Flow typings incorrect too?

**Comment by erikras** [comment]
Yes. Should be `FormApi`. It was originally called `Api`, but it got renamed. PR again?

**Comment by mark-raymond** [comment]
Will do :smiley:

**Comment by aodinok** [comment]
@mark-raymond  I'm getting
```
ts] JSX element type 'Component<FieldProps, ComponentState>' is not a constructor function for JSX elements.
```
When trying to use Form or Field components. Is this only me or this is known issue?

```
[ts]
JSX element type 'Component<FormProps, ComponentState>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): ReactNode; (): false | Element | null; }'.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.
```
