### ISSUE TITLE
Flow types missing

### ISSUE THREAD

**Issue by tpbowden** [final-form/react-final-form#500]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

```javascript

import { type FormRenderProps } from "react-final-form"

```

causes the following error:

```
Cannot import FormRenderProps because there is no FormRenderProps export in react-final-form.
```

### What is the expected behavior?

The type should be imported

### What's your environment?

```
react-final-form@6.0.0
flow@0.98.1
```

**Comment by eugene-stativka** [comment]
The same issue with other types like `FieldRenderProps`. Something went wrong [here](https://github.com/final-form/react-final-form/commit/ffd2003a3e0ec521d3e764623b780bb9e4b77aa9#diff-111f8503f86c1b55a6ca92cb33073fd1L5)

**Comment by erikras** [comment]
Published fix in [`v6.0.1`](https://github.com/final-form/react-final-form/releases/tag/v6.0.1).

**Comment by erikras** [comment]
Your comment helped tremendously, @eugene-stativka! ❤️

**Comment by Dema** [comment]
I'm not sure that it is fixed yet. As I understand, rollup's flow plugin was removed in commit that Eugene mentioned. I have 6.3.0 installed and there's no .js.flow files with types. Only typescript ones
