### ISSUE TITLE
How to validate one Password field with another with using pristine, dirty and touched properties and using OnChange and Onblur events?

### ISSUE THREAD

**Issue by SwapneelA** [final-form/react-final-form#509]
### Are you submitting a **bug report** or a **feature request**?

feature

### What is the current behavior?
Currently I tried record level validation, wherein I am able to compare password and confirm password values using `values` object but I am not able to check whether the field is touched or not? Also not sure how to trigger the validation using onchange and onblur event https://codesandbox.io/s/yk1zx56y5j

### What is the expected behavior?
Password and Confirm Password field should be validated against each other. If they do not match it should give error message below any of the Password field. The validation should not kick in until both the fields are touched.

### Sandbox Link

I was trying with https://codesandbox.io/s/yk1zx56y5j

**Comment by erikras** [comment]
I think you're thinking about it the wrong way. If `values.password !== values.confirm`, `errors.confirm` should have an error. The `touched` and `dirty` stuff doesn't matter in the validation function.

`touched` and `dirty` determine how you _display_ the errors.

> Also not sure how to trigger the validation using `onchange` and `onblur` event

React Final Form runs validation _on every change_. You don't need to worry with "triggering" validation. Notice how the "Must match" error goes away the instant the values match.

[![Edit 🏁 React Final Form - Synchronous Record-Level Validation Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yk1zx56y5j?fontsize=14)

Hope that clears things up.

**Comment by SwapneelA** [comment]
I want to start match validation after the user touches both the password fields. For example, when user types 'test' in the password field and then goes to the second field confirm and types 'te' and then move out from that field so immediately an error message should be shown. Now the user has to go to one of the fields and try to correct the text to match the other one after which the error should be removed.

Initially, validation should start after both fields are touched and later on it should run on every change event.
Note: I am assuming touch becomes true when focus changes from that input element.

**Comment by SwapneelA** [comment]
If one field is dirty and second is pristine, validation should not run. Once both fields are dirty validation should kick in.

**Comment by erikras** [comment]
Did you see how my code, in the sandbox, won't check until the `confirm` is truthy? It's not about the validation "not run[ning]", it's about the error not being displayed. The validation giving an error is also what prevents submission. When submission fails, all fields are marked as "touched", best used as a flag of when to show validation errors.

**Comment by SwapneelA** [comment]
I got your point, but my use case is a bit different If you can let me know how can I access any Field's meta inside a form that would be great.

**Comment by erikras** [comment]
I guess it depends on what you mean by "inside a form". Inside the form's render function, you can use the `useField` hook to get any field's meta data. From inside the form's validation function, not so much...
