### ISSUE TITLE
Infinite Loop when isEqual is updated

### ISSUE THREAD

**Issue by Titozzz** [final-form/react-final-form#517]
### **Bug report** 

When using \<Field>, if isEqual changes, form re-renders, leading to an infinite loop when creating comparator on the fly. eg:

example: 
```
            <Field
              // You can comment isEqual to stop the loop
			  isEqual={() => console.log("infinite power") || false}
              name="lastName"
              component="input"
              type="text"
              placeholder="Last Name"
            />
```

The behavior changed with the 5.0 release (you can see in the codesandbox below that it does not loop below 5.0)

### What is the current behavior?

Infinite loop when comparator function is defined on render.

### What is the expected behavior?

I'm not sure if this is intended or not. In my case, I can define my function before so it's fine but I'd rather still report the change as it leads to a bug in my app and I could not see it in the changelog.

### Sandbox Link

https://codesandbox.io/embed/react-final-form-simple-example-ed7ic

### What's your environment?

Loop need RFF >= 5.0

### Unrelated

Thanks for your hard work on this awesome library 🚀 !

**Comment by erikras** [comment]
Published fix in [`v6.3.1`](https://github.com/final-form/react-final-form/releases/tag/v6.3.1).
