### ISSUE TITLE
Leverage JSX generics for Form and Field

### ISSUE THREAD

**Issue by smashercosmo** [final-form/react-final-form#521]
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?

Last release improved experience for TypeScript and Flow users. Now we can have typed Forms and Fields. But it can be improved even more at least for TS users if we leverage JSX generics which are supported by TypeScript. So instead of
```
const { Form } = withTypes<Types>()
<Form>...</Form>
```
we will simply
```
<Form<Types>>...</Form>
```

WDYT?

**Comment by erikras** [comment]
1. Anything like this for Flow?
2. I'd definitely consider a PR for this.

**Comment by smashercosmo** [comment]
Unfortunately Flow hasn't implemented support for JSX generics yet https://github.com/facebook/flow/issues/7672

**Comment by smashercosmo** [comment]
Closed via https://github.com/final-form/react-final-form/pull/522
