### ISSUE TITLE
destroy on unregister breaks initial values 

### ISSUE THREAD

**Issue by zmitry** [final-form/react-final-form#523]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
I set initial value and destroyOnUnregister, when I type to first input, value resets, when I type to second input, value also resets.
Steps to reproduce
set intialValues
set destroyOnUnregister
try to type to field.
You can observe that field value resets to empty state. You should have this behavior at all.

### What is the expected behavior?

it just resets on unregister
### Sandbox Link
https://stackblitz.com/edit/final-form-issue
https://www.loom.com/share/2147185bb138468290bd8d60d52aac7d

**Comment by zmitry** [comment]
@erikras

**Comment by erikras** [comment]
The `Condition` component is a red herring here. Just focusing on a field with an initial value when `destroyOnUnregister` is `true` will clear the field. The good news is that I've got a test that replicates it, so this bug shouldn't take long to squash.

**Comment by zmitry** [comment]
@erikras kind of, but you if you will remove condition component you will have issue with missing initial values in focus.

**Comment by zmitry** [comment]
But I guess this issue should be fixed by your pr.
