### ISSUE TITLE
Keys with empty values get deleted after edit, even with set defaultValues

### ISSUE THREAD

**Issue by valcho** [final-form/react-final-form#527]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
I have two input fields that start with empty strings as default values. Let's say the fields are edited and then reverted back to default (empty string). Now, the values object is missing that key.

### What is the expected behavior?
I expect there to be a way for the values to remain empty. 

### Sandbox Link
[Codesandbox Demo](https://codesandbox.io/s/react-final-form-key-with-empty-string-bug-h7ptm)

### What's your environment?

    "react-final-form": @6.1.0,
    "react-dom": @16.9.0,
    "react": @16.9.0,
    "final-form": @4.14.1

**Comment by stanimirsellercloud** [comment]
Using an `identity` `parse` function appears to be a good way to mitigate this. See https://github.com/final-form/react-final-form/issues/130#issuecomment-425482365
