### ISSUE TITLE
Example request for nested objects

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#53]
following up on #25 

Would be great to have an example, like the field arrays to add/remove objects along with array.

**Comment by erikras** [comment]
Like this?

[![Edit 🏁  React Final Form - Deep Fields](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8z5jm6x80)

**Comment by kavink** [comment]
@erikras Not really, I am able to do that. Basically same way in Field array there are buttons to add/remove customers. Same way in this without an array.

In the example you have, You have 
```
    <div>
      <label>{label} City</label>
      <Field
        name={`${name}.city`}
        component="input"
        placeholder={`${label} City`}
      />
    </div>
```

Where the `city` keyword is in your code and user enters just the value value, I want to user to even provide `city` keyword as a value for text box, i.e. in your example there is 1 text box, for value, I wold have 2 test box.

So user click (+) button, gets 2 text box to add the key: city, value:San Francisco

**Comment by erikras** [comment]
You want the user to enter both the key and the value?

That might require your own state management solution. Either that or using arrays of `{key:string, value:string}`.

**Comment by kavink** [comment]
@erikras Yes both key and value. Maybe can use array,  But maybe on submit i change structure from array to object ?

**Comment by erikras** [comment]
> But maybe on submit i change structure from array to object ?

👍

**Comment by kavink** [comment]
@erikras Thanks will go down that route then. Was trying to create something like a JSON editor where user can update/add/remove JSON objects or arrays. Will do some hack for objects, Arrays work just fine.

**Comment by kavink** [comment]
@erikras If I need to Load and initialize the data in array forms, Do I need to do anything special ? Also are there any api's in final-form I can use for transformation of data while loading or when submitting ?

**Comment by erikras** [comment]
No, just provide the `initialValues` as an object with an array inside it. At the moment, for `FieldArray` to work, you must provide a named key. i.e. you can't have `initialValues: [ {key, value}, {key, value} ]`, you must do `initialValues: { myValues: [ {key, value}, {key, value} ] }`. Make sense?

**Comment by kavink** [comment]
@erikras, kind of makes sense, But im sure as final-form gains audience,  A real example working example to refer from Readme will help everyone a lot 👍 ..Thanks for great work.. I am impressed with ease of use of Final form.

**Comment by erikras** [comment]
It's not that complicated. (if I'm understanding your question) Here:

[![Edit 🏁 React Final Form - Field Arrays](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rm7kp3064n)
