### ISSUE TITLE
mutators, like setFieldData, do not update in useEffect on first render

### ISSUE THREAD

**Issue by skvale** [final-form/react-final-form#538]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

When using the setFieldData mutator and the Form has more than 1 field child, `setFieldData` does not find the field id in fieldData on the initial call from `useEffect`.
It doesn't exist in fieldData.  
When there is only one field, it works as expected.  

After the initial render, `setFieldData` can find the field in fieldState. 
It's like final-form isn't registering the fields before the first render by the time it passes fieldState to the mutator function.

### What is the expected behavior?

I would expect `setFieldData` to find the field in fieldState in the first render when there is more than one field and update the meta.data property to cause a re-render.  
Especially if this is the behavior when there is one field.

### Sandbox Link

https://codesandbox.io/s/react-final-form-simple-example-60uul

### What's your environment?

```
react-final-form          6.2.1
final-form                4.15.0
final-form-set-field-data 1.0.2
react                     16.8.6
react-dom                 16.8.6
```

**Comment by skvale** [comment]
Going to dig into this more and reopen if I find out more

**Comment by manzoorwanijk** [comment]
+1

**Comment by nicolad** [comment]
:100:

**Comment by manzoorwanijk** [comment]
Still facing this issue. Any update?
