### ISSUE TITLE
Property 'pristine' does not exist on type 'FormRenderProps'

### ISSUE THREAD

**Issue by KristopherWagner** [final-form/react-final-form#542]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

`Property 'pristine' does not exist on type 'FormRenderProps'.` when rendering with TypeScript `^3.5.2` and React `^16.8.6`

### What is the expected behavior?

`pristine` is used in the examples but does not appear in FormRenderProps

### Sandbox Link

![image](https://user-images.githubusercontent.com/20402962/59770939-d80c6d00-9276-11e9-8bdf-0e95e4eb4888.png)

### What's your environment?

```json
{
  "react-final-form": "^4.1.0",
  "type-script": "^3.5.2",
  "react": "^16.8.6",
  "react-scripts": "^3.0.1"
}
```

**Comment by xiaoyuze88** [comment]
same issue.

**Comment by yanisurbis** [comment]
same issue.

**Comment by erikras** [comment]
Hmm... You didn't specify the version of `final-form` you're using, and that's the important bit of information, but it certainly seems to be fine with the latest versions ([see line 48](https://codesandbox.io/s/strongly-typed-form-values-with-react-final-form-26jkd)).

**Comment by KristopherWagner** [comment]
Thanks updating from `4.15.0` to `4.16.1` fixed this issue

![image](https://user-images.githubusercontent.com/20402962/61052588-bc017480-a3b9-11e9-88fc-aff757dc280d.png)

**Comment by erikras** [comment]
Great!

Plus the latest version(s) of RFF have some [fun Typescript features](https://github.com/final-form/react-final-form/releases/tag/v6.2.0).
