### ISSUE TITLE
`multiple` is not passed down to custom components

### ISSUE THREAD

**Issue by ThiefMaster** [final-form/react-final-form#544]
I'm using the Dropdown from semantic-ui-react. Just like a normal multiselect dropdown it requires the `multiple` prop to enable multiselect mode.

However, the `Field` component passes `multiple` only to `useField()` but not along with the other props to the component. For `<select multiple>` this is handled correctly in `useField()` (`input.multiple = true`), but if `component` is something custom, then this prop is lost.

Would it make sense to always forward `multiple`, assuming that if it's specified the `input` (whatever it is) knows how to handle it? It doesn't seem to make sense to set `multiple` without passing it down, since `useField` *only* takes it into account for `select` components.

**Comment by erikras** [comment]
You _could_ get around this by using a prop name other than `multiple`, but...

**Comment by ThiefMaster** [comment]
yeah, that's the workaround i was using, but not having to do that is cleaner :p

**Comment by pulse00** [comment]
@erikras i was stumbling on this too in one of our apps, can you clarify what the [`multiple`](https://github.com/final-form/react-final-form/blob/b9985e65d0da33b34e72735c1070c4b9a4245b0a/src/Field.js#L18) FieldRenderProp is doing? I can't find it in the documentation (https://github.com/final-form/react-final-form/blob/master/docs/types/FieldRenderProps.md). 

Happy to send an PR if you clarify what it dows.

**Comment by erikras** [comment]
Published fix in [`v6.3.1`](https://github.com/final-form/react-final-form/releases/tag/v6.3.1).
