### ISSUE TITLE
How can I run validation only onSubmit?

### ISSUE THREAD

**Issue by mohsinulhaq** [final-form/react-final-form#556]
## Question
I want to run validation only onSubmit, not onChange, not onBlur. How can I achieve that?

**Comment by erikras** [comment]
With [Submission Errors](https://github.com/final-form/react-final-form#submission-errors). Just return them from your `onSubmit` function.

**Comment by Levino** [comment]
To maybe help others: One has to not pass the validation function to `validate` but call it in `onSubmit` by hand and return the result.
