### ISSUE TITLE
Infinite render when InitialValue props is an object or an array on Field component 

### ISSUE THREAD

**Issue by dayze** [final-form/react-final-form#562]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
There is an infinite render on adapter function when the props ``` initialValue``` is passed and it's type is array or object 

### What is the expected behavior?
No extra renders
### Sandbox Link
Look at the console to see the ``` console.count``` on the component adapter
https://codesandbox.io/s/react-final-form-third-party-components-example-ev4mb

### What's your environment?

```
    "react-final-form": "^6.2.1", 
    "final-form": "^4.13.0",
```
The issue persist on code codesandbox

**Comment by tomolenet** [comment]
Same here on:

```
"final-form": "^4.20.2",
"react-final-form": "^6.5.2",
 ```

Something new on this?
