### ISSUE TITLE
react-native: meta.touched meta.active not working

### ISSUE THREAD

**Issue by rendomnet** [final-form/react-final-form#567]
**bug report** 

Fields do not proved meta support. Like touched, visited, active

### What is the expected behavior?

touched, visited, active change when we use our Fields

### What's your environment?

final-from 4.18.2
react-final-from 6.3.0
react-native 0.59.9
MacOs

**Comment by pavlushkin** [comment]
The possible reason why meta does not work could be that "input" from RFF FieldRenderProps is not passed to the child form element, e.g. <TextInput />.

The code that works:
`        <Field name={name} {...fieldProps}>
            {({ **input**, meta, placeholder }) => {
                const isEditing = meta.active
                const hasError = meta.touched && meta.error
                return (
                    <TouchableWithoutFeedback onPress={() => props.inputRef.current!.focus()}>
                        <View style={[s.input, isEditing && s.inputEditing, hasError && s.inputError]}>
                            <Text style={[s.label, hasError && s.labelError]}>
                                {label} {hasError && <Text>({meta.error})</Text>}
                            </Text>
                            {helpText ? <Text>{helpText}</Text> : undefined}
                            <TextInput
                                **{...input}**
                                style={[s.textInput, hasError && s.textInputError]}
                                onSubmitEditing={props.onSubmitEditing}
                                autoCorrect={false}
                                keyboardType={textInputProps?.keyboardType || 'default'}
                                returnKeyType='next'
                                blurOnSubmit={false}
                            />
                        </View>
                    </TouchableWithoutFeedback>
                )
            }}
        </Field>`
