### ISSUE TITLE
FormSpy onChange and input type="radio"

### ISSUE THREAD

**Issue by bwlt** [final-form/react-final-form#569]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

Don't know why FormSpy onChange callback is called with a wrong FormRenderProps value reference

### What is the expected behavior?
FormSpy onChange callback should be called with valid references

### Sandbox Link

https://codesandbox.io/embed/hardcore-wind-4mgqt

### What's your environment?

    "final-form": "4.18.2"
    "react": "16.8.4"
    "react-dom": "16.8.4"
    "react-final-form": "6.3.0"

### Other information

It happens only with radio components

**Comment by erikras** [comment]
Wow! Great bug catch!

Thankfully, it happens with all components (not just radio).

**Comment by erikras** [comment]
Published fix in [`v6.3.1`](https://github.com/final-form/react-final-form/releases/tag/v6.3.1).
