### ISSUE TITLE
Recommendation/Example for nested forms or Wizard form

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#58]
In redux form there is a Wizard form example, But I want to do something similar where when user selects from a dropdown an option, I want to render different form elements for user to input.

Maybe this is not right way of thinking: But the way im thinking now is , I create various different forms and then on dropdown or click, I render different form to user to input data.

And end of nested form/wizard, if I can have 1 JSON or final values to submit, which is aggregate of all different form values user submitted.

**Comment by erikras** [comment]
Wizard is on my Examples todo list. Fear not! 😄

**Comment by kavink** [comment]
@erikras Thanks, But is a nested form an option ? i.e. I see your example of `Reusable Field Groups` which gives me hope it might, by nested form I mean, value of a key in form can be either `Form1` or `Form2` which would give user different options to enter as the value.

**Comment by kavink** [comment]
@erikras Ill keep an eye out on whenever Wizard example is available.

**Comment by erikras** [comment]
Voilà!

[![Edit 🏁  React Final Form - Wizard Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/km2n35kq3v)
