### ISSUE TITLE
Wizard example - get values in parent

### ISSUE THREAD

**Issue by ryatkins** [final-form/react-final-form#584]
Goal: Display form values outside of Wizard in component

### What is the current behavior?
The parent of the wizard component cannot get access to the form data values.

The wizard example has a parent that sets up the component calls to wizard and wizard.page.  The parent calls the field components.  The form data (values) resides in the wizard components.

### What is the expected behavior?
How do I access the values in Wizard?

Currently I'm trying to do a callback, but with no success.

App.js
```javascript
class App extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      visible: true, myValues: []
    }    
    this.myCallBack = this.myCallBack.bind(this);
  }
 
  myCallBack = (dataFromChild) => {this.setState({myValues: dataFromChild});}

   render() {   
     return (
    <div className="App">
     
  <Styles>
      <Wizard
        initialValues={{  }}
        callbackFromParent={this.myCallBack}
        onSubmit={onSubmit}
           <Wizard.Page>
               <Field />
             ......
            </Wizard.Page>
      </Wizard>
      <DisplayValuesComponent myValues={this.state.myValues} />

```

Wizard.js
```javascript

 next = values => {
    this.setState(state => ({
      page: Math.min(state.page + 1, this.props.children.length - 1),
      values
      
    }))    
    this.props.myCallBack(values)  // added callback when next is called
  }

       render() {

            

       }
```

**Comment by TylerRick** [comment]
Can you show how the callback (`callbackFromParent`) is getting called in Wizard?

**Comment by ryatkins** [comment]
@TylerRick I've update the OP above.
I have two issues:

1. In Wizard.js I need to put my call back into something that updates only on changes for the whole form.  In render it throws an error
2. In App.js for some reason I can't access this.state.myValues, but I have been able to console.log the value coming from Wizard.  Just can't get the scope correct into render I believe.
