### ISSUE TITLE
Migrating examples from CodeSandbox to the examples folder

### ISSUE THREAD

**Issue by CodeWithOz** [final-form/react-final-form#585]
There's a note at the top of the [Examples page](https://final-form.org/docs/react-final-form/examples) that calls for help in moving examples from CodeSandbox to the [examples folder](https://github.com/final-form/react-final-form/tree/master/examples).
I would like to help out with this but I'm not quite sure what is required for migration. I can see that the files in each example's folder match those in the respective CodeSandbox, but the README of each folder contains broken links to the respective sandboxes; "Could not find package.json" is the error message.

It appears that you want the files to be copied from the CodeSandbox to a corresponding subfolder in the examples folder, but I want to be sure before doing anything. I also don't know which CodeSandbox link should be provided in the README for each subfolder, given that those in the current folders are broken as I mentioned earlier. Could you please provide some clarification or a little guide explaining what you want to see in each PR? Thanks.

**Comment by erikras** [comment]
There seems to be a problem with CodeSandbox not liking such long URLs. I filed a bug report, https://github.com/codesandbox/codesandbox-client/issues/2277, and we'll have to wait until that gets sorted. I'm going to replace the relative links to go to the old location in CodeSandbox until then.

Thank you for your eagerness! ❤️

**Comment by CodeWithOz** [comment]
@erikras okay thanks then I'll do the same :+1:.

**Comment by CodeWithOz** [comment]
@erikras I can't seem to install the dependencies. Both npm and yarn complain that a certain `.yalc/final-form` file/folder is necessary but it doesn't exist. Is this something you're aware of? I can't find anything about it online.

**Comment by erikras** [comment]
Oops. My mistake. Should be better now.

**Comment by CodeWithOz** [comment]
#593 

@erikras I did one example in that PR. Let me know if anything needs to change, otherwise I'll do all the others and send them as one PR.
