### ISSUE TITLE
pristine with tiers component

### ISSUE THREAD

**Issue by Gi972** [final-form/react-final-form#59]
### Are you submitting a **bug report** or a **feature request**?
I report a bug

### What is the current behavior?

I  initialized a value, when  I change the value and I come back on the initial value of the select component, the pristine doesn't work.

The values are the same.

I Fork the  Third Party Components example here:

https://codesandbox.io/s/yw6y5y00yx

Thanks @erikras

**Comment by erikras** [comment]
Hmm... It was a conscious decision to only do a shallow equals test for dirty/pristine. Maybe that's just not good enough...

**Comment by Gi972** [comment]
Ok is because I have a nested object

maybe implement the same code that function isEqual from lodash
https://lodash.com/docs/4.17.4#isEqual


or limited the shallow equals with one level of deep in the object

**Comment by erikras** [comment]
That's a _lot_ of code, though. It's a significant portion of the bulk of lodash.

**Comment by Gi972** [comment]
I Have a other suggestion, we want just compare content  Maybe compare two two Json.stringify()  can works.
What do you think ?

**Comment by Gi972** [comment]
after few tests, 
it's a bad idea

**Comment by erikras** [comment]
The answer is that a field can provide its own `isEqual` function to overrride the default `===`.

**Comment by davidhenley** [comment]
But its not pristine anymore because you touched the value.

**Comment by erikras** [comment]
Fixed published in [`final-form@3.0.0`](https://github.com/final-form/final-form/releases/tag/v3.0.0) and [`react-final-form@2.0.0`](https://github.com/final-form/react-final-form/releases/tag/v2.0.0).
