### ISSUE TITLE
submitting form prop is not able to disable button with version 3.6.4 of react-final-form

### ISSUE THREAD

**Issue by SwapneelA** [final-form/react-final-form#612]
### Are you submitting a **bug report** or a **feature request**?
It seems using submitting prop does not disable button on form submit. I am using version 3.6.4. Is there a reported bug with this version of 3.6.4?

### What is the expected behavior?
submitting prop should disable button on form submit.

### What's your environment?

3.6.4 react-final-form
4.8.3 final-form

**Comment by SwapneelA** [comment]
I identified await keyword was missing due to which submitting prop of react-final-form was not working. Closing issue

**Comment by iamskar** [comment]
@SwapneelA can you show where was it missing, please - its not working for me - i can disable the submit button
