### ISSUE TITLE
Form - Enter key to submit form 

### ISSUE THREAD

**Issue by acejusto11** [final-form/react-final-form#613]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Upon hitting submit button, the form is not submitted when hitting Enter key

### What is the expected behavior?
The form should be submitted upon hitting 'Enter key'.
Sample code:
<Form
            validations={VALIDATIONS}
            onSubmit={handleFormValueSubmission}
render={({ submitButtonActive, handleSubmit }) => {
              return (
                <form onSubmit={handleSubmit}>
                        <Button type='submit'>
                </form>
</Form>

### What's your environment?

"react-final-form": "^6.0.1",
Chrome 
Node: 10.15.3

Sample code sandbox:
https://codesandbox.io/s/9ywq085k9w

**Comment by yonahzucker** [comment]
I have almost the same request but with backspace button, so maybe being able to listen to keycode events?

**Comment by tstirrat15** [comment]
I'm seeing that it does submit upon hitting "enter." Where are you seing the problem?

**Comment by il421** [comment]
@tstirrat15 I have the same.  Is it not a bug? As I understand it is en expected behaviour. Can we disable that?

**Comment by tstirrat15** [comment]
@il421 I'm a bit confused. What behavior do you want and what behavior do you see?

I was saying that in the bug report submitted above, they were complaining that the form wasn't submitted when they pressed Enter, but when I went to their sandbox, entered things into the form, and pressed Enter, the form submitted (as I would expect from the way that form is constructed).

**Comment by idangozlan** [comment]
You can wrap your form with
<form onSubmit={handleSubmit}>
....
</form>

it will then perform the native browser behavior for forms, which is Submit on Enter key.

**Comment by joshraker** [comment]
> You can wrap your form with
> 
> ```
> <form onSubmit={handleSubmit}>
> ....
> </form>
> ```
> 
> it will then perform the native browser behavior for forms, which is Submit on Enter key.

My form wasn't submitting on Enter with this alone. I also had to add a `<button>` with `type="submit"` to the form then it started working.

**Comment by alfonsoperez** [comment]
> edit: For anyone else that has their submit button outside their form you can still make Enter work by adding a submit button to the form and setting its style to display: none

A better approach for modern browsers is to use the attribute "form" on the submit button:

https://stackoverflow.com/questions/7020659/submit-form-using-a-button-outside-the-form-tag/12567605#12567605

**Comment by RewriteH** [comment]
Just add <form> insude <Form>: 
```
<Form>
{ 
({handleSubmit}) => 
<form onSubmit={handleSubmit}>
//some fields... 
<button type='submit'>Submit form</button>
</form>
}
</Form>
```
