### ISSUE TITLE
Form level validation is triggered multiple times

### ISSUE THREAD

**Issue by VladShcherbin** [final-form/react-final-form#63]
### Are you submitting a **bug report** or a **feature request**?

A bug or a very unfortunate feature

### What is the current behavior?

When a form is loaded, validation is triggered multiple times.

### What is the expected behavior?

When a form is loaded, validation is triggered once.

### Sandbox Link

https://codesandbox.io/s/v5ywx6nxl

There are 3 fields in the demo, from console log you can see that validation was triggered 4 times.

### What's your environment?

- react-final-form 1.2.1
- final-form 1.3.5

**Comment by erikras** [comment]
Validation is currently triggered on every field registration. However perhaps FF could be switched into "batch" mode until the first form render completes.... Let me think about that...

**Comment by erikras** [comment]
Okay, I've thought about this, and coded some attempted fixes, but it all got ugly very fast. I have reached the following conclusion you might not love:

#### If you're worried about your validation being called too often, you should memoize it yourself.

[Here's an example](https://codesandbox.io/s/wy7z7q5zx5).

**Comment by VladShcherbin** [comment]
@erikras yeah, the conclusion is a really sad one 😢
