### ISSUE TITLE
how to do conditional form fields ?

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#64]
I want user from multi select drop down or checkbox's select  some fields, And based on those fields, show other textfields corresponding to selection.

how do i do something like this ?

**Comment by VladShcherbin** [comment]
@kavink you can use [FormSpy](https://github.com/final-form/react-final-form#formspy--reactcomponenttypeformspyprops) component, which has access to all form values. Based on this values you can render additional fields.

**Comment by kavink** [comment]
@VladShcherbin I haven't yet understood FormSpy completely. Is there an example i can refer on how it works and interact ?

**Comment by VladShcherbin** [comment]
@kavink hm, as far as I can tell you might not even need it. The form also has `values` prop, maybe you use it for what you want to do. Something like this:

```js
<Form
  render={(values) => (
    <Field ... />
    {values.isVisible && <Field ... />}
  )}
/>
```

**Comment by VladShcherbin** [comment]
@kavink something like this one - https://codesandbox.io/s/qz2kr60n39. The remaining problem to solve - remove the value when checkbox is turned off after value was set.

**Comment by kavink** [comment]
@VladShcherbin That seems a good enough example.. i can try to solve on reset. Thanks!

**Comment by VladShcherbin** [comment]
@kavink here is updated example - https://codesandbox.io/s/1qzv7yko6q. Not sure how big this is a hack, but it works :)

**Comment by em-ka** [comment]
How about this one: https://codesandbox.io/s/v355mvn7zy

**Comment by kavink** [comment]
@erikras What would u recommend is the best practice ? 👍

**Comment by erikras** [comment]
> hm, as far as I can tell you might not even need `FormSpy`. The form also has `values` prop.

☝️ Yes. This. @em-ka's example is the best practice.

Only for fine performance tuning will you ever provide a `subscription` prop to `Form` that cuts off your access to `values`. In that case, you would use a `FormSpy`, or even more efficiently, a `Field` component to listen to the value of the field you want to change UI based on.

**Comment by klis87** [comment]
In the @em-ka example, we can see
```js
if(!values.employed) {
  delete values.job
}
```
to remove `job` from `values` which is not needed when `employed` is `false`. However, this seems to be slightly inconvenient, do we have any alternative here?

**Comment by klis87** [comment]
Actually I checked @VladShcherbin clever approach to create dedicated components for this case with
```js
componentWillUnmount() {
  this.props.changeValue(this.props.name, undefined)
}
```
Very nice idea! :+1:

**Comment by romran** [comment]
`componentWillUnmount( )` will always reset value on page change in [Wizard Form](https://github.com/final-form/react-final-form#wizard-form). It is possible to "reset" input field using [Declarative Form Rules](https://github.com/final-form/react-final-form#declarative-form-rules) and [Conditional Fields ](https://github.com/final-form/react-final-form#conditional-fields) 
[Similar example](https://codesandbox.io/s/zwr2o7xo0m) with radio buttons instead of checkbox .

**Comment by yyynnn** [comment]
> `componentWillUnmount( )` will always reset value on page change in [Wizard Form](https://github.com/final-form/react-final-form#wizard-form). It is possible to "reset" input field using [Declarative Form Rules](https://github.com/final-form/react-final-form#declarative-form-rules) and [Conditional Fields ](https://github.com/final-form/react-final-form#conditional-fields)
> [Similar example](https://codesandbox.io/s/zwr2o7xo0m) with radio buttons instead of checkbox .

this one working with any type of field (field value eg true / false), but how to handle validation? field is gone from DOM but not from form state.

**Comment by Filson14** [comment]
> Yes. This. @em-ka's example is the best practice.
That solution is nice and simple but what about a situation, when we want to keep the component visible (the Field one) but disabled? I tried to manage _validation_ value, but it came out that validation runs before rerender of the component.

I've modified a bit @em-ka 's sandbox to show the case. 
https://codesandbox.io/s/x9k1qw7zz4

Here, even the disabled flag works the other way round... (in my project it is rendered correctly) :|

**Comment by Filson14** [comment]
> Yes. This. @em-ka's example is the best practice.

It's nice and simple solution, but what about a case when one want to keep the component visible (rendered) but disabled?

I've modified @em-ka 's example to show my issue.
https://codesandbox.io/s/x9k1qw7zz4

I have a <Form /> without values subscription. One field depends on another, so I use the <Field /> component to get it's value (line 33). Based on it, I am trying do decide if validation should be performed or not. The problem is that, if I toggle the checkbox, the dependent field validation is performed before rerendering, so _validate_ function operates on (de facto) previous flag value.
The result is that it works quite the opposite than I expect.

**Comment by hiei189** [comment]
> `componentWillUnmount( )` will always reset value on page change in [Wizard Form](https://github.com/final-form/react-final-form#wizard-form). It is possible to "reset" input field using [Declarative Form Rules](https://github.com/final-form/react-final-form#declarative-form-rules) and [Conditional Fields ](https://github.com/final-form/react-final-form#conditional-fields)
> [Similar example](https://codesandbox.io/s/zwr2o7xo0m) with radio buttons instead of checkbox .

I'm using this solution but my problem is I'm triggering a side effect when these field changes. But, like the change of the target field doesn't occur at the same render as the change of the condition field, my side effect triggers twice, one with a stale data and the other with right data. My current solutions is debouncing so I always trigger the last one but I'm not sure if this is the right thing. 

Repor is something like [this](https://codesandbox.io/s/react-final-form-wizard-example-t1phm). Try changing both number and then hide field, you're going to receive two alerts.

**Comment by cyonder** [comment]
I developed a similar feature for a product. I solved it in a rather different way. So, I just wanted to share it here in case someone might need it.

Basically use "useState" hook to conditionally render fields. By doing this:

`{option === "internal" && ( <Field name="internal" /> )`
`{option === "external" && ( <Field name="external" /> )`

```
const [option, setOption] = useState()

const handleOptionChange = (value, callback) => {
    setOption(value)
    callback(value)
}

// Use "OnChange" listener for your select 
<OnChange name="sampleSelectField">
    {value => handleOptionChange(value, option => {
        if (option === 'internal') {
            form.change("external", undefined)
        } else if (option === 'external') {
            form.change("internal", undefined)
        }
    })}
</OnChange>
```

https://github.com/final-form/react-final-form-listeners
