### ISSUE TITLE
Bug with square brackets in name Field.

### ISSUE THREAD

**Issue by NozhenkoD** [final-form/react-final-form#665]
Toggling fill type checkbox creates additional value if Field name contains square brackets. 

**Example name** - `Name[]`
**Example code** - https://codesandbox.io/s/delicate-dew-ub6yq

**Comment by bluSCALE4** [comment]
This is by design.
https://final-form.org/docs/final-form/field-names

**Comment by entr** [comment]
A possibility to opt out of this behavior would be nice.
