### ISSUE TITLE
Conditional validation not working

### ISSUE THREAD

**Issue by rendomnet** [final-form/react-final-form#674]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?

I'm validating fields depending on the react state.
```
 <Field
  component={input}
  validate={value =>
                 someState
                    ? isValid(value)
                    : null
                }
```

But when state changes, fields are not revalidated and even when I run handleSubmit it validates using old state value. And only revalidate when I type in some of the fields

How can I rerun validation ?

**Comment by rendomnet** [comment]
Okay I used record level validation and solved my problem

**Comment by KajetanDobczyk** [comment]
Up. I had the same problem - I was using formProps.values in a conditional validation, and those weren't updated on field render. I had to use allValues within field validator for each of the fields instead.
