### ISSUE TITLE
Async field validation: validating prop true when validating field loses focus

### ISSUE THREAD

**Issue by mentallabyrinth** [final-form/react-final-form#676]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

The issue is with async validation for form fields. When the form field is async validating, if the user tabs/clicks away to another field when the validation completes, the `validating` prop remains `true.`

Steps to reproduce:
1. Click on the username field and type a value
2. Immediately tab or click away from the field before async field validation completes.

### What is the expected behavior?

When the async validation completes for a field, the field state will reflect this operation e.g., the `validating` prop will change from false to true.

### Sandbox Link

https://codesandbox.io/s/wy7z7q5zx5

### What's your environment?

- React: 16.8.6
- React DOM: 16.8.6
- React final form: 6.3.0
- Final form: 4.18.6
- Operating system: OSX
- Browsers:  Chrome Version 78.0.3904.97, Firefox: Version 70.0.1, Brave: Version 0.70.122 
- Node: 12.13.0

### Other information

No stack trace because an error is never thrown.

**Comment by NicoleEtLui** [comment]
![Kapture 2019-11-20 at 15 37 32](https://user-images.githubusercontent.com/17101004/69247986-b27bea80-0bab-11ea-9bc6-05216bd7b13b.gif)

**Comment by ahaurat** [comment]
@erikras any guess where the bug might be? I'd be willing to take a shot at a PR but might need a little guidance on a possible starting point...

**Comment by marcin-piela** [comment]
Temporary solution:
https://codesandbox.io/s/react-final-form-asynchronous-field-level-validation-example-pww3l?file=/index.js (run resume validation on blur)

**Comment by AlexAndriyanenko** [comment]
I would like to try to solve this issue.

**Comment by razvanip** [comment]
me 2 :)

**Comment by razvanip** [comment]
@marcin-piela the solution won't work if u have sync and async validations once `input.onBlur()` will need to be called for sync validations to take place.

**Comment by razvanip** [comment]
Not sure why `blur` is breaking this
i guess the `state` of the field is not updating correctly https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L328

and when the new state is `calculated` it will be the same and the registerd field `subscriber` will be called with `validating` true.

but it does not make sense to me why `blur` would cause this, since it just updates a piece of the state and `notifies`, when the `promise` finishes for the `async` validation that should update the `state` and `notify` as well.

`blur` reruns the `validations` only if `focusOnBlur` is passed as prop.

@erikras any hints ?

**Comment by dzienisz** [comment]
Do you have any idea how to solve this?

**Comment by SigurdMW** [comment]
any update here? I'm experiencing the same issue.

**Comment by SigurdMW** [comment]
@erikras if you give me some pointers on where to look, I would like to look into this issue.

**Comment by skbogner** [comment]
@erikras fixed in https://github.com/final-form/final-form/pull/369

Close this issue ?

**Comment by gbakernet** [comment]
final-form/final-form#369 was reverted for causing a regression in v4.20.2. However, if you test the sandbox on version 4.20.4, it doesn't appear to be a reducible problem anymore. One of the changes in v4.20.3 appears to have resolved this. 
https://codesandbox.io/s/react-final-form-asynchronous-field-level-validation-example-forked-4s20w

**Comment by mentallabyrinth** [comment]
No longer and issue in the latest build, closing the ticket. Thank you, @erikras!
