### ISSUE TITLE
ts-essentials should be a dev dependency?

### ISSUE THREAD

**Issue by ntamas** [final-form/react-final-form#682]
### Are you submitting a **bug report** or a **feature request**?

This is (most likely) a bug report.

### What is the current behavior?

Steps to reproduce:

1. Add `react-final-form` as a dependency in a pure JavaScript project
2. Delete `node_modules` and `package-lock.json` (just to have a clean slate)
3. Run `npm install`

Current behaviour:

```
> npm install
[...]
npm WARN ts-essentials@3.0.4 requires a peer of typescript@>=3.5.0 but none is installed. You must install peer dependencies yourself.
```

### What is the expected behavior?

There should be no `npm` warning on the console.

### Sandbox Link

I think it's not relevant here; I cannot demonstrate this in a sandbox.

### What's your environment?

`final-form@4.18.6`, `react-final-form@6.3.3`, macOS 10.14, node 13.1.0, npm 6.12.1

**Comment by srana6** [comment]
As mentioned by @jdolearydl I think ts-essentials should be a devDependency. We use react-final-form in our project and we do not use typescript. Now our builds are failing for the same reason mentioned on this PR and requiring us to add the typescript as the dependency. I don't think we should do that and ship it to the user. Can we fix this issue? Make this a priority?
