### ISSUE TITLE
Submit does not work when <Field /> changes name and have `formatOnBlur`

### ISSUE THREAD

**Issue by gbiryukov** [final-form/react-final-form#695]
### Are you submitting a bug report or a feature request?
Bug report

### What is the current behavior?
Form submit throws error `Cannot read property 'value' of undefined` when form have field with dynamically changed name and specified `formatOnBlur={true}`

Steps to reproduce:
1. open [sandbox link](https://codesandbox.io/s/usefield-obsolete-context-qvvuy)
2. click "use phone"
3. fill anything into input
4. click submit

### What is the expected behavior?
Form submit just works

### Sandbox Link
https://codesandbox.io/s/usefield-obsolete-context-qvvuy

### What's your environment?
react-final-form@6.3.3
final-form@4.18.6
react@16.12.0

**Comment by erikras** [comment]
Published fix in [`v6.3.4`](https://github.com/final-form/react-final-form/releases/tag/v6.3.4).
