### ISSUE TITLE
When using format/parse and add trailing spaces, one trailing dot is added in the input

### ISSUE THREAD

**Issue by yohaydy** [final-form/react-final-form#717]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
When using format or parse and add trailing spaces, one trailing dot is added in the input.

STR:
1. Type any letter in the username field
2. Start adding trailing spaces

Result: instead of second space you get dot + space
![image](https://user-images.githubusercontent.com/7338715/72388194-31f5e800-371d-11ea-9302-f55e32a913ab.png)

(Does not happen if you add spaces slowly one by one)
### What is the expected behavior?
dot should not be added
### Sandbox Link
[https://codesandbox.io/s/10rzowm323](https://codesandbox.io/s/10rzowm323)
(Example from docs)

### What's your environment?
Sandbox

**Comment by andrekutianski** [comment]
how do you resolve this? Can you share the solution?

**Comment by yohaydy** [comment]
> how do you resolve this? Can you share the solution?

This is macOS feature :) double space press adds a a dot
