### ISSUE TITLE
How are large forms structured ? Best Practices question

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#73]
Wondering how to structure large forms using react-final-form, 

Does it all just go in 1 javascript file of all fields or are there examples on how to split up sections of forms in separate components all using same form ? Wizard form looks close enough, but not sure if thats how it should be for non-wizard forms ?

**Comment by erikras** [comment]
That's totally up to you. Different devs have different tolerances for long functions/components/files. If you prefer having everything in one big file, you can do that, or you can break up sections of your form into individual components. Personally, I usually keep it all together unless there is some specific value of having fields in a separate component, e.g. reusability. A good example of that is where I have an app with some onboarding questions when you first log in, and then those same form fields also exist for later editing on an Account page.
