### ISSUE TITLE
Backwards incompatible change in v6.5.3

### ISSUE THREAD

**Issue by MikeTaylor** [final-form/react-final-form#732]
The commit at https://github.com/final-form/react-final-form/commit/f3c1aea93b520c0620f1b8090f5966e0da94a798 has the backwards-incompatible effect of preventing a `<Field>` from using a prop called `data`. We have that does this, and which inexplicably stopped working due to the react-final-form change. (One of our devs spent the whole morning tracking down this action-at-a-distance bug.)

Can this change please be unwound until the next _major_ release, since it's a breaking change?

**Comment by vasilich6107** [comment]
Hi 👋 
Could you move your comments in #725 and close this duplicated issue?

**Comment by MikeTaylor** [comment]
Done. Thanks for the link!
