### ISSUE TITLE
export context, cant use hooks in class components nor events

### ISSUE THREAD

**Issue by AndyOGo** [final-form/react-final-form#745]
### submitting a **feature request**?

It would be great to consume the context directly.

> You can’t use Hooks inside of a class component,
https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

> Call Hooks from React function components.
> Do not call Hooks in class components.
> Do not call in event handlers.
https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions

### What is the current behavior?

No direct access to context, not exported.
And can't use hooks in class components.

### What is the expected behavior?

direct access to context by exporting it, to support access within class components too.

```js
import { ReactFinalFormContext } from 'react-final-form';
```

**Comment by maqduni** [comment]
I also think it'd be useful to have access to the context in class components, otherwise you are forced to create a higher order component with `useForm()` hook and pass the form instance to your class component.

**Comment by dhedegaard** [comment]
Any news on this one?

**Comment by AndyOGo** [comment]
Please see comments in PR for details
https://github.com/final-form/react-final-form/pull/746#issuecomment-605954073
