### ISSUE TITLE
What's the best practice for implementing a normalizer function?

### ISSUE THREAD

**Issue by PaulSavignano** [final-form/react-final-form#75]
Hi Eric,
Excellent library, simply fantastic work here!

Can you share a best practice for implementing a normalizer function?  I'm looking for similar functionality to the normalize prop available to the Field component in redux-form.  I'm able to achieve normalizing through the addition of conditions to an inputs onChange function.  Would this be the recommended approach?

**Comment by PaulSavignano** [comment]
Here is my implementation, feedback would be greatly appreciated.  My example uses adapters for Material UI v1 and an implementation similar to redux form for the normalizer.

TextFieldAdapter
`import React from 'react'
import TextField from 'material-ui/TextField'

const onChangeValue = (value, normalize) => {
  if (normalize) return normalize(value)
  return value
}

const TextFieldAdapter = ({
  children,
  input,
  meta: { error, touched },
  normalize,
  ...rest
}) => (
  <TextField
    fullWidth
    error={touched && Boolean(error)}
    {...input}
    {...rest}
    children={children}
    onChange={({ target: { value }}) => input.onChange(onChangeValue(value, normalize))}
    helperText={touched ? error : ''}
  />
)

export default TextFieldAdapter`

Field
`<Field
    name="phone"
    component={TextFieldAdapter}
    validate={required}
    label="Phone"
    normalize={normalizePhone}
/>`

normalizePhone
`const normalizePhone = value => {
    if (!value) return value
    const onlyNums = value.replace(/[^\d]/g, '')
    if (onlyNums.length <= 3) return onlyNums
    if (onlyNums.length <= 7) return `(${onlyNums.slice(0, 3)}) ${onlyNums.slice(3)}`
    return `(${onlyNums.slice(0, 3)}) ${onlyNums.slice(3, 6)}-${onlyNums.slice(6, 10)}`
}`

Here's a link to a fork of Eric's [codesandbox](https://codesandbox.io/s/50xx8p4y24) that uses normalizers and a few of Material-ui v1's components for anyone interested in implementing a similar feature.

**Comment by erikras** [comment]
Here is a sandbox using the new `parse` and `format` props in [`v2.1.0`](https://github.com/final-form/react-final-form/releases/tag/v2.1.0).

[![Edit 🏁 React Final Form - Parse and Format](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/10rzowm323)

**Comment by PaulSavignano** [comment]
Perfect, thanks Eric!!!

**Comment by erikras** [comment]
Glad you're happy. The name's "Erik", btw. :-)

**Comment by PaulSavignano** [comment]
Opps, sorry about that.  Correcting....
