### ISSUE TITLE
"type" attribute for fields seems to be reserved

### ISSUE THREAD

**Issue by Poyoman39** [final-form/react-final-form#757]
### What is the current behavior?
When adding a "type" attribute on a <Field>, the attribute is not spread on custom input component.

```
<Field
  name="myField"
  type={42}
  component={MyFieldComp} />

const MyFieldComp = props => {
  console.log(props.type) // undefined
  return <input {...props.input} />
}
```

### What is the expected behavior?

"type" attribute should ether be spread on custom input, ether it should be mentioned in the official documentation.

https://final-form.org/docs/react-final-form/types/FieldProps#component
> ... or a component that is given FieldRenderProps as props, children and render props, as well as any non-API props passed into the <Field/> component

**Comment by Poyoman39** [comment]
Note: This is NOT the same as #471 ;)

**Comment by Poyoman39** [comment]
A clean workaround (or maybe the good way to implement custom input) would be to gather the "type" attribute inside the "input" attribute where it seems to land.

```
<Field
  name="myField"
  type={42}
  component={MyFieldComp} />

const MyFieldComp = props => {
  console.log(props.input.type) // 42
  return <input {...props.input} />
}
```

**Comment by ingro** [comment]
Found the same problem after updating to the last release (but I come from 4.x so not sure what release caused the bug)
