### ISSUE TITLE
Fields are still touched when you try form.initialize or form.reset in onSubmit

### ISSUE THREAD

**Issue by marrkeri** [final-form/react-final-form#762]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

const handleSubmit = async (values, form) => {
    // BOTH LINES DO NOT WORK: return new Promise(resolve => resolve(form.reset);
    return new Promise(resolve => resolve(form.initialize(initialValues)));
};

meta.touched is after re-initialization or after reset still true

### What is the expected behavior?

Form should be after form.reset or form.initialize in default state.

### Sandbox Link

Steps:
1. Fill first name (there is validation !value.length) and Submit form
2. Error after re-initialization is visible because of meta.touched

https://codesandbox.io/s/awesome-franklin-symvh

### What's your environment?

"final-form": "^4.18.7",
"react": "16.13.0",
"react-dom": "16.13.0",
"react-final-form": "^6.3.5",
"react-scripts": "3.4.0"

**Comment by marrkeri** [comment]
I have found workaround. Not sure if this is by design and form.initialize should keep touched state.
But with resetFieldState I can achieve what I need

`const handleSubmit = async (values, form) => {
    console.log(values);
    
    Promise.resolve().then(x => {
      form.initialize(initialValues)
      form.resetFieldState('firstName')
    });
  };`

**Comment by gtoland-r7** [comment]
Also seen this, turns out the restart(initialValues) method fixed it

**Comment by enricoschaaf** [comment]
Still having problems with this one any solution?
