### ISSUE TITLE
Recommended validation library 

### ISSUE THREAD

**Issue by bogdansoare** [final-form/react-final-form#78]
Hey there 👋 . What do you recommend for the validation library? 
Formik recommends yup, just curious what final-form does recommend.

Keep up the good work ❤️

**Comment by erikras** [comment]
🏁Final Form is unopinionated. Yup should work fine.

[Here's a list of some](https://github.com/erikras/redux-form/blob/master/tools.md) that work with Redux-Form and should work fine with 🏁React Final Form.

**Comment by bogdansoare** [comment]
@erikras I'm struggling implementing validation with yup, could you please provide a simple example ? it would really help, thanks.

**Comment by OKNoah** [comment]
@bogdansoare 

This might help?

```js
<Form
        onSubmit={this.submitHandler}
        validate={async (values) => {
          const validator = validationSchema(values)

          try {
            await validator.validate(values, { abortEarly: false })
          } catch (err) {
            const what = err.inner.reduce((formError, innerError) => ({
              ...formError,
              [innerError.path]: innerError.message
            }), {})

            return what
          }
        }}
```

**Comment by lookfirst** [comment]
Took the above and turned it into a simple function.

```ts
import {Schema} from "yup";

export function makeValidate<T>(validator: Schema<T>) {
	return async (values: T) => {
		try {
			await validator.validate(values, {abortEarly: false})
		} catch (err) {
			return err.inner.reduce((formError: any, innerError: any) => ({
				...formError,
				[innerError.path]: innerError.message
			}), {});
		}
	};
}
```

```
const validator = yup.object().shape<InvoiceInput>(
	{
		id: yup.string().required().label('Invoice name'),
		date: yup.date().required(),
		purchaseOrder: yup.string().required(),
		supplier: yup.string().required(),
		purchasePrice: yup.string().required(),
		depreciationType: yup.string().required(),
		depreciationStart: yup.date().required(),
		depreciationRate: yup.string().required(),
	}
);
const validate = makeValidate<InvoiceInput>(validator);
```

Hopefully this saves someone 10 minutes. Note that `InvoiceInput` was [auto generated](https://graphql-code-generator.com) from my graphql schema. It would be nice if I could pass a typescript `type` into yup and have it magically generate a schema from that, but not the end of the world to write it out twice, at least it is typesafe.

**Comment by Noitidart** [comment]
@lookfirst that reduce doesn't work with nested or field arrays, I used to do that way to, it is setting `innerError.path`. We have to actually set the shape that the path says. I use lodash `set`:
```
function convertYupErrorsToFieldErrors(yupErrors) {
  return yupErrors.inner.reduce((errors, { path, message }) => {
    if (errors.hasOwnProperty(path)) {
      set(errors, path, get(errors, path) + ' ' + message);
    } else {
      set(errors, path, message);
    }
    return errors;
  }, {});
}
```

**Comment by ziaulrehman40** [comment]
Thanks @Noitidart Working flawlessly!

**Comment by lookfirst** [comment]
I added this without the lodash dependency to my Material UI + RFF library...

https://github.com/lookfirst/mui-rff#helpers
https://github.com/lookfirst/mui-rff/blob/master/src/Validation.ts

**Comment by Noitidart** [comment]
Thanks @ziaulrehman40 ! There was a bug in that, the `if (errors.hasOwnProperty(path))` I had to change to use lodash `get` as well.

@lookfirst we should be able to remove the lodash dependency as final-form exports some helpers:

* getIn - https://final-form.org/docs/final-form/types/Tools#getin
* setIn - https://final-form.org/docs/final-form/types/Tools#setin

**Comment by lookfirst** [comment]
Thanks @Noitidart ... that is helpful... I can use those instead of my own versions and save some bytes....

**Comment by lookfirst** [comment]
@Noitidart I tried them as a drop in replacement and my tests are failing. I'll have to dig into it deeper to see what is going on, but wanted to let you know that they don't seem to be a direct easy replacement.

**Comment by Noitidart** [comment]
Thanks please share your final solution.

**Comment by belliAndrea** [comment]
@Noitidart any news with a final solution?

**Comment by nfantone** [comment]
What about https://gist.github.com/manzoorwanijk/5993a520f2ac7890c3b46f70f6818e0a?

**Comment by nfantone** [comment]
For anyone out there interested in using `yup` with RFF and landing on this issue, here's [my take on a hook](https://gist.github.com/nfantone/9ab600760db8774ab4873cb1a3a22f26) that would allow just that.
