### ISSUE TITLE
What about the TS and Third Party Components ?

### ISSUE THREAD

**Issue by jongleb** [final-form/react-final-form#79]
How do I set a prop that is specific to a third-party library and does not catch an error?
For exmaple
```
<Field
 name="firstName"
 component={SomeComponentFromThirdParty}
 validate={required}
  somePropByThirdParty="AnyValue"
 />
```
I get type error
 TS2339: Property 'somePropByThirdParty' does not exist on type

**Comment by erikras** [comment]
Wow. Good question. Is there some way to specify "and anything else" in the props type for `Field`?

**Comment by geowarin** [comment]
[Yes](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html):

```ts
interface Props {
   [propName: string]: any
}
```
