### ISSUE TITLE
Cannot set a non-numeric property on an array

### ISSUE THREAD

**Issue by nbsobers** [final-form/react-final-form#798]
"Cannot set a non-numeric property on an array" error on my react native form.

I have a react-native page with final-form. This form has a Date picker with field name "documents.certificate.expiryDates". On Date change, App shows the error "Cannot set a non-numeric property on an array".

But if change the Field name to something else Eg: "documents123.certificate.expiryDates".
, it works fine. Can you please help me on this.

"react-native": "0.59.9"
  "react-final-form": "4.1.0",

**Comment by FMGordillo** [comment]
And what happened here?
