### ISSUE TITLE
Autosaving forms

### ISSUE THREAD

**Issue by oyeanuj** [final-form/react-final-form#80]
### Are you submitting a **bug report** or a **feature request**?
Feature Request

Hey @erikras, congrats on a new shinier form library 😄 I wanted to bring back an old feature request on Redux-Form to see how to achieve that with RFF

https://github.com/erikras/redux-form/issues/2169#issuecomment-263112409

Essentially, the usecase is to be able to save form fields `onChange`/`onBlur` and submit only that form field back to the backend. This is super useful for really long forms and often a better UX. 

What do you think would be the way to be able to do that with RFF?

Thanks!

**Comment by stunaz** [comment]
I guess you can use `FormSpy` as specified [https://github.com/final-form/react-final-form/issues/56](https://github.com/final-form/react-final-form/issues/56) and save `onChange`

**Comment by bogdansoare** [comment]
Also interested in an example that has autosave

**Comment by erikras** [comment]
Your wish has been granted.

💥 [Auto-Save Examples](https://github.com/final-form/react-final-form#auto-save-with-debounce) 💥

**Comment by bogdansoare** [comment]
@erikras thank you very much for the examples, really helpful ❤️

**Comment by stunaz** [comment]
Awesome!

**Comment by bogdansoare** [comment]
@erikras another quick question, how would you prevent the saving if the field that has been changed doesn't pass the validation?

**Comment by oyeanuj** [comment]
@erikras @stunaz firstly, thank you for the response and the examples! It almost answers the original request but for one difference: 

ATM, the examples use `FormSpy` to submit all values and then `diff` to see the ones that might have changed. Ideally, given that each field is changed at a time, "we" already know what has changed and should ideally be able to pass just that field and skip the 'diffing' process.

Is there a way that RFF can enable this to be achieved?

**Comment by oyeanuj** [comment]
@erikras Any thoughts on the above request/question?

**Comment by erikras** [comment]
Are you requesting an `onChange` callback for each field?

**Comment by oyeanuj** [comment]
@erikras Yes, I think that would do it if one can then submit from that field. Ideally, I was thinking an `onChangeSubmit` prop API would work best which then connects it to submitting the field. Thoughts?
