### ISSUE TITLE
What about state management?

### ISSUE THREAD

**Issue by a-x-** [final-form/react-final-form#82]
I confused because I didn't find any general purpose state management library mention.

As I understand its Observer pattern does not compatible with redux. What with mobx?
Is final-form vertically integrated and cannot work with usual state management lib?

**Comment by erikras** [comment]
Final Form manages its own state. You put state in, with `initialValues`, and you get state out, with `onSubmit`, and your global app state management solution (GASMS?) need not worry about the state of the form. However, if you _want_ to, you can totally plug update your GASMS with state from Final Form.

I don't _really_ understand your question, so I cannot be certain that I have answered it. ?

**Comment by a-x-** [comment]
Ok, I understand you. I’ll think how applicable that approach for our use-cases. Thank you.

**Comment by erikras** [comment]
👍 Closing, then.

**Comment by IlianYotov** [comment]
I have a related question. Is there an option to pass current values when the form is rendered for the first time. 

Here is an example what use case I want to implement.
I'm fetching a resource from backend to edit and show a form where initialValues are populate from this resource. Then change some fields and destroy the form ( e.g. I can have two tabs and just switch to the next tab and come back later ). The form current values were persisted on componentWillUnmount to some external store ( e.g. localStorage, redux or something else ). Then come back to the form and now I want to set initialValues and currentValues. 

One options is to set currentValues as initialValues, but I will lose pristine and dirty flags. Is there some option to change all current values?
