### ISSUE TITLE
meta.error is an object instead of string in IE11

### ISSUE THREAD

**Issue by gelim92** [final-form/react-final-form#829]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

`meta.error` errors returned from field validators is an object instead of a string in IE11 browser. For example, if I returned "error!" in a field validator, `meta.error` is an object in the form of `{ 0: "e", 1: "r", 2: "r", 3: "o", 4: "r", 5: "!" }` .

Also this only seems to happen on Fields which are a parent of child Fields

### What is the expected behavior?

`meta.error` should be a string instead of an object

### Sandbox Link

https://codesandbox.io/s/final-form-validation-error-ie11-lb9wc?file=/index.js

### What's your environment?

Browser: Internet Explorer 11 version 11.0.9600.19596

"final-form": "4.18.6"
"react-final-form": "6.3.3"
"react": "16.12.0"
"react-dom": "16.12.0",

**Comment by pmomot** [comment]
it's not only IE, I get the same behavior in the latest chrome

**Comment by seunggs** [comment]
Still a problem - seeing this in Chrome as well

**Comment by gertdreyer** [comment]
Please retest with the latest version and see #1007 for the same behaviour on the Form validator.
