### ISSUE TITLE
FormProps interface doesn't support custom props.

### ISSUE THREAD

**Issue by matiosfree** [final-form/react-final-form#864]
### What is the current behavior?
With TypeScript there is an error, when I app extra props.

`<Form
      component={FormComponent}
      onSubmit={handleSubmit}
      onCancel={handleCancel}
    />`

Property 'onCancel' does not exist on type 'IntrinsicAttributes & FormProps<any, Partial<{ firstName: string; }>>'.

### What is the expected behavior?
There should not be any error.

### What's your environment?

"@types/react": "^16.9.49",
"react-final-form": "^6.5.1",

### Other information
For the FieldRenderProps we have:
`[otherProp: string]: any;`

Seems like we need the same for FormProps

**Comment by erikras** [comment]
Published fix in [`v6.5.2`](https://github.com/final-form/react-final-form/releases/tag/v6.5.2).
