### ISSUE TITLE
input[type=checkbox] should behave as select[multiple]

### ISSUE THREAD

**Issue by brikou** [final-form/react-final-form#90]
### Are you submitting a **bug report** or a **feature request**?

I don't know, problably a bug... or a feature :)

### What is the current behavior?

When using using input type="checkbox" we only can get a boolean.

https://codesandbox.io/s/n4ppqq63n0

### What is the expected behavior?

In this example, I really want it to behave as the select with multiple option.

### Other information

Appart from this, lib is perfect :+1: keep the good work

**Comment by crobinson42** [comment]
I'm in the same boat as @brikou doesn't look like there's much testing on checkbox fields, yet.

https://github.com/final-form/react-final-form/blob/95a4c58c9fabbbbca4b892f3c8eb06eab8f214a2/src/Field.test.js#L462

**Comment by erikras** [comment]
Heh. I wrote a long informative comment here, but then my computer crashed.

In short, I considered your request and found it fairly easy to implement.

**Comment by mohadib** [comment]
@erikras any idea when this will be released (pushed to npm repo) ? Thanks.

**Comment by erikras** [comment]
Probably today. I want to knock out a couple of other things and then publish.

**Comment by crobinson42** [comment]
@erikras you rock!

**Comment by erikras** [comment]
Fix published in [`v2.2.0`](https://github.com/final-form/react-final-form/releases/tag/v2.2.0).

**Comment by brikou** [comment]
@erikras thank you

**Comment by borm** [comment]
Hi, how validate it?
As example all checkboxes should be checked

**Comment by erikras** [comment]
@borm Huh? Can you explain further what your requirements are?
