### ISSUE TITLE
Multipart Form Data

### ISSUE THREAD

**Issue by ryan-ds17** [final-form/react-final-form#92]
Can you please provide an example for submitting multipart form data?

**Comment by erikras** [comment]
Final Form manages form data as JSON. If you're doing file uploads, you'll have to get that data from the `<input type="file"/>` component yourself. I use [`react-dropzone`](https://react-dropzone.js.org) in all of my apps that need file uploads.

**Comment by valentynminaiev** [comment]
@erikras could you provide some example with react-dropzone?

**Comment by djeeg** [comment]
I'll post what I figured out

https://codesandbox.io/s/ww5mkm7nn8

If you are using `validateOnBlur `make sure you `props.blur()` in `Dropzone.onDrop`

**Comment by erikras** [comment]
@djeeg Very cool demo... but does that really help you "submit" the file to the server?

File inputs are complicated... 😦

**Comment by djeeg** [comment]
Yeah got this working.

Submit boils down to something like this (sans a chain of redux/redux-saga)

```
const onSubmit = async values => {
	var formData = new FormData();
	formData.append("company", values.company);
	if (values.file_logo && values.file_logo.length > 0) {
		formData.append("file_logo", values.file_logo[0]);
	} else if (values.logourl) {
		formData.append("logourl", values.logourl);
	}
	return fetch("/company/create", {
		method: "POST",
                body: formData,
	})
}
```
