### ISSUE TITLE
Remembering field values between renders

### ISSUE THREAD

**Issue by msageryd** [final-form/react-final-form#923]
I'm not sure if I should post this on SO or here. There might be some existing API that could be used, otherwise this is a feature request, so I'll put it here.

I need to identify every change of value from a couple of check boxes. I cannot use "modified" since this only tells if the field is modified at all since initialisation.

I have a working solution, but It feels convoluted so I wonder if there is a better way to get hold of the previous value for a field. My solution is to put the values in a ref-variable so I can compare with previous values

A more user friendly solution would be if `form` could give me access to prevValues. I'm thinking that these values might exist somewhere in final-form anyway and would be easy to expose.

Here is the essential part of my code.
```
  const changeMemory = useRef({
    includeInk: null,
    includeArrows: null,
    includeHighlights: null,
  });

<Form
    render={({form}) => {
        const {
            includeArrows,
            includeInk,
            includeHighlights,
        } = form.getState().values;

        if (
            changeMemory.current.includeArrows !== includeArrows ||
            changeMemory.current.includeInk !== includeInk ||
            changeMemory.current.includeHighlights !== includeHighlights
        ) {
            //Kick off the async task because a checkbox is altered
            doStuff()
        }

        changeMemory.current.includeArrows = includeArrows;
        changeMemory.current.includeInk = includeInk;
        changeMemory.current.includeHighlights = includeHighlights;

        return (
            //return the actual form components
        )
    }
/>
```

**Comment by agriffis** [comment]
You might want to check out https://github.com/final-form/react-final-form-listeners#onchange

**Comment by msageryd** [comment]
Thanks @agriffis 
Sorry for my delayed reply.
react-final-form-listener seems to solve the problem. But for this specific case I'll keep my solution. I do think I'll use form-listener fro another project where it would fit nicely.
