### ISSUE TITLE
multiple prop is not passed down to custom components

### ISSUE THREAD

**Issue by robdevil** [final-form/react-final-form#934]
Bug report. Issue was "fixed" in 6.3.1 but still appears to exist.

https://github.com/final-form/react-final-form/issues/544

I'm using Semantic React UI 2.02 with react-final-form 6.5.3.

If I try to pass multiple to a custom component the value is ignored and always false.

Custom Component:

import React from 'react';
import { FieldRenderProps } from 'react-final-form';
import { FormFieldProps, Form, Label, Dropdown } from 'semantic-ui-react';

interface IProps extends FieldRenderProps<string, HTMLElement>, FormFieldProps { }

const DropdownInput: React.FC<IProps> = ({
    input,
    inputWidth,
    inputPaddingRight,
    fieldWidth,
    options,
    label,
    search,
    placeholder,
    selection,
    multiple,
    inline,
    onSearchChange,
    disabled,
    meta: { touched, error }
}) => {
    return (
        <Form.Field error={touched && !!error} width={fieldWidth} inline={inline}>
            {label && (
                <label>{label}</label>
            )}
            <label>{multiple ? 'multiple is true' : 'multiple is false'}</label>
            <Dropdown 
                deburr
                clearable
                placeholder={placeholder}
                search={search}
                options={options}
                selection={selection}
                multiple={multiple}
                fluid
                closeOnChange
                onChange={(e, data) => {
                    return input.onChange(data.value);
                }}
                onSearchChange={onSearchChange}
                disabled={disabled}        
                style={{ width: inputWidth, paddingRight: inputPaddingRight }}
            />
            {touched && error && (
                <Label basic color='red' pointing>
                    {error}
                </Label>
            )}
        </Form.Field>
    );
};

export default DropdownInput;

Usage: 

  <Field
      component={DropdownInput}
      deburr
      clearable
      name='contactSkills'
      placeholder='Select skills...'
      selection={true}
      label='Skills'
      search={true}
      multiple={true}
      options={options}
      renderLabel={renderLabel}
  />

If I change the property to anything else, such as multipple, it passes the value of true to the custom component.

**Comment by callmeberzerker** [comment]
Create a sandbox repro and maybe someone will help you out. This low effort copy paste w/o formatting is really bad on your part.
