### ISSUE TITLE
Radio buttons not updating when their values are numeric

### ISSUE THREAD

**Issue by utkarsh22garg** [final-form/react-final-form#941]
### Are you submitting a **bug report** or a **feature request**?

Submitting a bug report.

### What is the current behavior?

Radio buttons are not getting selected in UI, on selection, when their values is numeric.

### What is the expected behavior?

Radio buttons should get selected in UI on option click.

### Sandbox Link

https://codesandbox.io/s/react-final-form-conditional-fields-forked-rndhw

### What's your environment?

React-final-form - 5.0.1

**Comment by utkarsh22garg** [comment]
Any updates here ?

**Comment by BATCOH** [comment]
DOM stores the input field value as a string, not as a number.
You can use `parse` to explicitly convert (text) input value to (numeric) form value:
```jsx
<Field
  name="reception"
  component="input"
  type="radio"
  parse={(v) => parseInt(v, 10)}
  value={1}
/>
```

[Fixed sandbox](https://codesandbox.io/s/react-final-form-conditional-fields-forked-c5clt?file=/src/index.js:2415-2619)

**Comment by utkarsh22garg** [comment]
Thanks @BATCOH this works 👍🏼
