### ISSUE TITLE
Bug: focus doesn't focus on given field

### ISSUE THREAD

**Issue by JasurN** [final-form/react-final-form#958]
**Bug report**

### What is the current behavior?
I was trying to focus on the field when the user press the button, I used focus('fieldName'), but it seems doesn't work.

https://stackoverflow.com/questions/69939197/react-final-form-focus-doesnt-focus-on-given-field

### What is the expected behavior?
It should focus on onClick

### Sandbox Link
https://codesandbox.io/s/condescending-heisenberg-q8dcr?file=/src/App.jsx

### What's your environment?
react-final-form@^6.5.7:
final-form@^4.20.4:
Browser Chrome
Node version v15.14

**Comment by erikras** [comment]
That's not what `form.focus()` does. `form.focus()` tells Final Form that a field has received focus.

You need an actual ref to the DOM node. Like this: https://codesandbox.io/s/mystifying-mestorf-26yv8?file=/src/App.jsx

**Comment by JasurN** [comment]
@erikras Thank you, I understood `focus` incorrectly.
