### ISSUE TITLE
Wizard Form Submitting Validation 

### ISSUE THREAD

**Issue by mertkahramanturk** [final-form/react-final-form#987]
I have a wizard form, I want to submit a validation check and if there is a missing value in the form, I want to direct the user to that page number and show it. Can you help?

**Comment by erikras** [comment]
You'll probably have to maintain a data structure of which fields are on which pages, so you can grab `Object.keys(errors)[0]` and figure out what page that field is on.

**Comment by mertkahramanturk** [comment]
**I solved.** 
 _I added :_ 
`if (!values.personal_name) {
      let personalNameValidation = new Promise(function (resolve) {
        setTimeout(function () { resolve({ personal_name: required() }); }, 100); // should be same field name
      });
      this.setState(() => ({
        page: 0
      })) 
return personalNameValidation `   
_to form **submit** function and added_ 
 ` {(meta.error || meta.submitError) && meta.touched && (
        <span className="form-control-error-label">{meta.error || meta.submitError}</span>
      )}` 
_to my **renderField**._
