### ISSUE TITLE
nested forms not working with functional components [example](https://codesandbox.io/s/p7p6lx24xq)

### ISSUE THREAD

**Issue by jokhuzb1** [final-form/react-final-form#993]
See this working [example](https://codesandbox.io/s/p7p6lx24xq)

_Originally posted by @gvautour in https://github.com/final-form/react-final-form/issues/276#issuecomment-401328415_

i was working with functional components and it does not allow nested form, do I have to use class based components or there is a workaround 

the error i'm getting is "validateDOMNesting(...): <form> cannot appear as a descendant of <form>." 
and i followed as you have shown in the example, but functional components

thanks

**Comment by mikdanjey** [comment]
This is not a nested form, which you mentioned example URL https://codesandbox.io/s/p7p6lx24xq

**Comment by gertdreyer** [comment]
@jokhuzb1 Please see https://github.com/final-form/react-final-form/issues/976#issuecomment-1378855583
